### ISSUE TITLE
Error "Wrong type argument: window-live-p, nil" when executing helm-imenu, after package update

### ISSUE THREAD

**Issue by clearmisp** [emacs-helm/helm#1973] opened 2018-02-23 13:12 UTC
## Expected behavior
helm-imenu should display an helmified imenu list of classes, functions etc in a C++ source file.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
An error is displayed in the mini-buffer and *Messages* buffer saying "Wrong type argument: window-live-p, nil"

## Steps to reproduce (recipe)
Update helm to most recent version on elpa, open a C++ source file, execute helm-imenu.

## Describe versions of Helm, Emacs, operating system, etc.
helm-20180222.2124, GNU Emacs 25.3.1, Linux openSUSE Leap 42.3

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by thierryvolpiatto** [comment] 2018-02-23 14:07
Mikael Springer <notifications@github.com> writes:

> Expected behavior
>
> helm-imenu should display an helmified imenu list of classes, functions etc in a C++ source file.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> An error is displayed in the mini-buffer and Messages buffer saying "Wrong type argument: window-live-p, nil"

This is related to issue #1971 which have been fixed, be sure to have
the last helm version installed and compiled properly, if bug persists,
please send a detailed recipe with a C++ sample file if possible and a backtrace.

> Backtraces if any (M-x toggle-debug-on-error)

Please backtrace.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2018-02-23 14:14
Can't reproduce with basics *.cpp files.

**Comment by Adrilv20** [comment] 2018-02-25 17:00
In case it's of any help, I've encountered this same issue while using helm-gtags, and in my case, it only happens when `helm-autoresize-mode` is enabled.

**Comment by thierryvolpiatto** [comment] 2018-02-25 19:49
Adrilv20 <notifications@github.com> writes:

> In case it's of any help, I've encountered this same issue while using
> helm-gtags, and in my case, it only happens when helm-autoresize-mode
> is enabled.

It helped, I could reproduce, should be fixed now.

Thanks.

--
Thierry

**Closed** 2018-02-27 07:52 UTC
