### ISSUE TITLE
Doesn't include *shell* in completion candidates

### ISSUE THREAD

**Issue by offby1** [emacs-helm/helm#2226] opened 2019-11-14 20:17 UTC
## Expected behavior

I expected to see `*shell*` as one of the lines in the `*helm-mode-switch-to-buffer*` window

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

I saw only `sh` -- i.e., exactly what I'd typed

## Steps to reproduce (recipe)
- Start emacs like `emacs -Q --load /tmp/repro.el`, where the file contains
```
(package-initialize)
(helm-mode 1)
```
Now type
```
ESC x [execute-extended-command]
 s [self-insert-command]
 h [self-insert-command]
 e [self-insert-command]
 l [self-insert-command]
 l [self-insert-command]
 RET [minibuffer-complete-and-exit]
 C-x 0 [delete-window]
 C-x b [switch-to-buffer]
 s [self-insert-command]
 h [self-insert-command]
```
## Backtraces if any (`M-x toggle-debug-on-error`)
n/a
## Describe versions of Helm, Emacs, operating system, etc.
- Emacs is from https://github.com/ochens/emacs/commit/55dcd32ad2209dc34bfb6b713bf73be9bf4c4cb2
- helm is from elpa, in a directory called `helm-20191113.1845`

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

Yes, I tried it as well as my description above; the bug repros in both cases.

## Are you using Spacemacs? (yes/no):
no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment] 2019-11-14 21:18
Seems to be a duplicate of #2224. Perhaps you are not up to date?
I can't reproduce here, see screenshot below:
![Capture d’écran_2019-11-14_22-12-49](https://user-images.githubusercontent.com/1533939/68896819-97812480-072c-11ea-957b-6fc859e8e2ce.png)

**Comment by offby1** [comment] 2019-11-14 21:34
You're right; helm-20191114.1800 seems to work!

Thanks for the quick response!

**Closed** 2019-11-19 12:42 UTC
