### ISSUE TITLE
Unable to scroll past Buffers to Recentf using arrow in Hem-Mini (keeps scrolling inside Buffers list)

### ISSUE THREAD

**Issue by ratnesh1729** [emacs-helm/helm#2633] opened 2023-12-25 18:49 UTC
### What happened?

In helm-mini _ see both Buffers and Recentf list. I am unable to pass from Buffers to Recentf using arrow keys. 
Exactly same as here = https://emacs.stackexchange.com/questions/52356/how-to-navigate-inside-helm-buffer 

I do not want to use C-o - as previously until I switched to emacs-29 I used to just keep scrolling using arrow keys past buffers list to recent files list

### How to reproduce?

On emacs-29 - installing helm is having me above problem

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-29.1

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
The visual picture on SO link in description summarizes the issue
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment] 2023-12-25 19:50
This is a duplicate of #2623.
See `helm-move-to-line-cycle-in-source` variable.

**Comment by ratnesh1729** [comment] 2023-12-25 20:09
thanks!

**Closed** 2024-09-08 05:55 UTC
Labels: bug
