### ISSUE TITLE
Move Helm organization to Savannah / GitLab / NotABug?

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#2054] opened 2018-06-05 13:23 UTC
The recent acquisition of GitHub might serve as a reminder that GitHub may not be an ideal platform for hosting free software projects, especially when GPL-licensed.

What do you people think about moving away from GitHub to more open platforms?

Also see the conversation on Evil Collection's tracker: https://github.com/emacs-evil/evil-collection/issues/141.

**Comment by thierryvolpiatto** [comment] 2018-06-05 14:33
Pierre Neidhardt <notifications@github.com> writes:

> What do you people think about moving away from GitHub to more open
> platforms?

We have to wait to see how github will evolve.
AFAIU microsoft+github is not worst as github alone or google, facebook
etc...

I would love to move to something else like gitlab, but it is for now
unreliable.
I tried to move helm there for a try, after 18h it was still not loaded...
And helm is not a big project.

Savannah would be a big regression, see emacs development, so no I don't
want to move there.

I don't know NotABug.

--
Thierry

**Comment by Ambrevar** [comment] 2018-06-05 15:48
Agreed, the acquisition does not change anything, but as I said it might serve as a good reminder to the free software community on GitHub.

When did you last try GitLab?  Did you experience issues with it recently?  I've been a happy GitLab user ever since I've started using it.

NotABug seems really good in my opinion, it's very light and fast as far as my experience goes.  Do you want to give it a try?

**Comment by thierryvolpiatto** [comment] 2018-06-05 18:04
Pierre Neidhardt <notifications@github.com> writes:

> When did you last try GitLab?

Last 72h and was unable to import helm from github, it hanged forever
last 24h or so.
Also switching to a project takes sometimes 1mn, showing the list of
projects is long as well etc..
After searching the internet, I discovered that this is a known issue
gitlab developers plan to fix.
https://gitlabfan.com/why-gitlab-is-slow-and-what-you-can-do-about-it-bca9d61405bd

> Did you experience issues with it recently? I've been a happy GitLab
> user ever since I've started using it.

Looks fine with small projects, I could import projects like helm-ls-git
(one source file).

> NotABug seems really good in my opinion, it's very light and fast as
> far as my experience goes. Do you want to give it a try?

Why not, but I want to be sure we have most of the features we have
actually in github (PR, bugtracker etc...).


--
Thierry

**Comment by Ambrevar** [comment] 2018-06-05 21:04
Gogs (NotABug's backend) is mostly a Github clone (and it shows!).
So far there are not much of the features of Github that I could not
find back in NotABug.  (Beside project tags maybe?)

**Comment by Ambrevar** [comment] 2018-06-05 21:08
Also the great upside of Gogs, as free software, is that we all can help
implement features.

**Comment by thierryvolpiatto** [comment] 2018-06-06 15:16
NotABug have no import from github function, that's mean we would lost all issues, PR etc...
But I finally could import helm successfully in gitlab, even the wiki have been imported, but org files are not handled, all the wiki would have to be translated to markdown.

**Comment by Ambrevar** [comment] 2018-06-06 15:19
NotABug can import via their RESTful API, I just tried it yesterday:
https://github.com/gogs/go-gogs-client/wiki/Repositories#migrate

See https://gist.github.com/gregdel/870d58c80b80172445dc93294531d88c for a commandline implementation.

If you don't have time to try it out, I could give it a go later (maybe tomorrow).

**Comment by jagrg** [comment] 2018-06-07 02:01
> What do you people think about moving away from GitHub to more open platforms?

Personally I think it's worth the effort. I'll keep an eye on this thread.

**Comment by angela-d** [comment] 2018-06-09 04:51
Not a bug has a migrate button in the GUI as well, I had trouble finding it yesterday myself: [Issue: Import from Github or Gitlab?](https://notabug.org/hp/gogs/issues/167)
The only thing that didn't migrate was the issues.  The wiki's migrated successfully.

Apparently, project tags are coming! 
[Allow adding labels to repositories (feature request)](https://notabug.org/hp/gogs/issues/166)

**Comment by thierryvolpiatto** [comment] 2018-06-09 07:32
Angela <notifications@github.com> writes:

> Not a bug has a migrate button in the GUI as well, I had trouble
> finding it yesterday myself: Issue: Import from Github or Gitlab?  The
> only thing that didn't migrate was the issues. The wiki's migrated
> successfully.

Thanks, I could import helm like this, but the issues are not imported
and the wiki only two pages (not complete).
But that's a good start.

--
Thierry

**Comment by thierryvolpiatto** [comment] 2018-06-09 07:39
Oh! I see the wiki was not fully imported because all files are org files, only markdown files are imported, so after a translation of wiki to MD it should work!

**Comment by Ambrevar** [comment] 2018-06-09 08:08
Well, I think we should rather fix gogs to import Org files :)
It already supports the display of Org `readme` files, so that should not be a big deal.
Could you file an issue there?
https://notabug.org/hp/gogs/issues

I've started opening a bunch of them myself:
- Display image thumbnails in `readme` files.
- Add a search bar. (Is it really missing?!)
- Answer e-mail notifications directly.

**Comment by thierryvolpiatto** [comment] 2018-06-09 08:36
Pierre Neidhardt <notifications@github.com> writes:

> Well, I think we should rather fix gogs to import Org files :)

Of course it would be better.

> 
> It already supports the display of Org readme files, so that should
> not be a big deal.  Could you file an issue there?
> https://notabug.org/hp/gogs/issues

Done.

> I've started opening a bunch of them myself:

Thanks.

>   * Display image thumbnails in readme files.
>   * Add a search bar. (Is it really missing?!)
>   * Answer e-mail notifications directly.

What is very important for helm is to not lost all issues.

-- 
Thierry

**Comment by alphapapa** [comment] 2018-06-10 13:56
As much as I am displeased about Microsoft's crashing this party, let's take this slowly.  Even without Microsoft, GitHub isn't that great of a company in some ways, either.  I'm sure Microsoft will eventually ruin GitHub, but probably at least not until the acquisition is completed.  Let's be sure we don't suffer a downgrade by moving to a worse host.  

For example, other than the reliability issues, GitLab seems like a decent organization, but I think the UI is much inferior to GitHub's, so I'm not a big fan of it.

My 2 cents.   :)

**Comment by alphapapa** [comment] 2018-06-10 13:57
BTW, we might want to bring in all the members of emacs-helm to this discussion.

**Comment by thierryvolpiatto** [comment] 2018-06-10 17:00
alphapapa <notifications@github.com> writes:

> As much as I am displeased about Microsoft's crashing this party,
> let's take this slowly. Even without Microsoft, GitHub isn't that
> great of a company in some ways, either. I'm sure Microsoft will
> eventually ruin GitHub, but probably at least not until the
> acquisition is completed. Let's be sure we don't suffer a downgrade by
> moving to a worse host.

I agree completely.
Be quiet, I will not switch to something else until I am sure we have
something decent and we don't loose our issues, wiki etc...

> For example, other than the reliability issues, GitLab seems like a
> decent organization, but I think the UI is much inferior to GitHub's,
> so I'm not a big fan of it.

Made two attempts to use gitlab and fail, it is unreliable IMHO, would
be a big regression to use this, also I am not sure it will be always
free.

What's looks promising however is NotABug+Gogs, it is fast and reliable, though
not able to migrate issues, wiki etc... for now.

--
Thierry

**Comment by thierryvolpiatto** [comment] 2018-06-10 17:03
See https://notabug.org/emacs-helm/helm

**Comment by Ambrevar** [comment] 2018-06-10 17:17
While GitLab's interface is much more bloated, it also has so much more features.
I have not used it much so far though, so my opinion is a bit limited.

I personally prefer mailing list-based development, should that be an option too.

**Comment by Ambrevar** [comment] 2018-06-10 17:19
@tmalsburg, @lewang, @cofi, @maio, @manateelazycat, @michael-heerdegen, @vapniks, @xiongtx, @xuchunyang, @yasuyk ?

**Comment by tmalsburg** [comment] 2018-06-10 17:41
Moving to a platform whose principles are aligned with ours and free software more generally is worthwhile with and without the Microsoft acquisition.  Having said that, I think GitHub is working really well and it will be hard to find a technically satisfying replacement.  Beyond technical criteria, we should also consider the long term prospects of the candidate platforms.  One issue with NotABug is that I couldn't find out how they are funded.  If it depends on the goodwill of a small number of volunteers, it may not be a sufficiently stable foundation for us going forward.  I expect that a lot is going to happen in this space over the next couple of months. So for now the best we can do might be to observe and learn from other projects' experiences.

**Comment by xiongtx** [comment] 2018-06-10 17:47
The MS acquisition of GitHub has so far changed nothing; if we look at LinkedIn as a precedent, Microsoft has likely learned not to "fix" unbroken things.

Whatever objection to GitHub's non-free practices are as applicable to GitHub before the acquisition as after. If @thierryvolpiatto has found GitHub an acceptable platform so far, there's no reason it wouldn't be now.

We need also consider the opportunity cost of moving the project somewhere else. GitHub has the largest community of developers, many of whom would never have contributed to Helm were it not hosted here.

**Comment by Ambrevar** [comment] 2018-06-10 19:03
GitHub might have been the best option so far but there is always room for improvement and the current situation is a reminder of this, I believe.  Even if nothing has changed, there are a lot of issues with the current platform, both technical and ethical, and the only way to move forward is by making a first step.

> If it depends on the goodwill of a small number of volunteers, it may not be a sufficiently stable foundation for us going forward.

This is very true.  But even more than that, it's a problem inherent to platforms like GitHub, GitLab, NotAbug, etc. where issues and pull requests are centrally stored.  So this is not so much a matter of being a big or small organization, but a matter of design.

If we all trust Git so much for storing our code, it's because we all own a copy of it.  Should a server crash, someone die or any other catastrophe happen, the code will always be "out there".  Issues and pull requests are not quite as safe.

Ultimately, the only right approach to this is to store issues and pull requests "the Git way", that is, everyone owns a copy of the issues & pull requests histories.
Technically, it would not be very hard and it does not cost much, the required storage is about the same magnitude as a git repository.

Mailing-list-based developments are much closer to this approach: lots of people own much of the e-mails (but usually not all of them), and it's universally interfaceable with any e-mail client.  Mailing lists suffer from less popularity and a steeper learning curve mostly because of slightly inferior user interface / user experience (and bad e-mail clients).  For instance it's much less convenient to reference other issues and users and track status of tasks.

GNU debbugs is one attempt at solving all this.  It would certainly deserve some more love though.

**Comment by michael-heerdegen** [comment] 2018-06-11 01:39
@michael-heerdegen: I don't really have an opinion, but for me it feels a bit wrong to leave Github precipitately just because it's Microsoft.  My personal decision was to see what happens and how Microsoft behaves.  If they behave maliciously, we can still leave.  We have licenses that protect our work.  I came to that conclusion after thinking about it very shortly, so feel free to ignore my comment, but I felt asked.

**Comment by thierryvolpiatto** [comment] 2018-06-11 03:37
Titus von der Malsburg <notifications@github.com> writes:

> Moving to a platform whose principles are aligned with ours and free
> software more generally is worthwhile with and without the Microsoft
> acquisition. Having said that, I think GitHub is working really well
> and it will be hard to find a technically satisfying
> replacement. Beyond technical criteria, we should also consider the
> long term prospects of the candidate platforms. One issue with NotABug
> is that I couldn't find out how they are funded. If it depends on the
> goodwill of a small number of volunteers, it may not be a sufficiently
> stable foundation for us going forward. I expect that a lot is going
> to happen in this space over the next couple of months. So for now the
> best we can do might be to observe and learn from other projects'
> experiences.

I completely agree.

--
Thierry

**Comment by thierryvolpiatto** [comment] 2018-06-11 03:38
Pierre Neidhardt <notifications@github.com> writes:

> I personally prefer mailing list-based development, should that be an
> option too.

It is not an option, this lead to a mess like emacs development.

-- 
Thierry

**Comment by Ambrevar** [comment] 2018-06-11 05:54
> We have licenses that protect our work.

If I'm not mistaken, they don't protect issues nor comments.

**Comment by Ambrevar** [comment] 2018-06-11 06:13
Also see https://lwn.net/Articles/702177/ for some interesting arguments
around mailing-list-based development.

**Comment by michael-heerdegen** [comment] 2018-06-11 06:17
Pierre Neidhardt <notifications@github.com> writes:

>  We have licenses that protect our work.
>
> If I'm not mistaken, they don't protect issues nor comments.

What kind of trouble do you expect here?  They could restrict us from
viewing them, or try to hinder us to migrate them.  I guess they can't
do this without changing conducts.  Not sure who owns the rights of
issues and comments, however.

**Closed** 2018-08-24 16:39 UTC
