### ISSUE TITLE
C-x C-f C-c p    no longer populates all the printer instances

### ISSUE THREAD

**Issue by DrWaleedAYousef** [emacs-helm/helm#2187] opened 2019-08-20 04:51 UTC
## Expected behavior
populating all the instances written in `.cups/lpoptions`

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
Only shows the default printer. This happens all the sudden; I did not change any configurations (just the regular updates for archlinux and emacs) 

## Steps to reproduce (recipe)
just do `C-x C-f C-c p` 

## Describe versions of Helm, Emacs, operating system, etc.
`GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12`

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment] 2019-08-20 07:05
Waleed Yousef <notifications@github.com> writes:

> Expected behavior
>
> populating all the instances written in .cups/lpoptions
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Only shows the default printer. This happens all the sudden; I did not
> change any configurations (just the regular updates for archlinux and
> emacs)

I didn't change this since years, so I don't think it is a helm bug.
The function in charge of listing printers is `helm-ff-find-printers`,
it use internally `lpstat`.
What the command "lpstat -a" returns in a terminal?

--
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by DrWaleedAYousef** [comment] 2019-08-20 07:31
This is the output:

RICOH accepting requests since Tue 20 Aug 2019 08:47:10 AM EET


All instances, e.g., RICOH/SINGLE, ..., are not returned. I see, this is
the problem. The instances are not returned by lpstat. I changed nothing
for this to happen!!

**Comment by thierryvolpiatto** [comment] 2019-10-22 10:29
Need to know how to reproduce the old behavior of `lpstat -a`.

**Comment by DrWaleedAYousef** [comment] 2019-10-22 14:29
I have no idea; it seems a bug in Linux! not sure

**Comment by thierryvolpiatto** [comment] 2020-01-12 18:19
Hmm! Just tried now with my new printer and it is recognized immediately and print fine from Helm.

**Comment by DrWaleedAYousef** [comment] 2020-01-12 18:38
It recognize and print; right. But when you configure different printing
options for the same printer and give each a name, these names are not
recognized nor populated.

**Comment by thierryvolpiatto** [comment] 2020-01-12 19:39
Waleed Yousef <notifications@github.com> writes:

> SECURITY NOTE: file ~/.netrc must not be accessible by others
> It recognize and print; right. But when you configure different printing
> options for the same printer and give each a name, these names are not
> recognized nor populated.

Ah, ok, thanks.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2022-06-16 05:02
Tried with two printers and couldn't reproduce, closing, feel free to reopen with a full recipe to reproduce.

**Closed by thierryvolpiatto** 2022-06-16 05:02 UTC
Labels: bug, unrelated, not_reproducible
