### ISSUE TITLE
Helm hangs after deleting a character

### ISSUE THREAD

**Issue by xificurC** [emacs-helm/helm#1505] opened 2016-05-17 08:12 UTC
Latest helm seems to have a bug:

```
emacs -Q
M-x (package-initialize)
M-x (require 'helm)
M-x find-files . <backspace> .
```

This hangs for me. Several other people reported an issue with deleting on spacemacs gitter channel. The above snippet shows that it should be a `helm` issue though.

Let me know if you need more information

**Comment by thierryvolpiatto** [comment] 2016-05-17 08:32
duplicate of #1504

**Closed by thierryvolpiatto** 2016-05-17 08:32 UTC
Labels: duplicate

**Comment by xificurC** [comment] 2016-05-17 10:32
Thanks for the quick fix
