### ISSUE TITLE
Problem with TRAMP SSH double-hop

### ISSUE THREAD

**Issue by xiongtx** [emacs-helm/helm#1598] opened 2016-09-08 16:00 UTC
## Expected behavior

According to the [TRAMP manual](https://www.gnu.org/software/tramp/#Ad_002dhoc-multi_002dhops), we should be able to SSH double-hop as follows using `find-file`:

`C-x C-f /ssh:bird@bastion|ssh:you@remotehost:/path`

## Actual behavior from emacs-helm.sh if possible

I get the following error:

```
Error running timer: (error "In ‘Find Files’ source: ‘helm-find-files-get-candidates’ 
 (user-error \"Host name must not match method \\\"ssh\\\"\")")
```

## Steps to reproduce (recipe)

This can be reproduced with `emacs-helm.sh`.

## Describe versions of helm, emacs, operating system etc.

- Helm 2.1.0
- Emacs 25.1.50.1
- Mac OSX El Capitan

**Comment by thierryvolpiatto** [comment] 2016-09-08 16:38
This have been asked several times (you will find it in issues), please
use instead `tramp-default-proxies-alist`.
It's a headhache to implement this in helm, I have no motivation to
implement this.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-09-08 17:58
See #981

**Comment by xiongtx** [comment] 2016-09-08 18:27
Thanks, I'll take a look.

**Comment by thierryvolpiatto** [comment] 2016-09-10 03:52
Tianxiang Xiong <notifications@github.com> writes:

> Thanks, I'll take a look.

Note that as a workaround you should be able to connect through
helm-find-files like this (assuming C-x C-f is bound to
helm-find-files):

C-x C-f C-k C-!
Enter at prompt your multi-hops address and hit again C-!

--
Thierry

**Comment by thierryvolpiatto** [comment] 2016-09-10 04:03
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Tianxiang Xiong <notifications@github.com> writes:
>
>> Thanks, I'll take a look.
>
> Note that as a workaround you should be able to connect through
> helm-find-files like this (assuming C-x C-f is bound to
> helm-find-files):
>
> C-x C-f C-k C-!
> Enter at prompt your multi-hops address and hit again C-!

To make helm-find-files working without this trick we have to make
this test working (perhaps some clauses are missing):

    (ert-deftest helm--test-ff-set-pattern ()
      (let ((test1  (helm-ff-set-pattern "/ssh:bird@bastion"))
            (test2  (helm-ff-set-pattern "/ssh:bird@bastion:"))
            (test3  (helm-ff-set-pattern "/ssh:bird@bastion|ssh"))
            (test4  (helm-ff-set-pattern "/ssh:bird@bastion|ssh:"))
            (test5  (helm-ff-set-pattern "/ssh:bird@bastion|ssh:you@remotehost"))
            (test6  (helm-ff-set-pattern "/ssh:bird@bastion|ssh:you@remotehost:"))
            (test7  (helm-ff-set-pattern "/ssh:bird@bastion|ssh:you@remotehost:/etc/")))
        (should (string= test1 "Invalid tramp file name"))
        (should (string= test2 "/ssh:bird@bastion:"))
        (should (string= test3 "Invalid tramp file name"))
        (should (string= test4 "/ssh:bird@bastion|ssh:"))
        (should (string= test5 "Invalid tramp file name"))
        (should (string= test6 "/ssh:bird@bastion|ssh:you@remotehost:"))
        (should (string= test7 "/ssh:bird@bastion|ssh:you@remotehost:/etc/"))
        ))

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-09-10 10:15
See PR #1600

**Comment by thierryvolpiatto** [comment] 2016-09-10 10:18
Still have a problem, the root directory is not directly expanded, the helm-buffer stay silently empty until you add a local path (e.g "/etc") at end of pattern.  Hope i will find a fix for this ASAP.

**Comment by thierryvolpiatto** [comment] 2016-09-11 21:19
Please try out tramp_multi_hops branch, more tests I have faster it will
be fixed (The only server I had to test is down until I have the time to
repair it).

-- 
Thierry

**Comment by xiongtx** [comment] 2016-09-12 00:32
I'll try to test it at work over the next few days.

**Comment by thierryvolpiatto** [comment] 2016-09-12 04:18
Tianxiang Xiong <notifications@github.com> writes:

> I'll try to test it at work over the next few days.

Great thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-09-13 09:35
I have now merged the PR #1600  fixing partially this.
It works, I finally could have a chance to test, however at first connection the helm-buffer is not updated
to the default-directory until you start typing something after e.g "/ssh:host|sudo:host:".
The current changes even if not fully working as expected, allows one to use this tramp multi hops syntax which is better than the previous state where an error was popping up as soon as user entered the second ":".
So let this open I will try to fully fix it later.

**Comment by thierryvolpiatto** [comment] 2016-09-16 09:56
Now it is fully working, tested with emacs-24.5, 25.1 and 25.1.50.1.
Additionally, I will try to provide completion on host for second hops.

**Comment by thierryvolpiatto** [comment] 2016-09-21 15:27
Completion done, closing.

**Closed by thierryvolpiatto** 2016-09-21 15:27 UTC
Labels: fixed_wait_confim

**Comment by xiongtx** [comment] 2017-04-27 23:51
Had to use this in anger for the first time today; just wanted to say that I really appreciate you going through the trouble of implementing this!

There seems to be a small issue w/ lack of font-locking, which IIRC was due to performance? Can't find the issue ticket just now; is there an effort to address that or is it an intractable problem?

**Comment by thierryvolpiatto** [comment] 2017-04-28 04:49
Tianxiang Xiong <notifications@github.com> writes:

> Had to use this in anger for the first time today; just wanted to say
> that I really appreciate you going through the trouble of implementing
> this!

Thanks.

> There seems to be a small issue w/ lack of font-locking, which IIRC
> was due to performance?

Yes with or without double-hop, highlighting is disabled by default
because it is too slow (See helm-ff-tramp-not-fancy).
The problem is that all the functions used to get attributes of a file
are too slow (file-attributes and friends), however if you visit small
directories only it is ok to highlight files.

> Can't find the issue ticket just now;

There is none AFAIK.

> is there an effort to address that or is it an intractable problem?

I didn't find anything reliable, though we could differenciate directory
from files by using `file-name-all-completions` instead of
`directory-files` but for e.g symlinks the problem still the same.
I didn't make any effort to use `file-name-all-completions` though as
for now.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by ngleb** [comment] 2018-08-18 13:43
Hi! Thanks for all of your work, that is working very well, especially hosts completion. However, I do have one small problem.

Is it a known issue that `/ssh:user@hostname:/` shows completion for directories on the remote host, but `/ssh:user@hostname|sudo:hostname:/` doesn't?

I tried counsel-find-file and built-in find-file and both of them show competions for files and directories, but I couldn't figure out why I don't have any completions when using `helm-find-files`. The only thing I can do is to hit Enter and it will open dired or make a new file if I guess name correctly.

**Comment by thierryvolpiatto** [comment] 2018-08-19 08:48
Opened a new issue for this, see #2080
