### ISSUE TITLE
Empty helm buffer

### ISSUE THREAD

**Issue by mallet** [emacs-helm/helm#1157] opened 2015-09-08 11:19 UTC
Hello,

Helm buffer is often empty. For example, if I launch helm-find-files, remove everything but "/", all directories are properly shown in helm buffer (bin, boot, dev, ...). But if I type "b" (so, the query is now "/b"), "bin" is not proposed anymore and helm buffer is actually entirely empty. Even the title "Find Files (C-l: Go up one level)" is not there.

I use Emacs 24.5.1 and helm 20150907.2209 from Melpa. I had the same problem with previous versions of helm.

Thanks for your work anyway!

**Comment by thierryvolpiatto** [comment] 2015-09-08 11:38
I can't reproduce, did you try from emacs-helm.sh ?

**Comment by mallet** [comment] 2015-09-09 01:26
Yes, I tried with emacs-helm.sh. Same issue. I have the same problem on another computer, but it is more random on that computer. On the first computer, "/b" absolutely never shows "/bin".

**Comment by thierryvolpiatto** [comment] 2015-09-09 05:04
Vivien Mallet <notifications@github.com> writes:

> Yes, I tried with emacs-helm.sh. Same issue. I have the same problem
> on another computer, but it is more random on that computer. On the
> first computer, "/b" absolutely never shows "/bin".

Hmm, don't know what it could be, I never had this problem, hff is
working fine here on Linux and same on Windows, people are using it on
MacOS also without problems too.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-09-09 05:42
I too saw that problem on occasion, but very seldom.  Sorry, I can't say more, I cannot trigger it at the moment here.  Deleting most or all of the minibuffer content seems to be essential to trigger this issue.

**Comment by thierryvolpiatto** [comment] 2015-09-09 07:02
Michael Heerdegen <notifications@github.com> writes:

> I too saw that problem on occasion, but very seldom. Sorry, I can't
> say more, I cannot trigger it at the moment here. Deleting most or all
> of the minibuffer content seems to be essential to trigger this issue.

This problem can happen if you have special settings with your hard
drive and power settings (hdparm).
So when hff try to access the disk to read file list, the disk is at
that time not awake.

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by mallet** [comment] 2015-09-09 07:39
Can helm-input-idle-delay or helm-idle-delay help in some way?

**Comment by thierryvolpiatto** [comment] 2015-09-09 07:48
Vivien Mallet <notifications@github.com> writes:

> Can helm-input-idle-delay or helm-idle-delay help in some way?

Maybe helm-input-idle-delay, not helm-idle-delay.
After typing "/b" what happen if you hit `C-c C-u' ?

-- 
Thierry

https://emacs-helm.github.io/helm/
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-09-09 07:58
Are you using a clip ring manager such as parcellite or something ?
Or is something accessing your drive frequently ?

**Comment by mallet** [comment] 2015-09-09 08:15
When I hit "C-c C-u", the correct list of files/directories is displayed.

I do not use parcellite, but I have autocutsel running:
autocutsel -fork
autocutsel -selection PRIMARY -fork
autocutsel -selection CLIPBOARD -fork
After killing them, I failed to reproduce the problem. There is a small probability that this is luck because the problem does not raise so often with the updated versions.

As for the drive, not sure. Probably, yes. But the problem also appears on "M-x", so without drives involved. Actually, I have now in front of my eyes the problem again (empty helm buffer), after "M-x" "helm-M", or "hel" (after removing "m-M")...

**Comment by thierryvolpiatto** [comment] 2015-09-14 10:08
Do you have also problems with M-x when autocutsel is disabled ?

**Comment by mallet** [comment] 2015-09-20 14:06
Yes, even without autocutsel, M-x does not show the candidates (empty buffer). It is rare, but it can happen.

**Comment by thierryvolpiatto** [comment] 2015-09-20 16:52
Hmm, I definitely think that we can't do much here, you should look at your system to see what
is taking a lot of memory, cpu usage etc...
We found autocutsel, but I am sure you may find something else slowing down your system.
(e.g If you use a laptop, check if the bug happen more frequently when you use your laptop
on the battery mode)
Let keep this open and tell me what you found.

Thanks.

**Comment by mallet** [comment] 2015-09-20 17:54
Alright. But I have the problem on two different computers, one of which is rather powerful. Most of the time, I have plenty of resources available.

By the way, why would the power of the computer have anything to do with the software behavior? Maybe the implementation could be made more robust? Is there some race somewhere? or an asynchronous process?

**Comment by rdeben** [comment] 2015-10-02 19:25
Hi, I have this issue as well. I'm not familiar with the code, but this is what I think is happening:

There seems to be some non-keystroke event that is breaking the _while-no-input_ loop in _helm--compute-sources_. This causes the matching to stop for the current input. As the event doesn't actually update the minibuffer, it doesn't trigger a recomputation of candidates, so the helm buffer ends up empty.

At least in my case, removing the macro call to _helm--maybe-use-while-no-input_ (leaving the body) in _helm--compute-sources_ fixes the problem completely. The downside is that computing sources becomes blocking, so if you try it, you might want to increase _helm-input-idle-delay_ a bit. I'm using this as a workaround because I prefer the blocking behaviour over having candidades disappear.

I've tried setting a breakpoint with gdb inside the _throw_on_input_ block in _kbd_buffer_store_buffered_event_ (keyboard.c), but I don't get any spurious events. Maybe I could try adding some traces in there.

Any ideas? Can something be done about it in helm?

Thanks for your time.

**Comment by michael-heerdegen** [comment] 2015-10-03 02:44
@rdeben thanks for debugging!

That sounds interesting - and familiar.  Can you please have a look at Emacs bug#19547: 25.0.50; throw-on-input "fires" when switching workspace, if it can help with further debugging?

My conclusion at that time was that `while-no-input' is problematic, but the only way of making Helm behave as we want.  If you've got an idea how to fix this without sacrificing the interruptibility of matching... I didn't find a working one at that time.

**Comment by michael-heerdegen** [comment] 2015-10-03 02:50
BTW there was some compiler option or something like that mentioned by Eli in this thread that can be used to reveal what type of event is causing the interrupt AFAIR.

**Comment by thierryvolpiatto** [comment] 2015-10-03 08:07
rdeben <notifications@github.com> writes:

> At least in my case, removing the macro call to
> helm--maybe-use-while-no-input (leaving the body) in
> helm--compute-sources fixes the problem completely. The downside is
> that computing sources becomes blocking, so if you try it, you might
> want to increase helm-input-idle-delay a bit. I'm using this as a
> workaround because I prefer the blocking behaviour over having
> candidades disappear.

We can't use this, it would be a regression, we have to use while-no-input.

> Any ideas? Can something be done about it in helm?

I finally found a way to reproduce the bug at every time (pressing C-l
very fast in helm-find-files while in a very large directory).

Now when using the fix in PR #1200 I can't reproduce, have a try.

Thanks for your interest into this.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by rdeben** [comment] 2015-10-04 21:06
> We can't use this, it would be a regression, we have to use while-no-input.

I understand. That was more of a suggestion for people having the issue frequently.

> Now when using the fix in PR #1200 I can't reproduce, have a try.

Thanks! I think it's an improvement, because now when an unintended event hits, the buffer keeps the previous candidates instead of being erased. The while-on-input interrupt is still causing some unexpected behaviour, although that probably can't be fixed from the helm side.

I'll try again to find the source of those events.

**Comment by thierryvolpiatto** [comment] 2015-10-05 08:33
rdeben <notifications@github.com> writes:

> Thanks! I think it's an improvement, because now when an unintended
> event hits, the buffer keeps the previous candidates instead of being
> erased.

Exactly.
Note that when you continue typing (or just type C-c C-u) helm is
updating its buffer immediately according to current input.

> The while-on-input interrupt is still causing some unexpected
> behaviour,

Could you describe these unexpected behavior ?

> although that probably can't be fixed from the helm side.

If it comes from while-no-input internal, no, but perhaps we can arrange
to work around this if we exactly know what we are looking after ?

> I'll try again to find the source of those events.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rdeben** [comment] 2015-10-10 12:47
The events causing the issue were SELECTION_REQUEST_EVENT from _autocutsel_. I have to apologise because it was suggested previously and I ignored it. I thought disabling _autocutsel_ didn't fix the problem for the OP, but it does for me. I assume there can be other sources that trigger the same behaviour.

Applying the following patch to Emacs stops the interruptions to while-no-input with _autocutsel_ running:

    --- a/src/keyboard.c
    +++ b/src/keyboard.c
    @@ -3542,7 +3542,8 @@ kbd_buffer_store_buffered_event (union buffered_input_event *event,
           && event->kind != FOCUS_OUT_EVENT
           && event->kind != HELP_EVENT
           && event->kind != ICONIFY_EVENT
    -      && event->kind != DEICONIFY_EVENT)
    +      && event->kind != DEICONIFY_EVENT
    +      && event->kind != SELECTION_REQUEST_EVENT)
         {
           fprintf (stderr, "throw_on_input: event->kind: %d \n", event->kind);
           Vquit_flag = Vthrow_on_input;

Thanks for your support.

**Comment by michael-heerdegen** [comment] 2015-10-10 14:09
That means it was an instantiation of bug#19547.  AFAICT there is no workaround for that problem without modifying Emacs sources.  This will probably bite us again in the future - any event Emacs receives can break `while-no-input' unless explicitly excluded like in the above patch.

**Comment by thierryvolpiatto** [comment] 2015-10-13 07:25
Perhaps one of you can send a bug-report to emacs ?

**Comment by michael-heerdegen** [comment] 2015-10-13 10:14
Thierry Volpiatto <notifications@github.com> writes:

> Perhaps one of you can send a bug-report to emacs ?

Will do.  Dunno yet if I will revive the old bug report or create a new
one.  Note that a good fix for that problem will probably need quite a
lot of work, so it will presumably not happen very soon.

AFAIR the problem is that it is not trivial to decide whether an event
Emacs receives should break a `while-no-input' or not.  There is no
sharp border between events "caused by the user" and that "not caused by
the user".  Think of hitting Alt-Tab on Linux causing frame focus events
and causing Emacs to execute code.  Is this a "user" event - should it
break `while-no-input'?

We currently have a blacklist of events not causing `while-no-input' to
be broken; focus events are among them, and a few other.  But that approach
is obviously only a crutch.

**Comment by michael-heerdegen** [comment] 2015-10-13 10:51
Ok, I've revived the Bug#19547, it had still been open, and CC'd you @thierryvolpiatto.

**Comment by thierryvolpiatto** [comment] 2015-10-13 11:10
Michael Heerdegen <notifications@github.com> writes:

> Ok, I've revived the Bug#19547, it had still been open, and CC'd you @thierryvolpiatto.

Great, thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment] 2015-11-17 22:42
Can't do much more on helm side, so closing now.

**Comment by djr7C4** [comment] 2015-12-03 04:21
This isn't a fix for this bug, but if you want a clipboard manager that doesn't interfere with helm, [clipmon-mode](https://github.com/bburns/clipmon) (which implements a clipboard manager inside Emacs) seems to work well.

**Comment by thierryvolpiatto** [comment] 2015-12-03 05:29
djr7C4 <notifications@github.com> writes:

> This isn't a fix for this bug, but if you want a clipboard manager
> that doesn't interfere with helm, clipmon-mode (which implements a
> clipboard manager inside Emacs) seems to work well.

Looks nice, thanks for the tip!

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by Jehops** [comment] 2015-12-09 18:26
I was about to submit an issue, but found this one.  I occasionally see an empty list of choices when helm is invoked.  After quitting (`C-g`) and trying again, the list of choices is populated as normal.  I managed to capture a little video: https://www.youtube.com/watch?v=kluXEOUa30I.  Of note, I am running clipit (fork of parcellite).

**Comment by thierryvolpiatto** [comment] 2015-12-09 20:24
Yes, this is due to parcellite or similar.
Perhaps @jwiegley can have a look at issue and push to make the necessary change in emacs-25 ;-)

**Comment by jwiegley** [comment] 2015-12-10 20:13
@thierryvolpiatto Bug#19547?

**Comment by thierryvolpiatto** [comment] 2015-12-10 20:38
John Wiegley <notifications@github.com> writes:

> @thierryvolpiatto Bug#19547?

Yes, see the fix proposed by @rdeben in this same issue (#1157).

    @@ -3542,7 +3542,8 @@ kbd_buffer_store_buffered_event (union buffered_input_event *event,
           && event->kind != FOCUS_OUT_EVENT
           && event->kind != HELP_EVENT
           && event->kind != ICONIFY_EVENT
    -      && event->kind != DEICONIFY_EVENT)
    +      && event->kind != DEICONIFY_EVENT
    +      && event->kind != SELECTION_REQUEST_EVENT)
         {
           Vquit_flag = Vthrow_on_input;
           /* If we're inside a function that wants immediate quits,


Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by jwiegley** [comment] 2015-12-10 20:40
How confident are you that this is the right fix?  In the bug thread, he didn't sound sure....

**Comment by thierryvolpiatto** [comment] 2015-12-10 20:52
John Wiegley <notifications@github.com> writes:

> How confident are you that this is the right fix?

I can't tell, the C code of emacs is not familiar to me, I just wanted
you revive this bug report and you give your opinion on this change,
would like also to hear what eli think of this change.
I think this should be fixed in emacs-25, many people are using
parcellite or similar clipboard manager and they will have problem with
emacs in any place using while-no-input.

> In the bug thread, he didn't sound sure....

Yes, perhaps @michael-heerdegen can comment better than me on this.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment] 2015-12-10 22:09
I think it would fix the specific problem, but only one more member of the problem class. We probably should not hardcode a list of dozens of events to exclude at that point in the code.

Fixing the general problem will need some knowlegde and time, I think, and a good idea before that.

**Comment by thierryvolpiatto** [comment] 2015-12-11 05:26
Michael Heerdegen <notifications@github.com> writes:

> I think it would fix the specific problem, but only one more member of
> the problem class.

If fixing this specific problem doesn't cause a problem elsewhere, maybe
it is good to fix it like this waiting something better ?

> We probably should not hardcode a list of dozens of events to exclude
> at that point in the code.

I have no opinion on how to create such a list at the C level (only
for developer maintainance).

> Fixing the general problem will need some knowlegde and time, I think,
> and a good idea before that.

The point is to have a good idea of what are the events that need to be
excluded, or is there another approach for this problem ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by michael-heerdegen** [comment] 2015-12-11 13:38
Thierry Volpiatto <notifications@github.com> writes:

> If fixing this specific problem doesn't cause a problem elsewhere,
> maybe it is good to fix it like this waiting something better ?

Maybe.  In our case: sure.  But Eli was already very cautious when we
changed that code the last time and added a different event type (it was
FOCUS_OUT_EVENT IIRC then).  And we can wait for the next time a
different event type causes the same problem.  Every event causes
while-no-input to stop waiting and breaks helm.  There is currently no
way to decide from inside Emacs if the event was causes directly by user
input (whatever that means, that's a non-trivial problem, think about
it).

> I have no opinion on how to create such a list at the C level (only
> for developer maintainance).

Look some posts above in this thread in github.  They are currently just
listed one after another in a conditional.  But a hardcoded list makes
no sense, it would have to be updated manually whenever there is a new
event type introduced.

> The point is to have a good idea of what are the events that need to
> be excluded, or is there another approach for this problem ?

Before the discussion got stalled, Eli mentioned that the most
appropriate thing to do would be to write a new framework for
classifying input events or something like that.  It's all archived
either in emacs-bugs or emacs-dev, just have a look, look for Elis
answers (near the end, after the discussions about how to debug).


Michael.

**Comment by DamienCassou** [comment] 2016-11-25 12:00
I have the same problem. What is strange is that it never happened before (on NixOS with Gnome and GPaste). Now, I'm on Fedora with Gnome and Clipboard Indicator and I see that all the times. There is no specific patch in NixOS that would fix that bug.

**Comment by thierryvolpiatto** [comment] 2016-11-27 07:09
Probably GPaste is implemented differently and throwing events handled by emacs ?
If you use emacs-26 (master branch from git), could you try the following patch:

```diff
diff --git a/src/keyboard.c b/src/keyboard.c
index 65938a5..3caf506 100644
--- a/src/keyboard.c
+++ b/src/keyboard.c
@@ -3567,14 +3567,22 @@ kbd_buffer_store_buffered_event (union buffered_input_event *event,
 #endif	/* subprocesses */
     }
 
+  Lisp_Object ignore_event;
+
+  switch (event->kind)
+    {
+    case FOCUS_IN_EVENT: ignore_event = Qfocus_in;
+    case FOCUS_OUT_EVENT: ignore_event = Qfocus_out;
+    case HELP_EVENT: ignore_event = Qhelp;
+    case ICONIFY_EVENT: ignore_event = Qiconify;
+    case DEICONIFY_EVENT: ignore_event = Qdeiconify;
+    case SELECTION_REQUEST_EVENT: ignore_event = Qselection_request;
+    }
+
   /* If we're inside while-no-input, and this event qualifies
      as input, set quit-flag to cause an interrupt.  */
   if (!NILP (Vthrow_on_input)
-      && event->kind != FOCUS_IN_EVENT
-      && event->kind != FOCUS_OUT_EVENT
-      && event->kind != HELP_EVENT
-      && event->kind != ICONIFY_EVENT
-      && event->kind != DEICONIFY_EVENT)
+      && !NILP (Fmemq (ignore_event, Vwhile_no_input_ignore_events)))
     {
       Vquit_flag = Vthrow_on_input;
       /* If we're inside a function that wants immediate quits,
@@ -11164,6 +11172,10 @@ syms_of_keyboard (void)
   DEFSYM (Qiconify_frame, "iconify-frame");
   DEFSYM (Qmake_frame_visible, "make-frame-visible");
   DEFSYM (Qselect_window, "select-window");
+  DEFSYM (Qhelp, "help");
+  DEFSYM (Qiconify, "iconify");
+  DEFSYM (Qdeiconify, "deiconify");
+  DEFSYM (Qselection_request, "selection-request");
   {
     int i;
 
@@ -11822,6 +11834,12 @@ signals.  */);
 
   /* Create the initial keyboard.  Qt means 'unset'.  */
   initial_kboard = allocate_kboard (Qt);
+
+  DEFVAR_LISP ("while-no-input-ignore-events",
+               Vwhile_no_input_ignore_events,
+               doc: /* Ignored events from while-no-input.  */);
+  Vwhile_no_input_ignore_events = Qnil;
+    /* = listn (Qfocus_in, Qfocus_out, Qhelp, Qiconify, Qdeiconify, Qselection_request); */
 }
 
 void

```
Then recompile emacs, and once restarted eval this code:

```elisp
(setq while-no-input-ignore-events '(focus-in focus-out help iconify deiconify selection-request))
```
Can you reproduce the bug with this ?

**Comment by thierryvolpiatto** [comment] 2016-11-27 21:10
Now this bug is fixed in Emacs-26, so now a clipboard manager with Emacs-26 should work fine, otherwise
it is suggested to NOT use a clipboard manager along with Emacs versions < 26.

Thanks.

**Closed by thierryvolpiatto** 2016-11-27 21:10 UTC
Labels: emacsbug
