### ISSUE TITLE
Cannot run `find` / `findutils` when `helm-find-files` is a tramp directory?

### ISSUE THREAD

**Issue by wizeman** [emacs-helm/helm#1037] opened 2015-05-28 00:41 UTC
Hi,

When I have a tramp directory opened in `helm-find-files`, such as `/sudo:root@myhost:/some/path`, and then I press `C-c /` to run a recursive `find` command on that directory, `find` is failing because it doesn't understand the path `/sudo:root@myhost:/some/path`.

I'm just a beginner `emacs` and `helm` user, so sorry in advance if I'm not doing something correctly.

**Comment by thierryvolpiatto** [comment] 2015-05-28 04:51
Ricardo M. Correia <notifications@github.com> writes:

> Hi,
>
> When I have a tramp directory opened in helm-find-files, such as
> /sudo:root@myhost:/some/path, and then I press C-c / to run a
> recursive find command on that directory, find is failing because it
> doesn't understand the path /sudo:root@myhost:/some/path.

Indeed it is not working actually, broken by previous changes.
I will try to fix it, but no guarantee it will work.
The problem is that the find command is build with a tramp name, i.e
"find /sudo:host@user:/path/to/dir -name ..." which is not supported.
it should be called against the local name i.e
"find /path/to/dir -name ..."
with default-directory bound to the tramp name.
And `non-essential` let-bound to a non--nil value (maybe it is already
done, didn't check).

Anyway you have to know that processes with helm (grep, find)
are working badly against tramp due to the incremental nature of helm.
In fact each time you enter a character in the prompt, a new process
start with this new pattern (the previous process is killed) and tramp
accept process calls all the around 5s, no less.
We have a function that is called by hook in sentinels that delay the
processes but it still slow.
The best is using "C-!" to suspend all processes, enter pattern and then
hit again "C-!" to restart process.

So in practice for now, you have better time use find locally and when
your file is found jump to it with find file as root (see actions).
And for remote hosts (ssh) you have better time using a `sshfs` mount
instead of tramp.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-05-29 08:42
Should be fixed now.

**Comment by wizeman** [comment] 2015-05-29 15:13
It seems to work now. Thanks!

**Closed** 2015-06-02 13:58 UTC
Labels: bug, fixed_wait_confim
