### ISSUE TITLE
helm completing read causes 100% cpu usage when invoked via floobits on emacs 25

### ISSUE THREAD

**Issue by aaronjensen** [emacs-helm/helm#1437] opened 2016-03-21 04:48 UTC
See: https://github.com/Floobits/floobits-emacs/issues/87

On emacs 25, with helm-mode and floobits, if you attempt to share a workspace emacs will hang and use 100% cpu. 

Of special note is that floobits uses python externally and it is python that invokes the completing-read via event.

This does not repro on emacs 24 or with the built-in completing-read

**Comment by aaronjensen** [comment] 2016-03-21 05:40
I tracked it down to this line: https://github.com/emacs-helm/helm/blob/master/helm.el#L3870

If that line is commented out, the hang does not happen.

**Comment by thierryvolpiatto** [comment] 2016-03-21 08:07
Please elaborate, I don't know what floobit is and what it does.

What is "helm completing read" ?

-- 
Thierry

**Comment by michael-heerdegen** [comment] 2016-03-21 13:28
I can see nothing wrong with that line you commented out.  So I guess this is more likely a bug in floobits-emacs.

**Comment by aaronjensen** [comment] 2016-03-21 14:45
@thierryvolpiatto Floobits is a remote pair programming/cross editor collaboration tool. It has an emacs plugin here: https://github.com/Floobits/floobits-emacs

It uses `completing-read` to get user input.

`helm-mode` has a `completing-read` replacement, so that when library users use `completing-read` if `helm-mode` is active they will get helm instead. If `helm-mode` is disabled, they get the normal `completing-read` behavior.

@michael-heerdegen it may be that `floobits-emacs` is using `completing-read` in a bad way, but even if so, `helm` appears to be the one causing the actual crash/infinite loop. Also, this is only an emacs 25 issue, so this could actually be an emacs bug that helm is triggering (which floobits-emacs is, in turn, triggering)

**Comment by michael-heerdegen** [comment] 2016-03-21 15:05
Aaron Jensen <notifications@github.com> writes:

> @michael-heerdegen it may be that floobits-emacs is using
> completing-read in a bad way, but even if so, helm appears to be the
> one causing the actual crash/infinite loop.

What makes you think so?  Helm may be doing something that is part of a
recipe to produce the problem, but that doesn't mean Helm is the cause
of it.

> Also, this is only an emacs 25 issue, so this could actually be an
> emacs bug that helm is triggering (which floobits-emacs is, in turn,
> triggering)

If you can reproduce it, I suggest to try the usual steps: use
profiler.el to find out what code is looping, if you are able to get
Emacs back to life again.  Try to get a backtrace from within the
endless loop (in Unix, sending SIGUSR2 can force a frozen Emacs into the
debugger).

**Comment by aaronjensen** [comment] 2016-03-21 15:18
> If you can reproduce it, I suggest to try the usual steps: use
> profiler.el to find out what code is looping, if you are able to get
> Emacs back to life again.  Try to get a backtrace from within the
> endless loop (in Unix, sending SIGUSR2 can force a frozen Emacs into the
> debugger).

I can reproduce it very easily. It hangs emacs completely, however and SIGUSR2 does not drop to debugger, I have to kill emacs to get anywhere. Is there a way to write a profile to a file in real time or anything else that may be able to show me the loop?

**Comment by aaronjensen** [comment] 2016-03-21 15:22
It appears to be something in the `pref` that is required to trigger it. If I replace the questionable line with

```elisp
        (setq header-line-format (concat " " cont " "))
```

It does not trigger.

**Comment by michael-heerdegen** [comment] 2016-03-21 16:06
Aaron Jensen <notifications@github.com> writes:

> It appears to be something in the pref that is required to trigger
> it. If I replace the questionable line with
>
>         (setq header-line-format (concat " " cont " "))
>
> It does not trigger.

I guess that the process or python stuff floobits starts infloops.  Or
the display engine.

Anyway, would do you want us to do?  Setting the header line to some
string is surely no bug in helm.

I suggest to try to derive a recipe that works independently from helm -
or independently from floobit.

For the start, you could try whether setting the header-line Helm uses
in some other buffer to the value that causes the problem, with Helm
then turned off, and try whether using floobit stuff already triggers
the problem.

Or try to turn off Helm, start floobit sharing, and turn it on again.
Etc.  We have definitely not enough information to localize the problem.

**Comment by aaronjensen** [comment] 2016-03-22 05:31
On my current setup, this alone repros for me:

```elisp
(setq header-line-format #("  " 0 1 (display #("->" 0 2 (face helm-header-line-left-margin)))))
```

I'm guessing this is either an emacs bug or something very strange w/ my setup or theme or...? I don't have a repro from `emacs -Q` yet, just defining the face and executing that isn't enough.

**Comment by michael-heerdegen** [comment] 2016-03-22 14:44
Ah, I see you were successful, found your bug report in emacs-bugs.
Thanks for investigating...so I think we can close this issue here, right?... Done.

**Closed by michael-heerdegen** 2016-03-22 14:44 UTC

**Comment by aaronjensen** [comment] 2016-03-22 14:48
Yep, thanks!
