### ISSUE TITLE
M-x ^   in helm

### ISSUE THREAD

**Issue by OrionRandD** [emacs-helm/helm#2426] opened 2021-06-17 11:43 UTC
how do I make my emacs "M-x" search always start with beggining of line
    character. Like so:                                                                
    M-x ^                                                                              
    and then write whichever letter I want...                                         
    M-x ^a (b..z)              
I tried:
(global-set-key "\370" 'helm-M-x ^)  
But did not work                                                                                                          

In ivy it is the
ivy-initial-inputs-alist

**Comment by thierryvolpiatto** [comment] 2021-06-17 16:10
Duplicate of #2340, please post there instead. Thanks.

**Closed by thierryvolpiatto** 2021-06-17 16:10 UTC
