### ISSUE TITLE
(helm-org-in-buffer-headings) retuns list of nil entries

### ISSUE THREAD

**Issue by Mafeuser** [emacs-helm/helm#2243] opened 2019-12-04 06:38 UTC
## Expected behavior
it should return list of all headings

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
list of nil entries is returned

## Steps to reproduce (recipe)
I just run run spacemacs

## Describe versions of Helm, Emacs, operating system, etc.
helm-core-20191203.642

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
no

## Are you using Spacemacs? (yes/no):
yes
just downloaded

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

I'm running emacs 25.3 compiled from sources.
I've just upgraded all the packages. previous upgrade was several months ago.

As helm-org-in-buffer-headings looks like following:

```
(defun helm-org-in-buffer-headings (&optional arg)
  "Preconfigured helm for org buffer headings."
  (interactive "P")
  (let ((files (list (current-buffer))))
    (unwind-protect
        (helm :sources (helm-org-build-sources
                        files nil (or arg helm-org--force-refresh))
              :preselect (helm-org-in-buffer-preselect)
              :truncate-lines helm-org-truncate-lines
              :buffer "*helm org inbuffer*")
      (setq helm-org--force-refresh nil))))
```

To narrow down the problem I've just issued the following:

`(helm-org-build-sources (list (current-buffer)) nil nil)
`

and it returns proper list of headings.

helm-org--force-refresh is nil in my org buffer 
helm-org-headings-max-depth keeps value 10 in my org buffer

**Comment by thierryvolpiatto** [comment] 2019-12-04 09:18
Mafeuser <notifications@github.com> writes:

> Expected behavior
>
> it should return list of all headings

It does, just tried from emacs-25.3.

> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> list of nil entries is returned

Can't reproduce.

> Steps to reproduce (recipe)
>
> I just run run spacemacs

Do you think this is a good recipe to reproduce your bug?

> Backtraces if any (M-x toggle-debug-on-error)
>
> Describe versions of Helm, Emacs, operating system, etc.
>
> helm-core-20191203.642
>
> Are you using emacs-helm.sh to reproduce this bug? (yes/no):
>
> no

Why?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2019-12-04 09:25
Closing, please make a bug report starting either from emacs-helm.sh or from a minimal helm installation from emacs -Q and with a recipe describing exactly what you are doing.
For helm-org please make the bug report at https://github.com/emacs-helm/helm-org, not here.
Thanks.

**Closed by thierryvolpiatto** 2019-12-04 09:25 UTC
Labels: InvalidBugReport
