### ISSUE TITLE
Symbol's value as variable is void: helm-info-source

### ISSUE THREAD

**Issue by eamonnsullivan** [emacs-helm/helm#2609] opened 2023-08-01 11:10 UTC
### What happened?

I pulled the master branch this morning, for the first time in a week. I get the following error after compilation on 29.1.
```
⛔ Error (use-package): helm/:catch: Symbol’s value as variable is void: helm-info-source
⛔ Error (use-package): helm-ag/:catch: Symbol’s value as variable is void: helm-info-source
⛔ Warning (initialization): An error occurred while loading ‘/home/eamonn/.config/emacs/init.el’:

Symbol's value as variable is void: helm-info-source

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```
The issue goes away if I roll back to commit c859db76283068a38270cd833d1b84e2fec3683c.

### How to reproduce?

```
(use-package 'helm)

### Helm Version

Master branch

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (void-variable helm-info-source)
  byte-code("\301\10\302 \303\304\305\306\"\307\305\310\"\311\305\312\"\313\305\314\"$#\207" [helm-info-source defclass helm-source-in-buffer (info-file :initarg :info-file :initform nil :custom 'string) init :initform helm-info-init display-to-real helm-info-display-to-real get-line buffer-substring action (("Goto node" . helm-info-goto))] 10)
  require(helm-info)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310%\210\311\312\313\314\315DD\316\317\320\321\322&\7\207" [require helm-lib helm-info custom-declare-group helm-global-bindings nil "Global bindings for Helm." :group helm custom-declare-variable helm-command-prefix-key funcall function #f(compiled-function () #<bytecode -0x12770f62746e04b3>) "The prefix key used to call Helm commands from the..." :type (choice (string :tag "Key") (const :tag "no binding")) :set #f(compiled-function (var key) #<bytecode -0x10e40ed6536f65a5>)] 8)
  require(helm-global-bindings)
  byte-code("\300\301!\210\300\302!\210\303\304!\207" [require helm-core helm-global-bindings provide helm] 2)
  require(helm)
  load-with-code-conversion("/home/eamonn/.config/emacs/lisp/init-projectile.el" "/home/eamonn/.config/emacs/lisp/init-projectile.el" nil t)
  require(init-projectile)
  load-with-code-conversion("/home/eamonn/.config/emacs/init.el" "/home/eamonn/.config/emacs/init.el" nil nil)
  load-file("~/.config/emacs/init.el")
  funcall-interactively(load-file "~/.config/emacs/init.el")
  command-execute(load-file record)
  execute-extended-command(nil "load-file" "load-file")
  funcall-interactively(execute-extended-command nil "load-file" "load-file")
  command-execute(execute-extended-command)
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by eamonnsullivan** [comment] 2023-08-01 11:17
Sorry I was getting confused with my frames. The stacktrace I get from `emacs -Q` and `(use-package 'helm)` is a bit different: 
```
Debugger entered--Lisp error: (void-variable helm-info-source)
  byte-code("\301\10\302 \303\304\305\306\"\307\305\310\"\311\305\312\"\313\305\314\"$#\207" [helm-info-source defclass helm-source-in-buffer (info-file :initarg :info-file :initform nil :custom 'string) init :initform helm-info-init display-to-real helm-info-display-to-real get-line buffer-substring action (("Goto node" . helm-info-goto))] 10)
  require(helm-info)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310%\210\311\312\313\314\315DD\316\317\320\321\322&\7\207" [require helm-lib helm-info custom-declare-group helm-global-bindings nil "Global bindings for Helm." :group helm custom-declare-variable helm-command-prefix-key funcall function #f(compiled-function () #<bytecode -0x12770f62746e04b3>) "The prefix key used to call Helm commands from the..." :type (choice (string :tag "Key") (const :tag "no binding")) :set #f(compiled-function (var key) #<bytecode -0x10e40ed6536f65a5>)] 8)
  require(helm-global-bindings)
  byte-code("\300\301!\210\300\302!\210\303\304!\207" [require helm-core helm-global-bindings provide helm] 2)
  require(helm)
  load-with-code-conversion("/home/eamonn/.config/emacs/lisp/init-projectile.el" "/home/eamonn/.config/emacs/lisp/init-projectile.el" nil t)
  require(init-projectile)
  load-with-code-conversion("/home/eamonn/.config/emacs/init.el" "/home/eamonn/.config/emacs/init.el" nil nil)
  load-file("~/.config/emacs/init.el")
  funcall-interactively(load-file "~/.config/emacs/init.el")
  command-execute(load-file record)
  execute-extended-command(nil "load-file" "load-file")
  funcall-interactively(execute-extended-command nil "load-file" "load-file")
  command-execute(execute-extended-command)
```

**Comment by thierryvolpiatto** [comment] 2023-08-01 17:01
I am closing this as it is a duplicate of #2608 .

**Closed** 2023-08-01 17:02 UTC
Labels: bug
