### ISSUE TITLE
helm-ff-skip-boring-files no longer does as advertised

### ISSUE THREAD

**Issue by TheBB** [emacs-helm/helm#1391] opened 2016-02-15 14:22 UTC
To reproduce:

1. `./emacs-helm.sh`
2. `(setq helm-ff-skip-boring-files t)`
3. Add some filename to `helm-boring-file-regexp-list` that is in your current directory (by default I have `\.elc$` there and the helm directory is full of elc files, so this can be skipped)
4. `C-x C-f`

Expected behaviour: No elc files in the list.
Observed behaviour: Lots of `nil` in the list corresponding to where the elc files would have been.

**Comment by michael-heerdegen** [comment] 2016-02-15 17:58
Indeed, I can reproduce.  This bug must have been introduced within the last seven or eight days.

**Comment by michael-heerdegen** [comment] 2016-02-15 18:23
@thierryvolpiatto the first bad commit seems to be a07cb1e1e741bd8c51c151945ff20e5d415c7a83 "Get rid of helm--accumulate-candidates in helm-match-from-candidates." that rewrites `helm-match-from-candidates`.

**Comment by thierryvolpiatto** [comment] 2016-02-15 18:37
Michael Heerdegen <notifications@github.com> writes:

> @thierryvolpiatto the first bad commit seems to be a07cb1e "Get rid of
> helm--accumulate-candidates in helm-match-from-candidates." that
> rewrites helm-match-from-candidates.

Will fix next week.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-02-22 11:35
Should work now, please confirm.

**Comment by TheBB** [comment] 2016-02-22 12:04
Yep, it's good.

**Comment by TheBB** [comment] 2016-02-23 08:03
Sorry to bother but this reproduces again on the current master.

**Comment by thierryvolpiatto** [comment] 2016-02-24 11:35
Here a simple test where I expect helm showing only foo.el and bar.el:

```elisp
(helm :sources (helm-build-sync-source "test"
                 :candidates '("foo.el" "foobar.o" "foo.i" "foo.la" "bar.el" "bar.i")
                 :candidate-transformer '(helm-skip-boring-files helm-highlight-files))
      :buffer "*helm test*")
```
![screenshot - 24022016 - 12 32 59](https://cloud.githubusercontent.com/assets/1533939/13284167/d99cf34a-daf2-11e5-8cfa-bf90c19f825f.png)

**Comment by thierryvolpiatto** [comment] 2016-02-24 11:35
So your bug is not reproductible with this test.

**Comment by thierryvolpiatto** [comment] 2016-02-24 11:42
But yes I have it now with helm-find-files, will fix soon.

**Comment by TheBB** [comment] 2016-02-24 12:01
Yep, thanks. Appears to be fixed again.

**Comment by thierryvolpiatto** [comment] 2016-02-25 10:54
Thanks, closing now.

**Closed by thierryvolpiatto** 2016-02-25 10:54 UTC
