### ISSUE TITLE
C-l doesn't work every first time on M-x helm-find-files

### ISSUE THREAD

**Issue by alpha22jp** [emacs-helm/helm#1076] opened 2015-06-24 12:58 UTC
When I invoke `M-x helm-find-files` and press `C-l` to go up one level, it doesn't work only for the first time. It works if I press `C-l` twice though.

This problem looks to have been arising since 2ac73e1. Could you take a look at this issue?

**Comment by thierryvolpiatto** [comment] 2015-06-24 15:44
alpha22jp <notifications@github.com> writes:

> When I invoke M-x helm-find-files and press C-l to go up one level, it
> doesn't work only for the first time. It works if I press C-l twice
> though.

Please be sure you have compiled correctly helm and try from
./emacs-helm.sh.

I can't reproduce this (I use helm-find-files all the time when on
emacs).

> This problem looks to have been arising since 2ac73e1.

helm--maybe-update-keymap take now one more arg, I guess your helm.el
have been badly compiled.

> Could you take a look at this issue?

For now I can't do anything since I have no backtrace and I can't
reproduce myself.
We let this open and wait for more infos.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-06-24 16:11
FWIW I can't reproduce it neither.

**Comment by alpha22jp** [comment] 2015-06-25 10:43
Thanks for a quick response.

I can reproduce the issue with `emacs-helm.sh` actually. I tested it as below.

```
$ git clone https://github.com/emacs-helm/helm.git
$ cd helm
$ git co 2ac73e1
$ make clean; make
$ ./emacs-helm.sh
```

The problem doesn't occur if I replace 2ac73e1 with d2ae934. I'm using Emacs 24.3.1 on ubuntu 14.04 64bit. Is there anything what I can do to find out the cause?

**Comment by michael-heerdegen** [comment] 2015-06-25 11:10
What is "git co"?

**Comment by alpha22jp** [comment] 2015-06-25 11:59
Sorry, it's alias of `git checkout` I locally define.

**Comment by thierryvolpiatto** [comment] 2015-06-25 12:01
alpha22jp <notifications@github.com> writes:

> Thanks for a quick response.
>
> I can reproduce the issue with emacs-helm.sh actually. I tested it as below.
>
> $ git clone https://github.com/emacs-helm/helm.git
> $ cd helm
> $ git co 2ac73e1
> $ make clean; make
> $ ./emacs-helm.sh
>
> The problem doesn't occur if I replace 2ac73e1 with d2ae934. I'm using
> Emacs 24.3.1 on ubuntu 14.04 64bit.

Still unable to reproduce on emacs-24.3.1, did you compile your emacs
yourself or you are using the version provided by ubuntu ?

> Is there anything what I can do to find out the cause?

Is there other keys not working (e.g C-]) ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by alpha22jp** [comment] 2015-06-25 12:25
> did you compile your emacs yourself or you are using the version provided by ubuntu ?

I'm just using the provided version.

> Is there other keys not working (e.g C-]) ?

`C-]` isn't working either. When I press `C-]`, helm buffer disappears and the cursor goes back to the current buffer. Also, I found that both `C-l` and `C-]` work after pressing any other key like `C-n`. They don't work only when I press them right after `M-x helm-find-files`.

**Comment by alpha22jp** [comment] 2015-06-25 12:46
I tested emacs-24.3 and emacs-24.5 which I compiled by myself. The former was the same as the provided version, but the latter worked fine. So this issue looks to be emacs version dependent problem.

**Comment by thierryvolpiatto** [comment] 2015-06-25 12:53
alpha22jp <notifications@github.com> writes:

>     did you compile your emacs yourself or you are using the version provided by ubuntu ?
>    
> I'm just using the provided version.

So here is the problem, I guess they have done some bad things in the
startup file, or added an unwanted minor-mode.
BTW note that 24.3 is deprecated, we are now at 24.5...

>
>     Is there other keys not working (e.g C-]) ?
>    
> C-] isn't working either. When I press C-], helm buffer disappears and
> the cursor goes back to the current buffer.

Hmm, that's the global binding which is running.

> Also, I found that both C-l and C-] work after pressing any other key
> like C-n. They don't work only when I press them right after M-x
> helm-find-files.

Ok, any other keys not working ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-06-25 13:29
Thierry Volpiatto <notifications@github.com> writes:

> Hmm, that's the global binding which is running.

It could be that for some reason, Emacs first doesn't get idle after
starting helm-find-files, so the timer in `helm--maybe-update-keymap'
doesn't fire.

@alpha22jp you could test this by evaluating

(defun helm--maybe-update-keymap (&optional map)
  (with-helm-buffer
    (helm-aif (or map (assoc-default 'keymap (helm-get-current-source)))
        (run-with-idle-timer
         0.01 nil
         `(lambda ()
            (message "!!!")
            (message nil)
            (with-current-buffer
                (window-buffer (minibuffer-window))
              (setq minor-mode-overriding-map-alist
                    '((helm--minor-mode . ,it)))))))))
                    
and watch *Messages* while performing the test.  When does the first
"!!!" appear in *Messages*?


OTOH it could be a problem with keymap installation in older Emacs
version.  I once too had a problem where user visible key bindings were
not yet updated correctly to represent the keymaps currently in effect,
I think it also was with some overriding map and had been fixed by Eli.

Anyway, this is more likely to be an Emacs thing, and given that the bug
is not that dramatic and it doesn't show up in newer Emacsen, it's
probably not worth investing too much time.

**Comment by thierryvolpiatto** [comment] 2015-06-25 14:26
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Hmm, that's the global binding which is running.
>
> It could be that for some reason, Emacs first doesn't get idle after
> starting helm-find-files, so the timer in `helm--maybe-update-keymap'
> doesn't fire.

Maybe, but it seems it is not only the problem, the keymap is not
updated when moving from one source to another, I guess
post-command-hook and/or overriding maps is not working properly here, 
maybe it is the reason why at this time I was using helm hooks to update
keymaps.

BTW I can reproduce the problem after a reinstall of emacs-24.3.1.

> OTOH it could be a problem with keymap installation in older Emacs
> version. I once too had a problem where user visible key bindings were
> not yet updated correctly to represent the keymaps currently in effect,
> I think it also was with some overriding map and had been fixed by Eli.

Yeah, maybe this one.

> Anyway, this is more likely to be an Emacs thing, and given that the bug
> is not that dramatic and it doesn't show up in newer Emacsen, it's
> probably not worth investing too much time.

Probably at the end of the year we will have another release of emacs,
maybe soonner, don't know, at this time we will have 3 new versions
above 24.3.1 and I will drop the support for this, so yes starting from
now emacs-24.3 users (few people now I guess) will have to live with
these small bugs.

To fix this I would have to reenable the old mechanism of updating
keymaps (that have other inconvenients and bugs) and that would be a
regression.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-06-25 14:50
Thierry Volpiatto <notifications@github.com> writes:

> To fix this I would have to reenable the old mechanism of updating
> keymaps (that have other inconvenients and bugs) and that would be a
> regression.

Indeed.

**Comment by thierryvolpiatto** [comment] 2015-06-25 18:34
I leave this open for anyone that encounter the same problem with emacs-24.3.

**Comment by alpha22jp** [comment] 2015-06-26 23:36
>  you could test this by evaluating
> ...
> and watch *Messages* while performing the test.  When does the first
"!!!" appear in *Messages*?

I tested it. emacs-24.3 output the first "!!!" when I pressed the first 'C-l' (which didn't work), while emacs-24.5 did at the moment I invoked 'M-x helm-find-files'. Is this an expected result?

**Comment by thierryvolpiatto** [comment] 2015-06-27 07:25
alpha22jp <notifications@github.com> writes:

>     you could test this by evaluating
>     ...
>     and watch Messages while performing the test. When does the first
>     "!!!" appear in Messages?
>    
> I tested it. emacs-24.3 output the first "!!!" when I pressed the
> first 'C-l' (which didn't work), while emacs-24.5 did at the moment I
> invoked 'M-x helm-find-files'.  Is this an expected result?

Well the expected result is what you have in emacs-24.5.
No message "!!!" until you press a key means the keymap haven't been
initialized.

Note that this bug appear also when changing sources in e.g
helm-multi-files.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-06-27 12:18
So my assumption was correct and Emacs doesn't get idle after starting helm-find-files, so the timer that sets the keymap doesn't fire.  Dunno why, that could be anything.

@alpha22jp If you think it's worth your time, on Linux you can send Emacs a SIGUSR2 with the kill command.  That will force Emacs instantly into a debugger.  Do this directly after entering helm-find-files, before giving any input.  Try to find out what Emacs is doing.

But I think simply dropping that Emacs version if you can is the better choice...

**Comment by thierryvolpiatto** [comment] 2015-06-28 07:46
Should work now both in emacs-24.3 and >24.3 versions.

**Closed** 2015-06-28 20:24 UTC
Labels: emacsbug

**Comment by alpha22jp** [comment] 2015-06-28 23:24
Now my emacs-24.3 is working fine, thanks :smiley: 
But it would be better to migrate to emacs-24.5 as you say.
