### ISSUE TITLE
Why so often freeze Emacs when try to switch to "helm-mini" buffer?

### ISSUE THREAD

**Issue by lmdic** [emacs-helm/helm#2089] opened 2018-09-03 09:08 UTC
Windows 10 (64 bit), Emacs 26.1, helm-3.0

Very often when I want to show buffer list. To do this I use  (`C-x b`). But "`helm-mini`* buffer sometimes  open very long time (30 seconds). As result the Emacs is "freeze". 
As result I need to kill Emacs process from Task Manager.
Why this happened?

**Comment by alphapapa** [comment] 2018-09-03 09:50
Please follow the bug-reporting instructions in the issue template.  As it is, it's virtually impossible to help you or diagnose this problem.

**Comment by lmdic** [comment] 2018-09-03 10:40
Where I can find bug-reporting instructions? I never used it before.
Thanks.

**Comment by alphapapa** [comment] 2018-09-03 10:43
It should have appeared automatically when you first filed this issue.  Anyway, you can also see it here: https://github.com/emacs-helm/helm/blob/master/.github/issue_template.md

**Comment by ReneFroger** [comment] 2018-09-05 18:49
Perhaps you could start again with an empty Emacs configuration file, with only Helm package included. Give us also a link to your Emacs dot-file, so we could reproduce with an **empty emacs configuration file with Helm only** in re-submitted issue. 

Perhaps this could be considered as closed, I cannot reproduce it here on Windows.

**Comment by lmdic** [comment] 2018-09-07 06:59
In my `init.el` I has about 15 packges. I create simple test. I disable ONLY **helm** package in my `init.el`. 
And the problem **is gone**. No more wait (sometimes 30 seconds) to open list of buffers.  So I guess that the problem is in **helm** package.

**Comment by lmdic** [comment] 2018-09-11 17:13
You was right. From scratch I install Emacs 26.1. for Windows 26.1. Also I install ONLY package **helm 3.0** from` Melpa-Stable`.  And the problem **is gone**. No more wait while open buffer of list of buffers (`helm-mini`). I test this about week. All work nice. 
So, as I said before I has about 14 packages. 
So I will apply packages **one by one** to try to reproduce the situation when buffer `helm-mini` open very long time (> 10 seconds).

Here algorithm of testing:

1. **helm** + **package#1** - test one week.
2. If OK then apply next package: **helm** + **package#1**+ **package#2** - test one week.
3. And so on

Is it a good approach?


Here my `init.el`

```
(setq custom-file "~/.emacs.d/custom/emacs-init-custom.el")
(load custom-file)

(add-to-list 'load-path "~/.emacs.d/elpa")
;; UTF-8 as default encoding
(set-language-environment "UTF-8")
;; Use CUA keys (Cut/Past with C-x/C-c/C-v)
(cua-mode t)
;; Enable upcase whole selection text
(put 'upcase-region 'disabled nil)
;; Start maximised (cross-platf)
(add-hook 'window-setup-hook 'toggle-frame-maximized t)

(require 'helm)
(require 'helm-config)
(helm-mode 1)

(load "~/.emacs.d/custom/emacs-init-keybindings.el")
```

Here my `emacs-init-custom.el`

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(column-number-mode t)
 '(cua-keep-region-after-copy t)
 '(global-hl-line-mode t)
 '(make-backup-files nil)
 '(package-archives
   (quote
    (("gnu" . "https://elpa.gnu.org/packages/")
     ("melpa-stable" . "https://stable.melpa.org/packages/"))))
 '(package-selected-packages (quote (helm)))
 '(password-cache-expiry nil)
 '(split-width-threshold nil))
 
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

```

Here my `emacs-keyboard-macros.el`

```
;; Helm mode
(global-set-key (kbd "M-x") 'helm-M-x)
(global-set-key (kbd "C-x C-f") 'helm-find-files)
;; find files only project (in git repo)
;;(global-set-key (kbd "C-<f6>") 'helm-ls-git-ls)
;; find text only in project's files (in git repo)
(global-set-key (kbd "C-M-<f6>") 'helm-grep-do-git-grep)

;;(global-set-key (kbd "C-x C-d") 'helm-browse-project)
;;(global-set-key (kbd "C-<f12>") 'helm-imenu)

;; 3 sections: Buffers/Recentf/Create buffer
(global-set-key (kbd "C-x b") 'helm-mini)

;; Shell commands history
;;(define-key shell-mode-map (kbd "C-c C-l") 'helm-comint-input-ring)

;; Minibuffer commands history
(define-key minibuffer-local-map (kbd "C-c C-l") 'helm-minibuffer-history)

;; complete path by tab in minibuffer
(define-key helm-map (kbd "<tab>") 'helm-execute-persistent-action)

(global-set-key (kbd "<f9>") 'toggle-truncate-lines)

;; Split windows
(global-unset-key (kbd "C-x 3")) ;; split-window-right
(global-set-key (kbd "M-4") 'split-window-vertically)

(global-unset-key (kbd "C-x 2")) ;; split-window-below
(global-set-key (kbd "M-$") 'split-window-horizontally)

;; Delete windows
(global-unset-key (kbd "C-x 1")) ;; delete-other-window
(global-set-key (kbd "M-3") 'delete-other-windows)

(global-unset-key (kbd "C-x 0")) ;; delete-window
(global-set-key (kbd "M-2") 'delete-window)

;; Standard Fixed Shortcuts
;;(global-unset-key (kbd "C-x C-f")) ;; Remove Emacs Method
;;(global-set-key (kbd "C-o") 'find-file)

;; Override 'M-left' and 'M-right'
(windmove-default-keybindings 'meta)

(global-unset-key (kbd "C-x h")) ;; Mark whole buffer
(global-set-key (kbd "C-a") 'mark-whole-buffer)

;; kill buffer without prompt
(global-set-key (kbd "C-w") 'kill-this-buffer)

(global-set-key (kbd "C-S-w") 'kill-buffer-and-window)

;; Set mark after end of following balanced expression
(global-set-key (kbd "C-=") 'mark-sexp)

;; Clean screen in shell mode
;; Same as Windows console command "cls"
(global-set-key (kbd "<f12>") 
		(lambda ()
		  (interactive)
		  (erase-buffer)
		  (process-send-string nil "\n")))


;; custom function in init.el
(global-set-key (kbd "C-<f12>") 'clear-buffer-permenantly)

;; run shell in current folder
;; To start another shell use univeral prefix C-u
(global-set-key (kbd "<f8>") 'shell)
```

**Comment by ReneFroger** [comment] 2018-09-11 18:11
Why one week? Comment out half of your configuration. You can use M-x comment-region to comment out the region of selected text, or with Evil commenter (see emacs.zeef.com). (You can uncomment the region using C-u with the same command. (For convenience, you can bind comment-region to a key.)

Start Emacs. Did you see the same problem? 
If yes, then the problem is not caused by the part you commented out. 
If no, then it is. 

For the problematic part: Comment out the other part and half of the problematic part. Then see if the problem arises. Repeat #2 and #3, over and over. It doesn't take long: 1/2, 3/4, 7/8, 15/16, 31/32, 63/64, 127/128, 255/256, 511/512, 1023/1024,...

It doesn't matter how big your init file is or how much other code it loads (if the problem is in other code then repeat the same process on that file, etc.).

Please stop posting your whole configuration, you need to solve the problem you might have caused since it's not related to Helm.

Can someone close this issue?

**Comment by lmdic** [comment] 2018-09-12 07:10
One week because  I noticed that this problem (with `helm-mini`) may appear not  immediately, but after 3 days of using **helm**.

**Comment by thierryvolpiatto** [comment] 2018-09-12 13:27
Please describe exactly what you are doing to "switch to helm-mini buffer".

**Comment by lmdic** [comment] 2018-09-12 13:32
I execute `C-x b` to open `helm-mini`

**Comment by thierryvolpiatto** [comment] 2018-09-22 10:12
There is a misunderstanding on how to use helm-mini.
Apparently you used one time M-x helm-mini and then instead of using again M-x helm-mini when you want to list your buffers, you do C-x b (switch-to-buffer) to open the helm buffer "*helm mini*"!
If you want help here, you have to fill in the Issue template when submitting a new issue and explain clearly what you are doing step by step, this to avoid loosing time trying to understand what you are doing.  Feel free to open a new issue if needed, I am closing this one now.

**Closed by thierryvolpiatto** 2018-09-22 10:12 UTC

**Comment by lmdic** [comment] 2018-09-22 12:34
I use `C-x b` because in my init.el I set:

`(global-set-key (kbd "C-x b") 'helm-mini)`

**Comment by yantar92** [comment] 2018-10-01 15:05
As I remember, dired+ introduces a custom mode-line format with a large
number of evals `diredp-nb-marked-in-mode-name`.
helm-mini evaluates mode-lines for every single dired buffer, which
makes it incredibly slow in some cases (the mode line evaluates
something like `(while (and (<= (point) e-pt) (< (point) (point-max)))
...` in every mode-line, which is obviously slow for large dired
buffers).
