### ISSUE TITLE
commit 7a7426b (Fix disabling mouse events while in helm) is problematic

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#834] opened 2015-01-21 01:30 UTC
Hello,

there are several problems, especially due to the fact that we use global map now to disable mouse.

- we don't undefine bindings, we now remap commands.  What if someone has bound some command to a mouse event that has other bindings as well? Even worse - what if someone already has remapped a command bound to a mouse event?  Then (helm--remap-mouse-events nil) will remove the user's remapping.

- we do this in  global map. Not a good idea IMHO. For example when using helm-do-grep, before that change one could scroll the popped up search buffers with the mouse.  That's not possible anymore.

- Disabling mouse in global map is especially bad for users of helm-prevent-escaping-from-minibuffer nil.  In this case, changing the behavior of Emacs globally is bad.

**Comment by michael-heerdegen** [comment] 2015-01-21 01:39
BTW, no harm meant. I appreciate how much work you do for helm, I couldn't do that much work on it.  And I find the vast majority of your fixes and ideas very clever...not that you get the impression I have only critiques...

**Comment by thierryvolpiatto** [comment] 2015-01-21 05:13
Michael Heerdegen <notifications@github.com> writes:

> BTW, no harm meant. I appreciate how much work you do for helm, I
> couldn't do that much work on it. And I find the vast majority of your
> fixes and ideas very clever...

Thanks.

> not that you get the impression I have only critiques...

No, it's ok, most of your critiques are helping a lot (even if sometimes
they give me a lot of work :-))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-01-21 08:15
Michael Heerdegen <notifications@github.com> writes:

> Hello,
>
> there are several problems, especially due to the fact that we use global map now to disable mouse.
>
>   * we don't undefine bindings, we now remap commands. What if someone
>     has bound some command to a mouse event that has other bindings as
>     well? Even worse - what if someone already has remapped a command
>     bound to a mouse event? Then (helm--remap-mouse-events nil) will
>     remove the user's remapping.

This should be fixed.
    
>   * we do this in global map. Not a good idea IMHO. For example when
>     using helm-do-grep, before that change one could scroll the popped
>     up search buffers with the mouse. That's not possible anymore.

The problem is not global-map here, was just I have added all
mouse-bindings even the one for scrolling, which is not necessary.
Scrolling is working now unless disabled with `mouse-wheel-mode'.
    
>   * Disabling mouse in global map is especially bad for users of
>     helm-prevent-escaping-from-minibuffer nil. In this case, changing
>     the behavior of Emacs globally is bad.

Same, not a problem with global-map as long as we reset the old
bindings.
Mouse bindings should now work in helm when
helm-prevent-escaping-from-minibuffer is nil.

Thanks to catch this, as I don't use mouse in emacs, I often forget it
is important for others. 

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-01-21 09:27
Thierry Volpiatto <notifications@github.com> writes:

> Thanks to catch this, as I don't use mouse in emacs, I often forget it
> is important for others.

Ok, I'm happy with the fixed behavior.

But now that we use a minor mode - why don't we just give that mode a
keymap with bindings of the mouse keys to undefined (I mean the command
named "undefined")?  The minor mode map would shadow the global
bindings, and the mode definition would become a one-liner, you would
only have to specify this map.

BTW, where did all the trailing whitespace come from?  I hope it was not
my fault (at least one occurrence seems to have been my fault though).

**Comment by thierryvolpiatto** [comment] 2015-01-21 10:42
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> Thanks to catch this, as I don't use mouse in emacs, I often forget it
>> is important for others.
>
> Ok, I'm happy with the fixed behavior.
>
> But now that we use a minor mode - why don't we just give that mode a
> keymap with bindings of the mouse keys to undefined

Good idea, done, thanks.

> BTW, where did all the trailing whitespace come from? I hope it was not
> my fault (at least one occurrence seems to have been my fault though).

One was in your macro indeed, the others I don't know, maybe from last PR's.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Closed** 2015-01-21 19:45 UTC
