### ISSUE TITLE
Killing helm buffers leaves helm in an unusable state

### ISSUE THREAD

**Issue by ahyatt** [emacs-helm/helm#1580] opened 2016-08-08 19:15 UTC
This is something hard to reproduce, so apologies if it has already been fixed.  Sometimes I end up killing  a helm buffer by accident, and this leaves me with many errors and unable to start a new helm session.  Since I bind M-x to helm-M-x, I usually just have to kill emacs at this point.

The errors are mostly like:
`Error running timer: (wrong-type-argument window-live-p nil)`

I can't actually reproduce this when trying, though.  I can kill a helm buffer and I do get a lot of those errors, which make any work impossible for about 10 seconds, but then I find I can start up a new helm buffer without issues.  In the past, though, I've been unable to get past the errors.

**Comment by thierryvolpiatto** [comment] 2016-08-09 05:34
Andrew Hyatt <notifications@github.com> writes:

> This is something hard to reproduce, so apologies if it has already
> been fixed. Sometimes I end up killing a helm buffer by accident, and
> this leaves me with many errors and unable to start a new helm
> session. Since I bind M-x to helm-M-x, I usually just have to kill
> emacs at this point.
>
> The errors are mostly like: Error running timer: (wrong-type-argument
> window-live-p nil)
>
> I can't actually reproduce this when trying, though. I can kill a helm
> buffer and I do get a lot of those errors, which make any work
> impossible for about 10 seconds, but then I find I can start up a new
> helm buffer without issues. In the past, though, I've been unable to
> get past the errors.

How are you killing your buffers ?

Can you provide a recipe so that I can reproduce ?

Can you reproduce from emacs-helm.sh ?

-- 
Thierry

**Comment by ahyatt** [comment] 2016-08-10 18:26
I'm killing buffers via kill-buffer, usually because the helm buffer was
misbehaving in some way and sticking around.  It's a bit difficult to give
specific reproduction steps because this happens infrequently.  I haven't
been able to reproduce at all with emacs-helm.sh, but I'll keep trying.

I'm wondering if there is something in the design of helm that assumes that
a helm buffer hasn't been killed.  Should helm be more robust to that, or
should whatever issue that is causing me to have to kill the helm buffers
be fixed?

**Comment by thierryvolpiatto** [comment] 2016-08-11 04:50
Andrew Hyatt <notifications@github.com> writes:

> I'm killing buffers via kill-buffer, usually because the helm buffer was
> misbehaving in some way and sticking around. It's a bit difficult to give
> specific reproduction steps because this happens infrequently. I haven't
> been able to reproduce at all with emacs-helm.sh, but I'll keep trying.

Ok let me know if you are able to reproduce, here I can't reproduce.

> I'm wondering if there is something in the design of helm that assumes that
> a helm buffer hasn't been killed.

No.

> Should helm be more robust to that, or should whatever issue that is
> causing me to have to kill the helm buffers be fixed?

I have no ideas to what need to be fixed for now.

-- 
Thierry

**Comment by ahyatt** [comment] 2016-08-12 05:02
Good news, I can reproduce it now, but not with a plain environment, only currently with spacemacs, and using helm-descbinds.  So I think the interesting thing here is the stacktrace which may provide you some clues.  If you think this is some spacemacs issue, I can instead report this issue there.

Reproducing w/ spacemacs:
1. C-h b (to list keybindings in helm)
2. C-x o (switch to minibuffer)
3. Type text - you can just start typing now in the middle of the helm buffer
4.  If that works, then just kill the buffer C-x k.

I get a few errors, and then, since I set backtrace on error, I get the following backtrace (I am only pasting some of it in, since it is very long):

`Debugger entered--Lisp error: (wrong-type-argument window-live-p nil)
  #<subr select-window>(nil norecord)
  ad-Advice-select-window(#<subr select-window> nil norecord)
  apply(ad-Advice-select-window #<subr select-window> (nil norecord))
  select-window(nil norecord)
  helm-update()
  helm-check-new-input("")
  #[0 "\301\302\303 \206\n\304 !r\305\306\307\310\311\312!\313\"\314\315%DC\216\316@\317\"\210\320\321 !*\262)\207" [inhibit-quit nil internal--before-with-selected-window active-minibuffer-window minibuffer-window funcall make-byte-code 0 "\301\300!\207" vconcat vector [internal--after-with-selected-window] 2 "\n\n(fn)" select-window norecord helm-check-new-input minibuffer-contents] 8 "\n\n(fn)"]()
  funcall(#[0 "\301\302\303 \206\n\304 !r\305\306\307\310\311\312!\313\"\314\315%DC\216\316@\317\"\210\320\321 !*\262)\207" [inhibit-quit nil internal--before-with-selected-window active-minibuffer-window minibuffer-window funcall make-byte-code 0 "\301\300!\207" vconcat vector [internal--after-with-selected-window] 2 "\n\n(fn)" select-window norecord helm-check-new-input minibuffer-contents] 8 "\n\n(fn)"])
  helm-check-minibuffer-input()
  #[0 "\206	?\205%\302 r\303\304\305\306\307\310!\311\"\312\313%DC\216\314 \210\315 *\262\207" [helm-in-persistent-action helm-suspend-update-flag internal--before-save-selected-window funcall make-byte-code 0 "\301\300!\207" vconcat vector [internal--after-save-selected-window] 2 "\n\n(fn)" helm-check-minibuffer-input helm-print-error-messages] 8 "\n\n(fn)"]()
  apply(#[0 "\206	?\205%\302 r\303\304\305\306\307\310!\311\"\312\313%DC\216\314 \210\315 *\262\207" [helm-in-persistent-action helm-suspend-update-flag internal--before-save-selected-window funcall make-byte-code 0 "\301\300!\207" vconcat vector [internal--after-save-selected-window] 2 "\n\n(fn)" helm-check-minibuffer-input helm-print-error-messages] 8 "\n\n(fn)"] nil)
  timer-event-handler([t 0 0 10000 repeat #[0 "\206	?\205%\302 r\303\304\305\306\307\310!\311\"\312\313%DC\216\314 \210\315 *\262\207" [helm-in-persistent-action helm-suspend-update-flag internal--before-save-selected-window funcall make-byte-code 0 "\301\300!\207" vconcat vector [internal--after-save-selected-window] 2 "\n\n(fn)" helm-check-minibuffer-input helm-print-error-messages] 8 "\n\n(fn)"] nil idle 0])
  read-from-minibuffer("pattern:" nil (keymap ...))
`

At this point I can't do anything - switch buffers (which says "No previous helm sessions available for resuming!", find-file or M-x ("No buffer named *helm descbinds"), and more.  But after a minute or so it starts working again.

**Comment by ahyatt** [comment] 2016-08-12 05:06
I should add that it doesn't always start working again.  I just tried it again and it stays in the broken state even after several minutes have gone by.

**Comment by thierryvolpiatto** [comment] 2016-08-12 06:03
Andrew Hyatt <notifications@github.com> writes:

> Good news, I can reproduce it now, but not with a plain environment,
> only currently with spacemacs, and using helm-descbinds. So I think
> the interesting thing here is the stacktrace which may provide you
> some clues. If you think this is some spacemacs issue, I can instead
> report this issue there.

As long as it is not reproductible from emacs-helm.sh and it happens
only with spacemacs, yes I guess it is a spacemacs bug.  I see in your
backtrace `select-window` is advised somewhere, not by helm at least...
BTW when providing a BT, always load the source files (.el) instead of
the byte-compiled ones (.elc) to avoid bytecode in BT.

> Reproducing w/ spacemacs:
> 1. C-h b (to list keybindings in helm)
> 2. C-x o (switch to minibuffer)
> 3. Type text - you can just start typing now in the middle of the helm buffer
> 4. If that works, then just kill the buffer C-x k.

You are killing the helm-buffer while minibuffer is in use, well while
helm-session is alive, which is not recommended, however helm is
perfectly handling this even if `helm-prevent-escaping-from-minibuffer`
is nil, the session is stopped and you get a message 
"Aborting an helm session running in background".

NOTE: I am not following and supporting spacemacs modifications apported
to helm.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-08-12 20:05
Closing as not reproductible.

**Closed by thierryvolpiatto** 2016-08-12 20:05 UTC
