### ISSUE TITLE
Slow Helm window and frame popup on Emacs 26.1

### ISSUE THREAD

**Issue by Zaeph** [emacs-helm/helm#2049] opened 2018-05-30 07:16 UTC
Hello,

Following `emacs`’s 26.1 release, I’ve been experiencing the delays described in #1976.

There’s a significant hang running the following code (mentioned above):
```elisp
(with-helm-in-frame
  (helm :sources (helm-build-sync-source "test"
                   :candidates '("foo" "bar" "baz"))
        :buffer "*helm test*"))
```

It happens both when calling `helm` in windows (e.g. `helm-mini`) or frames (e.g. code above).

Could someone look into it to see if they can reproduce it?

(I’m new to GitHub, so please excuse me if it’s not proper to create a new issue rather than commenting on the previous one. I did both to ensure visibility.)

**Comment by thierryvolpiatto** [comment] 2018-05-30 07:46
Zaeph <notifications@github.com> writes:

> Hello,
>
> Following emacs’s 26.1 release, I’ve been experiencing the delays described in #1976.
>
> There’s a significant hang running the following code (mentioned above):
>
> (with-helm-in-frame
>   (helm :sources (helm-build-sync-source "test"
>                    :candidates '("foo" "bar" "baz"))
>         :buffer "*helm test*"))
>
> It happens both when calling helm in windows (e.g. helm-mini) or frames (e.g. code above).
>
> Could someone look into it to see if they can reproduce it?

Yes I can reproduce on emacs-26, it is not reproductible on emacs-27.
The change made on emacs-27 have not been backported to emacs-26. As a
workaround as specified in #1976 setting x-wait-for-event-timeout to nil
    (setq x-wait-for-event-timeout nil)
Fixes the issue for emacs-26.

> (I’m new to GitHub, so please excuse me if it’s not proper to comment on a closed issue.)

You can, no need to open a new issue ;-)

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*


-- 
Thierry

**Comment by Zaeph** [comment] 2018-05-30 07:54
Thank you for the quick reply. `(setq x-wait-for-event-timeout nil)` does indeed fix it!
Sorry if it was obvious that the changes would be present in 26.1. I must say I don't really know how `emacs` versions work, and I thought that it warranted another issue.
At any rate, thank you!

**Comment by thierryvolpiatto** [comment] 2018-05-30 08:00
Zaeph <notifications@github.com> writes:


> I must say I don't really know how emacs versions work,

You can add something like this in your init file:

    ;; Fix slow helm frame popup in emacs-26 helm issue #1976
    (when (= emacs-major-version 26)
      (setq x-wait-for-event-timeout nil))

-- 
Thierry

**Comment by Zaeph** [comment] 2018-05-30 08:03
> You can add something like this in your init file:
```elisp
;; Fix slow helm frame popup in emacs-26 helm issue #1976
(when (= emacs-major-version 26)
  (setq x-wait-for-event-timeout nil))
```
Thank you for the elegant solution. :)

**Comment by thierryvolpiatto** [comment] 2018-06-05 15:31
Duplicate of #1976 Closing now.

**Closed by thierryvolpiatto** 2018-06-05 15:31 UTC
