### ISSUE TITLE
emacs 24.5 , M-x ---> Args out of range: #<buffer *helm M-x*>, 0, 1

### ISSUE THREAD

**Issue by alexei28** [emacs-helm/helm#1644] opened 2016-11-19 14:54 UTC
## Expected behavior
show Emacs command in buffer *helm M-x*

## Steps to reproduce (recipe)
1. Start emacs 
2. Press M-x
3. In minibuffer show: **Args out of range: #<buffer *helm M-x*>, 0, 1**
4. Again press M-x
5. Success show Emacs command in buffer *helm M-x*

## Describe versions of helm, emacs, operating system etc.
Windows 7 (64 bit)
Emacs 24.5
helm-20161116.1211
helm-core-20161113.908

in init.el
`(require 'helm)
(require 'helm-config)
(helm-mode 1)
(global-set-key (kbd "M-x") 'helm-M-x)`

**Comment by alexei28** [comment] 2016-11-19 14:56
my comment

**Comment by thierryvolpiatto** [comment] 2016-11-19 19:54
alexei28 <notifications@github.com> writes:

> ## Expected behavior
> show Emacs command in buffer *helm M-x*
>
> ## Steps to reproduce (recipe)
> 1. Start emacs 
> 2. Press M-x
> 3. In minibuffer show: **Args out of range: #<buffer *helm M-x*>, 0, 1**
> 4. Again press M-x
> 5. Success show Emacs command in buffer *helm M-x*

Can't reproduce from Windows7.
Be sure you start in a clean environment (only helm).

-- 
Thierry

**Comment by alexei28** [comment] 2016-11-20 11:05
Yes, you are right. This is because I install package "еrgoemacs-mode"

**(add-to-list 'load-path "~/.emacs.d/elpa/ergoemacs-mode-20161025.1222/")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)**


If remove this package, then all is OK.

**Comment by alexei28** [comment] 2016-11-20 11:06
Yes, you are right. This is because I install package "еrgoemacs-mode"

**(add-to-list 'load-path "~/.emacs.d/elpa/ergoemacs-mode-20161025.1222/")
(require 'ergoemacs-mode)
(setq ergoemacs-theme nil) ;; Uses Standard Ergoemacs keyboard theme
(setq ergoemacs-keyboard-layout "us") ;; Assumes QWERTY keyboard layout
(ergoemacs-mode 1)**


If remove this package, then all is OK.

**Comment by thierryvolpiatto** [comment] 2016-11-20 13:44
Ok, so I am closing.

**Closed by thierryvolpiatto** 2016-11-20 13:44 UTC
