### ISSUE TITLE
gnus messing up the helm-M-x completion candidates

### ISSUE THREAD

**Issue by dinojr** [emacs-helm/helm#2249] opened 2019-12-11 11:13 UTC
From emacs-helm.sh. After (require 'gnus), M-x doesn't offer "gnus" as a completion when typing "gnus", only gnus-bug, gnus-mode.... Even when typing "gnus " with a space. Changing helm-completing-style and gnus-completing-styles to "helm" didn't fix it.

Edit: (require 'eww) results in the same behaviour.

**Comment by thierryvolpiatto** [comment] 2019-12-11 14:41
Can't reproduce from emacs-helm.sh:

![Capture d’écran_2019-12-11_15-38-52](https://user-images.githubusercontent.com/1533939/70630837-8abcf700-1c2c-11ea-827b-82071ceebf6d.png)

**Comment by thierryvolpiatto** [comment] 2019-12-11 14:43
Please make a complete bug report with details following the issue template if you want me to help you or fix your problem.

**Comment by dinojr** [comment] 2019-12-11 15:33
## Expected behavior
helm-M-x should offer "gnus" to complete when typing "gnus" or "gnus "  

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
It only offers gnus-bug, gnus-mode and other commands with a dash in the name

## Steps to reproduce (recipe)
eval (require 'gnus)
run M-x gnus and look for the completion candidates

## Backtraces if any (`M-x toggle-debug-on-error`)
no errors

## Describe versions of Helm, Emacs, operating system, etc.
helm-20191210.1804 from melpa
GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) of 2019-12-10
Gnus v5.13 from the same emacs-snapshot package in Ubuntu.
## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):
yes
## Are you using Spacemacs? (yes/no):
no

**Comment by thierryvolpiatto** [comment] 2019-12-11 18:03
Ok, thanks for the report.  Seems it is only that `helm-candidate-number-limit` is too low.
I will see what I can do, for now just increase it globally or better increase it just for helm-M-x:

```elisp
(defmethod helm-setup-user-source ((source helm-M-x-class))
  (setf (slot-value source 'candidate-number-limit) 1000))
```

**Comment by thierryvolpiatto** [comment] 2019-12-11 20:35
Ok, seems fixed in dev branch, I will merge tomorrow.
Thanks and sorry for inconvenience.

**Comment by thierryvolpiatto** [comment] 2019-12-12 08:07
Ok, merged in master.

**Closed by thierryvolpiatto** 2019-12-12 08:07 UTC

**Comment by dinojr** [comment] 2019-12-12 21:03
Thanks for the fix.
