### ISSUE TITLE
helm-eshell-complete not working as documented

### ISSUE THREAD

**Issue by rileyrg** [emacs-helm/helm#2263] opened 2020-01-06 08:45 UTC
The documentation at https://github.com/emacs-helm/helm/wiki/Eshell gives this config example:-
```
     (add-hook 'eshell-mode-hook
          (lambda ()
            (define-key eshell-mode-map
              (kbd "M-p")
              'helm-eshell-history)))

```

It doesn't work with emacs 27.0.50 and Melpa helm. It kind of works changing to eshell-hist-mode-map but I say "kind of" because of constant focus issues. Frequently the popup frame which hosts the completion UI isn't focused and I need to reach for the mouse to focus it. I ha a quick code grep but missed any option for the eshell history to use the usual helm minibuffer or completion ui such as things like helm-find-file uses. Would be great if there was such an option.

My config which does work but which has focus issues with the completion popup:

```
   (use-package eshell
     :config 
     (use-package eshell-git-prompt
       :config
       ;; the powerline prompt is best but I've no idea how to shorten it to the last directory.
       (eshell-git-prompt-use-theme 'powerline)
       (define-advice eshell-git-prompt-powerline-dir (:override () short)
         "Show only last directory."
         (file-name-nondirectory (directory-file-name default-directory))))
     (use-package em-hist
       :bind (:map eshell-hist-mode-map
                   ("<down>" . 'next-line)
                   ("<up>" . 'previous-line)
                   ("M-p" . 'helm-eshell-history)))
     ;; (defun runEShellAndJumpToEnd()
     ;;   (interactive)
     ;;   (eshell)
     ;;   (goto-char (point-max)))
     ;; :bind
     ;; ("<f12>" . runEShellAndJumpToEnd)
     )

```

POST EDIT: The helm-eshell-history popup is much more reliable with helm-autoresize-mode off.

**Comment by thierryvolpiatto** [comment] 2020-01-06 13:25
Richard Riley <notifications@github.com> writes:

> The documentation at https://github.com/emacs-helm/helm/wiki/Eshell gives this config example:-
>
>      (add-hook 'eshell-mode-hook
>           (lambda ()
>             (define-key eshell-mode-map
>               (kbd "M-p")
>               'helm-eshell-history)))
>
> It doesn't work with emacs 27.0.50 and Melpa helm.

In emacs-27+ both completion and history have changed, making most part
of helm-eshell.el obsolete, history still work though, I just tried this:

    (add-hook 'eshell-mode-hook
              (lambda ()
                (define-key eshell-hist-mode-map
                  [remap eshell-previous-matching-input-from-input]
                  'helm-eshell-history)))

And it works just fine as expected.

> It kind of works changing to eshell-hist-mode-map but I say "kind of"
> because of constant focus issues. Frequently the popup frame which
> hosts the completion UI isn't focused and I need to reach for the
> mouse to focus it.

Can't reproduce this, please try from a minimal config.

> I ha a quick code grep but missed any option for the eshell history to
> use the usual helm minibuffer or completion ui such as things like
> helm-find-file uses. Would be great if there was such an option.

helm-show-completion-display-function

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by rileyrg** [comment] 2020-01-06 13:38
> (add-hook 'eshell-mode-hook
>               (lambda ()
>                 (define-key eshell-hist-mode-map
>                   [remap eshell-previous-matching-input-from-input]
>                   'helm-eshell-history)))
> 

Yup, the same, give or take, as my use-package solution. eshell-hist-mode-map.

>  '(helm-show-completion-display-function 'helm-show-completion-default-display-function)

did indeed solve focus issues. thanks.

**Comment by thierryvolpiatto** [comment] 2020-01-06 14:15
Richard Riley <notifications@github.com> writes:

>     (add-hook 'eshell-mode-hook
>     (lambda ()
>     (define-key eshell-hist-mode-map
>     [remap eshell-previous-matching-input-from-input]
>     'helm-eshell-history)))
>    
> Yup, the same, give or take, as my use-package
> solution. eshell-hist-mode-map.

Not really the same.


>     '(helm-show-completion-display-function 'helm-show-completion-default-display-function)
>    
> did indeed solve focus issues.

Seems you are not using a minimal config to reproduce your focus issues,
I tried hard to reproduce but couldn't, I have no problems here.

So closing now, feel free to reopen, not forgetting to reproduce your
bug from a minimal setting emacs -Q or better emacs-helm.sh, and also
the issue template...

Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Closed** 2020-01-06 14:16 UTC

**Comment by rileyrg** [comment] 2020-01-06 14:24
Sure thing. I  will try to get back to it. And thank you.
