### ISSUE TITLE
Helm is modifying window point when splitting windows

### ISSUE THREAD

**Issue by jstaursky** [emacs-helm/helm#2348] opened 2020-07-27 16:09 UTC
**Is your feature request related to a problem? Please describe.**
helm shifts window modelines + window views with `helm-M-x`--I find this very jarring + annoying.

**Describe the solution you'd like**
put all completion inside the modeline, separate each candidate by |. Make the current selection bold and on the far left or something. candidates that do not fit are brought in from the right side while browsing for a selection. 

**Additional context**
Hopefully this is the right place to ask, I don't know whether helm is 
synonymous with popup window, but figured I'd ask in case in case its not.

**Comment by thierryvolpiatto** [comment] 2020-07-27 18:17
jstaursky <notifications@github.com> writes:

> Is your feature request related to a problem? Please describe.
> helm shifts window modelines + window views with helm-M-x--I find this very jarring + annoying.

Sorry don't understand this.

> Describe the solution you'd like
> put all completion inside the modeline, separate each candidate by |. Make the current selection bold and on the far left or something. candidates that do not fit are
> brought in from the right side while browsing for a selection.

This is not possible and anyway would be terrible, but maybe I
misunderstand what you want...

> Additional context
> Hopefully this is the right place to ask, I don't know whether helm is
> synonymous with popup window, but figured I'd ask in case in case its not.

No it is not, perhaps you are asking for something that belong to
another package ? Dunno.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jstaursky** [comment] 2020-07-27 23:45
> Sorry don't understand this.

Here is a short annotated clip. I have added arrows where the modeline/divider of another window shifts. I suspect this is a built in limitation of emacs (and hence my proposed solution)
![output](https://user-images.githubusercontent.com/25406664/88601370-853ae280-d03e-11ea-984b-f69f02c354b9.gif)
 >This is not possible and anyway would be terrible, but maybe I
misunderstand what you want...

Really? the more I've thought about it, the more I like the idea. Maybe I will try and implement it when time allows. Basically I was thinking that the modeline would change to a sort of overlay cmd line when `M-x` is pressed with incremental completion candidates appearing to its right (along with an appropriate separator like `|`) until truncation at the windows end. Although the same thing at the minibuffer would be just as nice. just want to find a way to do away with the buffer-view shifting shown in the gif.

>No it is not, perhaps you are asking for something that belong to
another package ? Dunno.

Maybe. But do you have a workaround for the issue show in the gif?

**Comment by thierryvolpiatto** [comment] 2020-07-28 04:28
jstaursky <notifications@github.com> writes:

>     Sorry don't understand this.
>    
> Here is a short annotated clip. I have added arrows where the modeline/divider of another window shifts. I suspect this is a built in limitation of emacs (and hence my
> proposed solution)
> output  

Sorry but I still don't see what is happening in your clip.

>     This is not possible and anyway would be terrible, but maybe I
>     misunderstand what you want...
>    
> Really? the more I've thought about it, the more I like the
> idea. Maybe I will try and implement it when time allows. Basically I
> was thinking that the modeline would change to a sort of overlay cmd
> line when M-x is pressed with incremental completion candidates
> appearing to its right (along with an appropriate separator like |)
> until truncation at the windows end. Although the same thing at the
> minibuffer would be just as nice. just want to find a way to do away
> with the buffer-view shifting shown in the gif.

I think I misunderstand what do you want.

> Maybe. But do you have a workaround for the issue show in the gif?

Sorry but still don't know what the issue is, please try to reproduce
your issue from a minimal environment e.g. emacs-helm.sh, it seems your
emacs is heavily modified by external packages.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jstaursky** [comment] 2020-07-28 11:31
>Sorry but I still don't see what is happening in your clip.

Sorry its probably too dark. Here's another attempt
![output](https://user-images.githubusercontent.com/25406664/88657620-345bd600-d0a0-11ea-94e1-c7aafad28ff9.gif)

>I think I misunderstand what do you want.

I found a package that more or less does what I want ([smex](https://github.com/nonsequitur/smex))  (but I was thinking this inside a mode-line). However, resolving this particular issue would be ideal since helm is so ubiquitous.

>Sorry but still don't know what the issue is, please try to reproduce
your issue from a minimal environment e.g. emacs-helm.sh, it seems your
emacs is heavily modified by external packages.

Fixed. The gif shows a emacs config consisting of the following dot file.

```elisp
(require 'package)
(setq package-archives
      '(
        ("org" . "https://orgmode.org/elpa/")
        ("gnu" . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")
        ))
(package-initialize)

(unless (package-installed-p 'use-package)
  ;; only fetch the archives if you don't have use-package installed
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package);; set package.el repositories

(use-package auto-package-update
  :ensure t
  :config
  (setq auto-package-update-delete-old-versions t)
  (setq auto-package-update-hide-results t)
  (auto-package-update-maybe))

(use-package helm
  :config
  (setq helm-split-window-in-side-p nil)
  (add-to-list 'display-buffer-alist
               `(,(rx bos "*helm" (* not-newline) "*" eos)
                 (display-buffer-in-side-window)
                 (inhibit-same-window . t)
                 (window-height . 0.4)))
  :bind ("M-x" . helm-M-x))

(add-to-list 'default-frame-alist
             '(font . "Source Code Pro-14"))

```


Now I know this is with the added code
```elisp
  (add-to-list 'display-buffer-alist
               `(,(rx bos "*helm" (* not-newline) "*" eos)
                 (display-buffer-in-side-window)
                 (inhibit-same-window . t)
                 (window-height . 0.4)))
```
But I only added this to make the problem more apparent. Even with a config such as this
```elisp
(use-package helm
  :bind ("M-x" . helm-M-x))
```
 you can still see the issue of the buffer view shifting 
![output-New](https://user-images.githubusercontent.com/25406664/88659780-9a962800-d0a3-11ea-9e65-27cb6fded95f.gif)
 (hopefully you can see this)

**Comment by thierryvolpiatto** [comment] 2020-07-28 12:19
Can't reproduce from emacs-helm.sh
![Peek 28-07-2020 14-15](https://user-images.githubusercontent.com/1533939/88664244-152f6980-d0dd-11ea-8e7e-c6092f08ed93.gif)

Also what you are asking for i.e. an interface similar to smex or ido is not planned and will never be implemented in helm.

**Comment by jstaursky** [comment] 2020-07-28 13:25
The problem occurs when point is in range of where `helm-M-x` pops up. For example, if you move point right above mode line and hit M-x, the window above it will do the shift. I'm guessing this is caused by mark being shown in the previous window. Is there a way to move mark to the top of each window prior to helm-M-x? that way chances of overlap occurring will be minimized. Maybe theres a way to hide mark during helm-M-x? that might fix it.

**Comment by thierryvolpiatto** [comment] 2020-07-28 14:59
jstaursky <notifications@github.com> writes:

> The problem occurs when point is in range of where helm-M-x pops
> up. For example, if you move point right above mode line and hit M-x,
> the window above it will do the shift. I'm guessing this is caused by
> mark being shown in the previous window. Is there a way to move mark
> to the top of each window prior to helm-M-x? that way chances of
> overlap occurring will be minimized. Maybe theres a way to hide mark
> during helm-M-x? that might fix it.

I tried to tell you to use emacs-helm.sh, but you seem to ignore this.
Please use emacs-helm.sh to reproduce your bug.
Thanks.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jstaursky** [comment] 2020-07-28 18:49
Even simpler.
Type `M-> (end-of-buffer)`. then
`helm-M-x`. 
Observe page shift. 

I really don't understand why my running a shell script is required. It is two keybindings (one of which is apart of a default config `end-of-buffer`). 

If that really is not working for you, let me know and I'll go through your script later.

**Comment by thierryvolpiatto** [comment] 2020-07-29 04:35
jstaursky <notifications@github.com> writes:

> Even simpler.
> Type M-> (end-of-buffer). then
> helm-M-x.
> Observe page shift.

It is what done in the gif I sent.

> I really don't understand why my running a shell script is
> required. It is two keybindings (one of which is apart of a default
> config end-of-buffer).

Because package.el is loading all your packages and one of this package
is recentering of something like that the other window.

What is the problem of running a shell script?

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by jstaursky** [comment] 2020-07-29 12:22
>What is the problem of running a shell script?
I just don't want any symlinks to get clobbered or otherwise have environment variables changed. I'll go through the script tonight so we both can be happy.

In the meantime, I really think it would be faster if you just place your cursor immediately above the mode-line, type something and invoke helm-M-x to observer the behavior I am talking about.

**Comment by manuel-uberti** [comment] 2020-07-29 12:27
From `emacs-helm.sh`, this is before `M-x`:

![1](https://user-images.githubusercontent.com/8199224/88799907-84719000-d1a7-11ea-8de0-d7aae3255b51.png)

And this is after:

![Screenshot from 2020-07-29 14-26-09](https://user-images.githubusercontent.com/8199224/88799918-8a677100-d1a7-11ea-8017-d1f187acf72b.png)

If I understood what you mean, I don't see any overlapping. The cursor and the line it was before `M-x` are still visibile after `M-x`.

**Comment by manuel-uberti** [comment] 2020-07-29 12:36
Now I can reproduce it from `emacs-helm.sh`:

- `C-x 2`
- `C-x 3`
- `C-x o` (twice)
- `C-x C-f` and visit `helm.el`

![1](https://user-images.githubusercontent.com/8199224/88800638-c3ecac00-d1a8-11ea-90c4-438e5f550968.png)

- `M-x`

![2](https://user-images.githubusercontent.com/8199224/88800653-c8b16000-d1a8-11ea-8705-afa969d30e7a.png)

Is this the behaviour you are describing?

**Comment by thierryvolpiatto** [comment] 2020-07-29 13:50
Manuel Uberti <notifications@github.com> writes:

> Now I can reproduce it from emacs-helm.sh:
>
>   • C-x 2
>   • C-x 3
>   • C-x o (twice)
>   • C-x C-f and visit helm.el
>
> 1       
>
>   • M-x
>
> 2       

Thanks Manuel to look into this, but I still don't see where the problem
is.  I think I will close this in next days if I have no more clues on
this.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by manuel-uberti** [comment] 2020-07-29 13:57
> Thanks Manuel to look into this, but I still don't see where the problem is. I think I will close this in next days if I have no more clues on this.

I think the problem is the the Helm buffer related to `M-x` is hiding the bottom window. I'm taking a guess though. :)

**Comment by thierryvolpiatto** [comment] 2020-07-29 18:43
Manuel Uberti <notifications@github.com> writes:

>     Thanks Manuel to look into this, but I still don't see where the problem is. I think I will close this in next days if I have no more clues on this.
>    
> I think the problem is the the Helm buffer related to M-x is hiding
> the bottom window. I'm taking a guess though. :)

Well, of course it is hiding the bottom window, perhaps it is for this
reason the OP asked to have completion in ... mode-line!!!
Perhaps a solution for hime would be to use a new frame to display the
helm-buffer, I will send a screeshot in case.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or unsubscribe.*


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2020-07-29 18:47
Here helm-M-x displayed in a frame, does that help ?
![Capture d’écran_2020-07-29_20-44-49](https://user-images.githubusercontent.com/1533939/88840364-9f122c00-d1dc-11ea-88d3-d36e75684f1b.png)

**Comment by jstaursky** [comment] 2020-07-29 21:01
@manuel-uberti thanks for running the script on my behalf. Ironically despite the misunderstanding you still show the behavior I am speaking of. In your **_FIRST_** screenshot the text
```elisp
(require 'cl-lib)
(require 'async)
; ...
```
 is **_NOT VISIBLE_** 


however **_after_** invoking `helm-M-x` it can be seen in the **_SECOND_** screenshot the text **_IS VISIBLE_** because the **_shift_** in windows view.

I just want behavior where window view is unchanged during `helm-M-x`
my comments concerning point and mark were that it I believe this is the cause of the behavior.

**Comment by jstaursky** [comment] 2020-07-29 21:16
@thierryvolpiatto I could live with the pop up frame assuming it closes upon the command completing

**Comment by thierryvolpiatto** [comment] 2020-07-30 05:21
jstaursky <notifications@github.com> writes:

> @thierryvolpiatto I could live with the pop up frame assuming it
> closes upon the command completing

Of course it does.

    (add-to-list 'helm-commands-using-frame 'helm-M-x)

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2020-07-30 06:26
To resume the bugreport, IIUC the problem was the helm window is hiding the previous window where helm is displayed :)
Closing now.

**Closed by thierryvolpiatto** 2020-07-30 06:26 UTC
Labels: Spacemacs, not_reproducible

**Comment by jstaursky** [comment] 2020-07-30 13:09
BTW any chance you might know how to position it at the bottom of frame?
I was thinking something along the lines of
```elisp
    (advice-add 'helm-M-x :after
     (lambda (&rest args)
       (let ((x  (car (x-frame-edges nil 'inner-edges)))
             (y  helm-display-buffer-height))
         (set-frame-position nil x y))))
```
But this seems like it might be the wrong approach.

**Comment by jstaursky** [comment] 2020-08-21 04:25
For anyone in the future who sees this, the best solution is [here](https://github.com/tumashu/helm-posframe) with the following configuration
```elisp
(use-package helm-posframe
  :init (setq-default helm-posframe-width (frame-outer-width)
                      helm-posframe-min-width (frame-outer-width)
                      helm-posframe-height (/ (frame-outer-height) 5))
  :demand t
  :config
  (helm-posframe-enable))
```

**Comment by thierryvolpiatto** [comment] 2020-08-21 05:50
jstaursky <notifications@github.com> writes:

> For anyone in the future who sees this, the best solution is here with the following configuration
>
> (use-package helm-posframe
>   :init (setq-default helm-posframe-width (frame-outer-width)
>                       helm-posframe-min-width (frame-outer-width)
>                       helm-posframe-height (/ (frame-outer-height) 5))
>   :demand t
>   :config
>   (helm-posframe-enable))

Note that using helm-posframe, you may enter other bugs that are related
to helm-posframe and not helm, also helm-posframe is not compatible with
prior versions of emacs (child frames), so helm is NOT covering the
possible bugs related to posframe, be warned.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2020-08-21 06:11
Just tried helm-posframe, it completely break helm persistent actions.
Also the settings you are showing above disable completely the purpose of helm frames (helm-posframe or whatever frame settings), so please readers don't use this.

**Comment by jstaursky** [comment] 2020-08-28 04:13
> Also the settings you are showing above disable completely the purpose of helm frames (helm-posframe or whatever frame settings), so please readers don't use this.

? It directly solves the issue brought up.

Maybe this will illustrate the issue more clearly for you.

Here is ***with*** `helm-posframe`
![simplescreenrecorder-2020-08-27_23 33 56](https://user-images.githubusercontent.com/25406664/91518585-95084980-e8be-11ea-9d42-9ba44a93ae83.gif)

versus without ***without*** `helm-posframe`
![old](https://user-images.githubusercontent.com/25406664/91518913-3e4f3f80-e8bf-11ea-9b16-a95cf67c37c1.gif)

But you are right persistent actions do not work very well (without modification). But with regards to this particular issue, it implements a solution not otherwise available builtin.
