### ISSUE TITLE
Loading helm breaks M-x man on GNU/Linux

### ISSUE THREAD

**Issue by wdkrnls** [emacs-helm/helm#2345] opened 2020-07-20 04:10 UTC
## Expected behavior

Activating Helm doesn't break other Emacs functionality.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

After loading `helm-mode`, `M-x man` does not build and display a man page for
many commands (ssh for example). However, `helm-man-woman` works as expected.

## Steps to reproduce (recipe)

Evaluate the code:

    (require 'helm)
    (helm-mode 1)

Try to read ssh man page with `M-x man`.

## Backtraces if any (`M-x toggle-debug-on-error`)

No lisp error, but `*Messages*` buffer records: 

    Invoking man 0 ssh in the background
    Can’t find the 0 ssh manpage

## Describe versions of Helm, Emacs, operating system, etc.

Latest versions of helm and Emacs on the Guix System.

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

no

## Are you using Spacemacs? (yes/no):

no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.
If necessary you can specify emacs executable path on command line with "-P" option.

Thanks.

**Comment by thierryvolpiatto** [comment] 2020-07-20 04:22
wdkrnls <notifications@github.com> writes:

> Expected behavior
>
> Activating Helm doesn't break other Emacs functionality.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> After loading helm-mode, M-x man does not build and display a man page for
> many commands (ssh for example). However, helm-man-woman works as expected.

Not reproductible, I guess you are pressing RET on the first candidate
which is a false candidate because man is not using a must-match
argument.


-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2020-07-20 09:44
Also your helm installation is not conventional, please read the wiki page on how to install helm.
Also please use emacs-helm.sh when reporting a bug.
Closing now.

**Closed by thierryvolpiatto** 2020-07-20 09:44 UTC
