### ISSUE TITLE
Helm etags does not reload TAGS file automatically.

### ISSUE THREAD

**Issue by Crazy-Owl** [emacs-helm/helm#1374] opened 2016-02-02 09:11 UTC
Hello. I have a problem with revisiting TAGS table. I have a script that regenerates TAGS table every 30 seconds, and almost every time I invoke `#'helm-etags-select` it asks whether I want to reload the TAGS table. I've already tried `(setq tags-revert-without-query t)` and `(setq-default tags-revert-without-query t)` and that did not help, unfortunately.
Helm versions:
```
  helm               20160201.1057
  helm-core          20160201.100
```

**Comment by thierryvolpiatto** [comment] 2016-02-03 11:27
Can you give more details, here helm is reloading TAGS file automatically when this one is modified.
So your bug is not reproductible.
BTW helm is not using `tags-revert-without-query` .
Try to reproduce your bug starting with emacs-helm.sh.
Thanks.

**Comment by Crazy-Owl** [comment] 2016-02-03 12:27
Even when I start emacs with `emacs-helm.sh` the problem still persist. `TAGS` file is modifed every 30 seconds, and almost every time I invoke `#'helm-etags-select` I am prompted for reloadint `TAGS` file. What information from `emacs-helm.sh` can I provide to further clarify the problem?

**Comment by thierryvolpiatto** [comment] 2016-02-03 12:38
Vladimir <notifications@github.com> writes:

> Even when I start emacs with emacs-helm.sh the problem still persist. TAGS file is modifed every 30 seconds, and almost every time I invoke #
> 'helm-etags-select

Are you sure you invoke helm-etags-select and not find-tag or something
else ?

How are you asked ?

There is no `y-or-n-p` in helm-tags.el.

> I am prompted for reloadint TAGS file.

As said above there is no such prompt in helm-tags.el.

-- 
Thierry

**Comment by Crazy-Owl** [comment] 2016-02-03 12:48
I invoke `helm-etags-select`, because I've tried it both through `M-x` and through keybinding.

Right now I've restarted emacs without sh-script, updated magit to version `20160202.2138` and it seems like the problem has disappeared. Don't know if this is caused by restart, update, both or none of that. I will post an update here if I'm asked about reloading tags again.

Thanks for your help.

**Comment by Crazy-Owl** [comment] 2016-02-03 13:05
I've encountered the message again. It is

`File TAGS changed on disk.  Reread from disk? (y or n) y`

**Comment by thierryvolpiatto** [comment] 2016-02-03 16:45
Vladimir <notifications@github.com> writes:

> I've encountered the message again. It is
>
> File TAGS changed on disk. Reread from disk? (y or n) y

This message comes from emacs because your file have been changed on
disk in the back of emacs (i.e by a script, a crontab or something else
external to emacs).
IOW the message is not coming from helm but from emacs itself (not a bug
but a feature).

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-02-03 16:58
I guess also you have an open buffer displaying your TAGS file.

**Comment by michael-heerdegen** [comment] 2016-02-03 18:39
Maybe what @Crazy-Owl wants is that `helm-etags-select` would honor his tags-revert-without-query -> t binding and avoid prompting?

**Comment by michael-heerdegen** [comment] 2016-02-03 18:44
I guess you could use `tags-verify-table` in `helm-etags-create-buffer` or something like that.

**Comment by thierryvolpiatto** [comment] 2016-02-03 19:25
Michael Heerdegen <notifications@github.com> writes:

> I guess you could use tags-verify-table in helm-etags-create-buffer or something like that.

No, if user kill his TAGS buffer everything should work fine for him.
IOW I won't fix this, sorry, if one wants to do it go ahead but not me.

-- 
Thierry

**Comment by Crazy-Owl** [comment] 2016-02-04 09:34
The message is indeed caused by an opened buffer with TAGS file. The question is - how that buffer was opened taking into account that I have not opened it myself?

May this be caused by "Ido virtual buffers" feature in helm? I can see TAGS buffer there (but do not open it), and not in my buffers list  (`buffers-list` for example shows no TAGS buffer).

**Comment by thierryvolpiatto** [comment] 2016-02-04 10:51
Vladimir <notifications@github.com> writes:

> The message is indeed caused by an opened buffer with TAGS file. The
> question is - how that buffer was opened taking into account that I
> have not opened it myself?

Only you can know this, AFAIK it is not helm.

> May this be caused by "Ido virtual buffers" feature in helm?

No, what you see here is a TAGS buffer previously killed.

> I can see TAGS buffer there (but do not open it), and not in my
> buffers list (buffers-list for example shows no TAGS buffer).

Your TAGS buffer have perhaps a different name e.g TAGS<2>, or you have
many buffers open and not all are displayed due to candidate-number-limit.
If your buffer appear in helm-buffers-list it should be highlighted in
red after you have updated the TAGS file from your crontab or externally
from command line (See C-h m for the meaning of colours).

More generally see the manual page of find-file-noselect (used by helm
for tags) here: 

[EVAL] (info "(elisp) Visiting Functions")

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-02-04 10:54
Note that after answering "y" to:

"File TAGS changed on disk.  Reread from disk? (y or n)"

emacs kills the TAGS buffer.

**Comment by michael-heerdegen** [comment] 2016-02-04 14:33
Thierry Volpiatto <notifications@github.com> writes:

> > The message is indeed caused by an opened buffer with TAGS file. The
> > question is - how that buffer was opened taking into account that I
> > have not opened it myself?
>
> Only you can know this, AFAIK it is not helm.
>
> > May this be caused by "Ido virtual buffers" feature in helm?
>
> No, what you see here is a TAGS buffer previously killed.
>
> > I can see TAGS buffer there (but do not open it), and not in my
> > buffers list (buffers-list for example shows no TAGS buffer).

Thierry, look at helm-etags-create-buffer.  It's helm that causes the
query by calling find-file-noselect without respecting the user option
to discard prompting.  And it kills the buffer immediately after reading
tags, so there is no TAGS buffer left.

AFAICT using tags-verify-table instead of find-file-noselect there
should solve the issue.

But I won't make the change, I _never_ used tags or etags.  I just argue
after having read the sources and I think that the issue could be solved
quite easily (and it's not Vladimir's fault).

**Comment by thierryvolpiatto** [comment] 2016-02-04 17:26
Michael Heerdegen <notifications@github.com> writes:

> Thierry, look at helm-etags-create-buffer. It's helm that causes the
> query by calling find-file-noselect without respecting the user option
> to discard prompting.

No the query is caused because a buffer is open, there is no query if
buffer is not here, you can try.
And if you mean the NO-WARN option of find-file-noselect, it is not
handling this kind of query.

> AFAICT using tags-verify-table instead of find-file-noselect there
> should solve the issue.

No these tags* functions are evil.

> But I won't make the change, I _never_ used tags or etags.

I did, but differently.

-- 
Thierry

**Closed** 2016-02-05 09:56 UTC
Labels: not_reproducible
