### ISSUE TITLE
helm-imenu-in-all-buffers error.

### ISSUE THREAD

**Issue by zw963** [emacs-helm/helm#1584] opened 2016-08-20 09:49 UTC
Please see this issue:  #1499

My settings is:
```cl
(require 'helm-imenu)
(with-eval-after-load 'helm-imenu
  (global-set-key [(control c) (j)] 'helm-imenu)
  ;; (custom-set-variables '(helm-imenu-fuzzy-match t))
  (add-hook 'prog-mode-hook
            #'(lambda ()
                (local-set-key [(control c) (j)] 'helm-imenu-in-all-buffers)))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js-mode))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . html-mode))
  (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . html-mode)))
```

 this function in some case still not worked well with me ...

When I  press `C-c j` in one ruby mode file, I got following error message. 
(sorry for could not copy backtrace, because it very very hard to copy, when I try to copy it,
helm close it immediately)

```cl
;;  just from my memory to remember
Scan error: unbalanced expression 12343 23232
;; following is some escaped ASCII code
;;  hand very long line backtrace info
...
```

I think maybe exist some ruby-mode syntax error make this function
not worked well ...

**Comment by thierryvolpiatto** [comment] 2016-08-20 10:15
Billy.Zheng <notifications@github.com> writes:

> Please see this issue: #1499
>
> My settings is:
>
> (require 'helm-imenu)
> (with-eval-after-load 'helm-imenu
>   (global-set-key [(control c) (j)] 'helm-imenu)
>   ;; (custom-set-variables '(helm-imenu-fuzzy-match t))
>   (add-hook 'prog-mode-hook
>             #'(lambda ()
>                 (local-set-key [(control c) (j)] 'helm-imenu-in-all-buffers)))
>   (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . js-mode))
>   (add-to-list 'helm-imenu-all-buffer-assoc  '(ruby-mode . html-mode))
>   (add-to-list 'helm-imenu-all-buffer-assoc  '(js-mode . html-mode)))
>
> this function in some case still not worked well with me ...
>
> When I press C-c j in one ruby mode file, I got following error message.
> (sorry for could not copy backtrace, because it very very hard to copy, when I try to copy it,
> helm close it immediately)

I wonder why. I heard several people have the same problem, I am curious
to know what is triggering this, I never had problems while debugging
helm to read/copy backtrace.

> ;;  just from my memory to remember
> Scan error: unbalanced expression 12343 23232
> ;; following is some escaped ASCII code
> ;;  hand very long line backtrace info
> ...
>
> I think maybe exist some ruby-mode syntax error make this function
> not worked well ...

Probably, could you provide the ruby file(s) so that I can reproduce.

Thanks.


-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-08-20 14:47
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

>> ;;  just from my memory to remember
>> Scan error: unbalanced expression 12343 23232

I guess this is a bug with imenu itself (which is used by helm).
Try to reproduce using M-x imenu, if you succeed, you can report
upstream to emacs-bugs.

I couldn't reproduce with some *.rb files I found around in github.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-08-20 14:54
Billy.Zheng <notifications@github.com> writes:

> Please see this issue: #1499
>
> My settings is:

BTW, unrelated to this bugreport some comments on your config.

> (require 'helm-imenu)

Using this defeat the purpose of autoloads.

> (with-eval-after-load 'helm-imenu

Using with-eval-after-load is unneeded because you already required
helm-imenu, use one or the other.

>   (global-set-key [(control c) (j)] 'helm-imenu)

Using (kbd "C-c j") is much easier...

>   ;; (custom-set-variables '(helm-imenu-fuzzy-match t))
>   (add-hook 'prog-mode-hook
>             #'(lambda ()
>                 (local-set-key [(control c) (j)]
>   'helm-imenu-in-all-buffers)))

As long as C-c j is global no need to redefine it for prog-mode.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-08-22 05:22
Closing as not reproductible.

**Closed by thierryvolpiatto** 2016-08-22 05:22 UTC

**Comment by zw963** [comment] 2016-08-22 07:33
The error message is happen again:
```rb
Imenu indexing buffers...
In `Imenu in all buffers' source: `helm-imenu-candidates-in-all-buffers' 
 (scan-error "Unbalanced parentheses" 829 1688)
```





> I guess this is a bug with imenu itself (which is used by helm). Try to reproduce using M-x imenu, if you succeed, you can report upstream to emacs-bugs.

Yes, I have tried, it can be reproduce in imenu, so I think it not a bug about helm-imenu.
though, it not caused by imenu too, just caused by `ruby-mode` parser.

Following is the content which exist problem ruby files: (<< is interpreted as HERE docment)

```rb
def generate_timestamp_shard_sequence_id(options = {})
    timestamp = (options[:timestamp_from_epoch] || self.generate_timestamp_from_epoch)<<23
    shard = (options[:shard] || SecureRandom.random_number(2**13))<<10
    sequence = (options[:sequence] || SecureRandom.random_number(2**10)) % 1024
    timestamp + shard + sequence
  end
```



> I wonder why. I heard several people have the same problem, I am curious to know what is triggering this, I never had problems while debugging helm to read/copy backtrace.

If you can copy backtrace infomation, I think this maybe some config problem.
I strong suspicion this caused by this: https://github.com/zw963/helm-popwin/blob/master/helm-popwin.el , i will verify it after a while.

Thanks for reply.
