### ISSUE TITLE
Remove unwanted contents in helm-semantic-or-imenu

### ISSUE THREAD

**Issue by zijianyue** [emacs-helm/helm#1027] opened 2015-05-20 12:38 UTC
In a c file like below, invoke helm-semantic-or-imenu ,it displayed the contents of "array2" and "abc_tag",  which is unwanted.Can you remove them?

---------------------------------
test.c

DATA_TYPE  array2[1][2] = 
{
    {{ a,   b },
     { c,   d },
     { e,   f },
     { f,   g },
     { g,   r}},
};

typedef struct abc_tag
{
    int bbb;  /* */
    short sss  /* */
    long lll;    /* */
}abc_tag_S;

**Comment by tuhdo** [comment] 2015-05-20 12:44
It is a feature and you can type to narrow it down. It is useful when you want to view values assigned to variables.

**Comment by zijianyue** [comment] 2015-05-21 01:48
Can you provide a custom option for this ,because there are big arrays which take too much space in helm-semantic, and I had to narrow it every time I open helm-semantic.

**Comment by thierryvolpiatto** [comment] 2015-05-21 05:36
zijianyue <notifications@github.com> writes:

> Can you provide a custom option for this ,because there are big arrays
> which take too much space in helm-semantic, and I had to narrow it
> every time I open helm-semantic.

Indeed, some arrays maybe huge and do not have to showup here, I will
try to see what I can do, don't know yet what is providing this though.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment] 2015-05-21 05:38
@thierryvolpiatto There are many `semantic-format-` functions that you can try and add it to an option to be selected in `helm-semantic-display-style`. If none is available, then I will write my custom semantic tag formatter based on the current formatting functions. Personally, I like the way it is or people can use `helm-imenu` instead.

**Comment by thierryvolpiatto** [comment] 2015-05-21 05:43
zijianyue <notifications@github.com> writes:

> Can you provide a custom option for this

Is (setq helm-semantic-display-style 'semantic-format-tag-name)

acceptable for you ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-05-21 06:06
Tu Do <notifications@github.com> writes:

> @thierryvolpiatto There are many semantic-format- functions that you
> can try and add it to an option to be selected in
> helm-semantic-display-style. If none is available,

Why none would be available?  The purpose of this change is to add more
options.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment] 2015-05-21 06:10
> Why none would be available? The purpose of this change is to add more options.

I mean, if you cannot select any `semantic-format-` functions that satisfy you, then I write my own and PR.

**Closed** 2015-05-21 07:48 UTC

**Comment by tuhdo** [comment] 2015-05-21 08:13
@thierryvolpiatto Now the default is even worse than `helm-imenu`. I can no longer see type information and full function signature of each function, as well as knowing which tag is a function/variable/include. If the OP wants such a simple thing, `helm-imenu` already does it.

**Comment by tuhdo** [comment] 2015-05-21 12:50
With the default we cannot even narrow based on type anymore. But it's fine if this is to be duplicated with `helm-imenu`. I'm going to set it back to the old value but this is definitely a regression.

**Comment by thierryvolpiatto** [comment] 2015-05-21 13:44
Tu Do <notifications@github.com> writes:

> With the default we cannot even narrow based on type anymore.

Try with:

`semantic-format-tag-uml-prototype-c-mode`

> But it's fine if this is to be duplicated with helm-imenu. I'm going
> to set it back to the old value but this is definitely a regression.

Now you can set a different value for each MJM which is not a
regression.
The point is to be able to set this as needed, the default should be the
safest value, which is not with old default if one open file containing
huge variables.
Same happen with classes in elisp, with default settings the display is
garbaged by the slot values, I will modify this too with:

`semantic-format-tag-abbreviate-emacs-lisp-mode`

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment] 2015-05-21 13:57
The UML looks better, but since it is designed to be displayed in UML diagram generated by COGRE, it has underline which looks ugly. Anyway, if you want a concise representation of Semantic tags, you have this function `semantic-format-tag-concise-prototype`:

```elisp
(setq helm-semantic-display-style 'semantic-format-tag-concise-prototype)
```

It really displays tags concisely as its name suggest. At least in C/C++, you know which tag is a function and which is not, since the function tag includes parameter names. And it works in Emacs Lisp the way you expect, since the function does not display values.

**Comment by thierryvolpiatto** [comment] 2015-05-21 15:52
Tu Do <notifications@github.com> writes:

> (setq helm-semantic-display-style
> 'semantic-format-tag-concise-prototype)

This is not a valid configuration anymore. 

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment] 2015-05-21 16:07
> This is not a valid configuration anymore.

I am having the older Helm a few days ago. But it's just an example. You can use `'semantic-format-tag-concise-prototype` as the default for all modes.
