### ISSUE TITLE
highlight-phrase "returning Symbol's function definition is void: nil"

### ISSUE THREAD

**Issue by ajmuela** [emacs-helm/helm#2587] opened 2023-02-10 14:01 UTC
### What happened?

* Expectation
Get the usual helm buffer with the options available

* What happened
The buffer doesn't appear.
The message "Symbol's function definition is void: nil" appears in the minibuffer 

* Backtrace
Full backtrace available. Textbox limit was hit and just copy/pasted in a rectangular to provide the full stack

### How to reproduce?

In scratch or any buffer with content:
1 M-x `highlight-phrase`
2 type a word to be highlighted in the mini-buffer

Extra:
Same behavior with different commands, such as, `b` `b` in a magit buffer to switch a branch => helm's buffer with the list of branches doesn't appear

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-26.3

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (void-function nil)                                                                  
  nil(("hi-yellow" "hi-pink" "hi-green" "hi-blue" "hi-black-b" "hi-blue-b" "hi-red-b" "hi-green-b" "hi-black-hb" "h
  apply(nil (("hi-yellow" "hi-pink" "hi-green" "hi-blue" "hi-black-b" "hi-blue-b" "hi-red-b" "hi-green-b" "hi-black
  helm-apply-functions-from-source(((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0
  helm-process-filtered-candidate-transformer(("hi-yellow" "hi-pink" "hi-green" "hi-blue" "hi-black-b" "hi-blue-b" 
  helm-compute-matches(((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) 
  helm--collect-matches((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)
  helm-update(nil)                                                                                                 
  helm-read-from-minibuffer("Highlight using face (default hi-yellow): " nil nil noresume (keymap (127 . helm-mode-
  helm-internal((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candi
  apply(helm-internal ((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>))
  helm((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candidates . h
  apply(helm ((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candida
  helm(:sources (((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candi
  helm-comp-read("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-color-apply-overlay
  helm-completing-read-default-1("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-col
  helm-completing-read-default-handler("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun an
  apply(helm-completing-read-default-handler ("Highlight using face (default hi-yellow): " [0 c-clear-char-property
  helm-mode--apply-helm-handler(helm-completing-read-default-handler ("Highlight using face (default hi-yellow): " 
  helm--completing-read-default("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-colo
  apply(helm--completing-read-default ("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun an
  #f(advice-wrapper :override completing-read-default helm--completing-read-default)("Highlight using face (default
  completing-read("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-color-apply-overla
  hi-lock-read-face-name()                                                                                         
  byte-code("\300\301\302\303\304\"!!\305 D\207" [hi-lock-regexp-okay hi-lock-process-phrase read-regexp "Phrase to
  call-interactively(highlight-phrase nil nil)                                                                     
  command-execute(highlight-phrase)
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment] 2023-02-10 16:02
Alfredo Muela ***@***.***> writes:

> What happened?
>
>   • Expectation
>     Get the usual helm buffer with the options available
>    
>   • What happened
>     The buffer doesn't appear.
>     The message "Symbol's function definition is void: nil" appears in the minibuffer
>    
>   • Backtrace
>     Full backtrace available. Textbox limit was hit and just copy/pasted in a rectangular to provide the full stack

Hmm, line are truncated so the trace is not complete, also, could you
get the backtrace with at least helm.el and helm-mode.el loaded
(i.e. not the .elc but the .el).

Thanks.
    
> How to reproduce?
>
> In scratch or any buffer with content:
> 1 M-x highlight-phrase
> 2 type a word to be highlighted in the mini-buffer

Couldn't reproduce either from my current Emacs and from emacs-helm.sh.
Are you sure you are using emacs-helm.sh?

> Extra: Same behavior with different commands, such as, b b in a magit
> buffer to switch a branch => helm's buffer with the list of branches
> doesn't appear

I don't use magit anymore (though b b was working as expected last time I
used magit), but all other generic commands (completing-read
etc...) are working as expected here.

> Helm Version
>
> Melpa or NonGnuElpa
>
> Emacs Version
>
> Emacs-26.3

Didn't try yet with Emacs-26 though, only with 28.

> OS
>
> GNU/Linux
>
> Relevant backtrace (if possible)
>
> Debugger entered--Lisp error: (void-function nil)                                                                  
>   nil(("hi-yellow" "hi-pink" "hi-green" "hi-blue" "hi-black-b" "hi-blue-b" "hi-red-b" "hi-green-b" "hi-black-hb" "h
>   apply(nil (("hi-yellow" "hi-pink" "hi-green" "hi-blue" "hi-black-b" "hi-blue-b" "hi-red-b" "hi-green-b" "hi-black
>   helm-apply-functions-from-source(((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0
>   helm-process-filtered-candidate-transformer(("hi-yellow" "hi-pink" "hi-green" "hi-blue" "hi-black-b" "hi-blue-b" 
>   helm-compute-matches(((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) 
>   helm--collect-matches((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)
>   helm-update(nil)                                                                                                 
>   helm-read-from-minibuffer("Highlight using face (default hi-yellow): " nil nil noresume (keymap (127 . helm-mode-
>   helm-internal((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candi
>   apply(helm-internal ((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>))
>   helm((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candidates . h
>   apply(helm ((((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candida
>   helm(:sources (((nomark) (name . "highlight-phrase") (init #f(compiled-function () #<bytecode 0x20dfc29>)) (candi
>   helm-comp-read("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-color-apply-overlay
>   helm-completing-read-default-1("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-col
>   helm-completing-read-default-handler("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun an
>   apply(helm-completing-read-default-handler ("Highlight using face (default hi-yellow): " [0 c-clear-char-property
>   helm-mode--apply-helm-handler(helm-completing-read-default-handler ("Highlight using face (default hi-yellow): " 
>   helm--completing-read-default("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-colo
>   apply(helm--completing-read-default ("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun an
>   #f(advice-wrapper :override completing-read-default helm--completing-read-default)("Highlight using face (default
>   completing-read("Highlight using face (default hi-yellow): " [0 c-clear-char-property-fun ansi-color-apply-overla
>   hi-lock-read-face-name()                                                                                         
>   byte-code("\300\301\302\303\304\"!!\305 D\207" [hi-lock-regexp-okay hi-lock-process-phrase read-regexp "Phrase to
>   call-interactively(highlight-phrase nil nil)                                                                     
>   command-execute(highlight-phrase)
>
> Minimal configuration
>
>   • [*] I agree using a minimal configuration
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2023-02-10 20:01
I switched to emacs-26 and could reproduce.
Should be fixed now, let me know if it works for you.
Thanks.

**Comment by ajmuela** [comment] 2023-02-11 12:53
I upgraded and it works great.
Many thanks for the prompt replies and fix, and kudos on the awesome work you do with this package!
Cheers.

**Comment by thierryvolpiatto** [comment] 2023-02-11 13:40
Alfredo Muela ***@***.***> writes:

> I upgraded and it works great.
> Many thanks for the prompt replies and fix, and kudos on the awesome work you do with this package!
> Cheers.

Thanks to confirm and for your contribution ;-)

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.*Message ID: ***@***.***>


-- 
Thierry

**Closed** 2023-02-11 18:18 UTC
Labels: bug
