### ISSUE TITLE
^\\.[^.]+ does not work in helm-boring-file-regexp-list

### ISSUE THREAD

**Issue by beojan** [emacs-helm/helm#2151] opened 2019-04-12 11:04 UTC
## Expected behavior
Files starting with a dot (other than `.` and `..`) are hidden in the helm find-files list.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
These files still appear in the list.

## Steps to reproduce (recipe)
1. `./emacs-helm.sh`
2. `M-:` `(push "^\\.[^.]+" helm-boring-file-regexp-list)`
3. `M-:` `(setq helm-ff-skip-boring-files t)`
4. `C-x C-f` then navigate to a directory with such files

## Describe versions of Helm, Emacs, operating system, etc.
Helm 20190403
Emacs 26.1.50
Arch Linux

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
Yes

**Comment by thierryvolpiatto** [comment] 2019-04-12 13:31
Beojan Stanislaus <notifications@github.com> writes:

> Expected behavior
>
> Files starting with a dot (other than . and ..) are hidden in the helm find-files list.
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> These files still appear in the list.

Yes these files are not affected by helm-boring-file-regexp-list because
they are important, this have been discussed several times.
Don't expect any changes for this, the dotted files will always be shown.

-- 
Thierry

**Comment by beojan** [comment] 2019-04-12 13:33
That's the `.` and `..` files. As you can see from the regexp I use, I specifically exclude these with `[^.]+`. I'm trying to hide all the other dot files, while leaving the `.` and `..` links untouched.

**Comment by thierryvolpiatto** [comment] 2019-04-12 20:35
Beojan Stanislaus <notifications@github.com> writes:

> That's the . and .. files. As you can see from the regexp I use, I
> specifically exclude these with [^.]+. I'm trying to hide all the
> other dot files, while leaving the . and .. links untouched.

Oops! sorry, didn't read carefully.
Seems in your recipe you are using push, but
helm-boring-file-regexp-list have a set function that work only when you
use customize, so use either the customize interface or
customize-set-variable (just tested right now and it works).

--
Thierry

**Comment by thierryvolpiatto** [comment] 2019-04-15 16:55
Ok, to resume what you need is:

``` elisp
(setq helm-ff-skip-boring-files t)
(customize-set-variable 'helm-boring-file-regexp-list (cons "^\\..+" helm-boring-file-regexp-list))
```
Which will set internally `helm-ff--boring-regexp` (setq or push will not) with the set function of `helm-boring-file-regexp-list`.
Note the regexp is quite different from yours, it match a file beginning with "." but having also a dot in the name i.e. ".emacs.el" whereas your regexp will match only ".emacs".

**Comment by thierryvolpiatto** [comment] 2019-04-15 20:31
Beojan Stanislaus <notifications@github.com> writes:

> Is there a reason my regexp wouldn't work? I do in fact want to hide files like .bashrc.

I have already explained why your regexp doesn't work:

For something like .bashrc it will work, but for something like
.emacs.el it will not because of "[^.]+" which match anything but dots
whereas ".+" match anything one or more times.

> Ideally, I'd like something like what Ivy does, where they are hidden
> unless I type the dot, but I don't think that's possible.

No this is not implemented and will not be.

> Also, wouldn't your regexp match any file beginning with a dot with at least two characters (i.e. .. as well)?

No, ".*" would but not ".+" .  Anyway `helm-boring-file-regexp-list` have no effect on the dotted
files.

> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.*


--
Thierry

**Comment by thierryvolpiatto** [comment] 2019-04-16 08:44
> Also, wouldn't your regexp match any file beginning with a dot with at least two characters (i.e. .. as well)?

Sorry didn't read this carefully, yes "^\\..+" would match ".." but we don't have to worry about this as the regexp will be ignored for the "." and ".." special files.
I think the issue is resolved, closing now.

Thanks.

**Closed by thierryvolpiatto** 2019-04-16 08:44 UTC
