### ISSUE TITLE
helm-regexp yields backtraces when debug-on-error is t

### ISSUE THREAD

**Issue by djr7C4** [emacs-helm/helm#1453] opened 2016-03-29 10:57 UTC
I am using helm 1.9.3.  For example, after running M-x helm-regexp and entering "abc\(" an error occurs becase the regexp is invalid when debug-on-error is t.  I have found that the following advice fixes this:

    (defun my-disable-debug-on-error (orig-fun &rest args)
      (let ((debug-on-error nil))
        (apply orig-fun args)))
    
    (advice-add 'helm-regexp :around 'my-disable-debug-on-error)

**Comment by thierryvolpiatto** [comment] 2016-03-29 11:07
djr7C4 <notifications@github.com> writes:

> I am using helm 1.9.3. For example, after running M-x helm-regexp and
> entering "abc(" an error occurs becase the regexp is invalid.

Of course you have a backtrace, it is the purpose of the condition-case
to raise all errors when debug-on-error in on.

> I have found that the following advice fixes this:

> (defun my-disable-debug-on-error (orig-fun &rest args)
>   (let ((debug-on-error nil))
>     (apply orig-fun args)))
>
> (advice-add 'helm-regexp :around 'my-disable-debug-on-error)

Why by the hell are you doing this ? Just disable debug-on-error with
M-x toggle-debug-on-error or if it is set in your .emacs, comment it
out.

-- 
Thierry

**Comment by djr7C4** [comment] 2016-03-29 12:35
I don't think I've run into another command that yielded errors in the normal course of operation, so I thought that it was not intended.  Of course, it is your package.

**Comment by thierryvolpiatto** [comment] 2016-03-29 13:25
djr7C4 <notifications@github.com> writes:

> I don't think I've run into another command that yielded errors in the
> normal course of operation, so I thought that it was not intended. Of
> course, it is your package.

The question is why debug-on-error is t ?
If it is set to t somewhere in your config, please set it to nil.

There is no bug here, closing.

-- 
Thierry

**Closed** 2016-03-29 13:26 UTC

**Comment by xuchunyang** [comment] 2016-03-29 13:31
The backtraces tells this is caused by calling `(looking-at pattern)` in `helm-search-from-candidate-buffer`. I think maybe we can ignore invaild-regexp error here (like what `helm-candidates-in-buffer-search-default-fn` does), so we don't need force helm users to turn off debug-on-error.

**Comment by thierryvolpiatto** [comment] 2016-03-29 13:54
Chunyang Xu <notifications@github.com> writes:

> The backtraces tells this is caused by calling (looking-at pattern) in
> helm-search-from-candidate-buffer. I think maybe we can ignore
> invaild-regexp error here (like what
> helm-candidates-in-buffer-search-default-fn does), so we don't need
> force helm users to turn off debug-on-error.

Done, thanks.

Anyway they will have (many) other errors popping up backtraces, and not
only in helm, that's the purpose of the debugger, having debugger turned on
for no particular reason is a strange idea.

-- 
Thierry
