### ISSUE TITLE
Auctex/Reftex issue

### ISSUE THREAD

**Issue by davidcarslaw** [emacs-helm/helm#860] opened 2015-02-06 08:03 UTC
When using reflex to insert a citation from a bibliography I get:

Error in post-command-hook (helm--maybe-update-keymap): (error "No buffer named *helm*")

I can still type in a Regex - but it does not show the list of candidates that can then be narrowed. If I type "smith" nothing is shown. I then press return and it does narrow the buffer to references containing "smith".

Thanks

**Comment by thierryvolpiatto** [comment] 2015-02-06 08:29
David Carslaw <notifications@github.com> writes:

> When using reflex to insert a citation from a bibliography I get:

I suppose you mean reftex, but which reftex-* command ?
Please provide a complete recipe of what you are doing, I can't guess.
Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by davidcarslaw** [comment] 2015-02-06 08:37
OK, apologies. In a latex file, using Reflex to insert a citation you do `C-c [`, which brings up a menu with different citation styles, I close `t` (textcite). This then brings up in mini buffer `Regex{ && Regex...}{high\.]:`

If I type an expression, say "smith" no candidates are shown from which I can narrow. I *can* press return and edit will come up with all candidates containing "smith".

**Comment by thierryvolpiatto** [comment] 2015-02-06 09:17
David Carslaw <notifications@github.com> writes:

> OK, apologies. In a latex file, using Reflex to insert a citation you
> do C-c [,

Could you provide a link to such latex file (or similar) so that I can
reproduce here what you are doing ?

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by davidcarslaw** [comment] 2015-02-06 10:02
OK. Here is a minimal tex file:

```
\documentclass{article}

\bibliography{test.bib}{}

\begin{document}

Some test text. 

\end{document}
```

And if you save the text below in a file called `test.bib`, in the same directory as the tex file above.

```
@article{einstein,
    author =       "Albert Einstein",
    title =        "{Zur Elektrodynamik bewegter K{\"o}rper}. ({German})
        [{On} the electrodynamics of moving bodies]",
    journal =      "Annalen der Physik",
    volume =       "322",
    number =       "10",
    pages =        "891--921",
    year =         "1905",
    DOI =          "http://dx.doi.org/10.1002/andp.19053221004"
}
 
@book{latexcompanion,
    author    = "Michel Goossens and Frank Mittelbach and Alexander Samarin",
    title     = "The \LaTeX\ Companion",
    year      = "1993",
    publisher = "Addison-Wesley",
    address   = "Reading, Massachusetts"
}
 
@misc{knuthwebsite,
    author    = "Donald Knuth",
    title     = "Knuth: Computers and Typesetting",
    url       = "http://www-cs-faculty.stanford.edu/\~{}uno/abcde.html"
}
```

Open the tex file, put cursor at end of "Some test text", `C-c [` to insert citation, `t` for text citation, then start typing "einst" or some other text that exists in the bib file. For me it does not show candidates.

**Comment by thierryvolpiatto** [comment] 2015-02-06 11:27
David Carslaw <notifications@github.com> writes:

> OK. Here is a minimal tex file:

Thanks for the sample files.

> Open the tex file, put cursor at end of "Some test text", C-c [ to
> insert citation, t for text citation, then start typing "einst" or
> some other text that exists in the bib file. For me it does not show
> candidates.

Here what happened:

I created the files as you describe above and hit `C-c [', and I had
completion on the 3 entriesthat are in bib files.
Hitting RET bring me to a menu, hitting RET again insert the citation.

After restarting emacs, I have no completion, only history.
But this is not helm fault, because when disabling helm-mode I had no
more completion.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by davidcarslaw** [comment] 2015-02-06 11:38
OK, thanks for looking into this. It's a minor thing. I'm loving helm BTW - I keep discovering neat things I can do that I didn't know about. I really miss helm when I'm forced to use non-emacs software...

**Comment by thierryvolpiatto** [comment] 2015-02-06 12:18
David Carslaw <notifications@github.com> writes:

> OK, thanks for looking into this. It's a minor thing. I'm loving helm
> BTW - I keep discovering neat things I can do that I didn't know
> about. I really miss helm when I'm forced to use non-emacs software...

Thanks, it looks like an emacs bug, but I am unsure on how works this,
my latex/bibtex knowledge is limited, maybe you can try submitting a
bugreport to emacs.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-02-07 22:17
Closing, as this looks like an emacs bug, feel free to reopen if you find something wrong in helm itself.
Thanks.

**Closed by thierryvolpiatto** 2015-02-07 22:17 UTC

**Comment by introom** [comment] 2017-04-29 14:00
@davidcarslaw did you manage to solve this problem?  I am facing the same exact issue.
