### ISSUE TITLE
Basic mouse usage in helm minibuffer

### ISSUE THREAD

**Issue by fice-t** [emacs-helm/helm#1536] opened 2016-06-12 04:56 UTC
Hello. On occasion I will for some reason leave my Emacs frame in the middle of a helm session and attempt to click in the minibuffer to regain focus. Since the commands aren't defined in `helm-map` it (temporarily) replaces my input with an annoying warning.

I noticed that helm uses a `helm--remap-mouse-mode-map` to disable the mouse. Could this be disabled for the minibuffer only? I evaluated the following basic bindings:

```elisp
(define-key helm-map (kbd "<mouse-1>") #'mouse-set-point)
(define-key helm-map (kbd "<drag-mouse-1>") #'mouse-set-point)
(define-key helm-map (kbd "<down-mouse-1>") #'mouse-drag-region)
```
and things seemed to be improved without affecting other areas of helm.

**Comment by thierryvolpiatto** [comment] 2016-06-12 06:29
fice-t <notifications@github.com> writes:

> Hello. On occasion I will for some reason leave my Emacs frame in the
> middle of a helm session and attempt to click in the minibuffer to
> regain focus.

Please describe exactly what you are doing, you should not be able with
default settings to gain focus somewhere else while you are in a helm
session.


> Since the commands aren't defined in helm-map it (temporarily)
> replaces my input with an annoying warning.

Which warning ? Please elaborate.

> I noticed that helm uses a helm--remap-mouse-mode-map to disable the
> mouse. Could this be disabled for the minibuffer only?

No, I don't want this.

-- 
Thierry

**Comment by fice-t** [comment] 2016-06-12 16:34
> Please describe exactly what you are doing

I sometimes go into another program (another Emacs, Firefox, etc.) and that makes Emacs as a whole lose focus. If I try to click in the minibuffer on the unfocused Emacs frame, then I get the annoying message.

> Which warning ? Please elaborate.

Sorry, I just meant the `<mouse-1> is undefined` messages.

> No, I don't want this.

It doesn't seem to affect the other parts of helm or people who disable the mouse. I don't care about any 'advanced' mouse usage like selecting candidates either way, but just being able to move around in the minibuffer prompt like in the standard minibuffer would be helpful from time to time.

**Comment by thierryvolpiatto** [comment] 2016-06-12 16:55
fice-t <notifications@github.com> writes:

>     Please describe exactly what you are doing
>    
> I sometimes go into another program (another Emacs, Firefox, etc.) and
> that makes Emacs as a whole lose focus. If I try to click in the
> minibuffer on the unfocused Emacs frame, then I get the annoying
> message.
>
>     Which warning ? Please elaborate.
>    
> Sorry, I just meant the <mouse-1> is undefined messages.

No problem, when you click on the minibuffer at this time it is
unrelated to emacs (i.e the click is handled by the window manager), and
just give you back focus on emacs and its minibuffer (and at this
moment emacs receive the binding and complain), I can easily
reproduce this here by clicking on the desktop while emacs is not full
frame, loosing focus on emacs and retrieving the focus where I lost it
(i.e no need to click in the minibuffer, clicking anwhere in your frame
will restore focus in minibuffer).  The "<mouse-1> is undefined" message
is not important just ignore it.

OTOH Reenabling the mouse bindings in helm would just allow loosing the
focus in helm and its minibuffer and result in an big amount of bug
reports.

So to resume, clicking outside of the emacs frame makes emacs loose focus
(normal) and clicking back on emacs frame makes helm retrieve the focus
in its minibuffer, though with a warning notifying you that the mouse
binding is disabled, not a big deal.
So nothing is preventing emacs and helm retrieving focus in such case
AFAIK.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-06-12 17:05
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> So to resume, clicking outside of the emacs frame makes emacs loose focus
> (normal) and clicking back on emacs frame makes helm retrieve the focus
> in its minibuffer, though with a warning notifying you that the mouse
> binding is disabled, not a big deal.
> So nothing is preventing emacs and helm retrieving focus in such case
> AFAIK.

Note also that if you set your window manager focus settings to "focus
follow mouse", just moving the mouse over the emacs frame will makes
emacs and helm retrieve focus with no warnings.

-- 
Thierry

**Comment by fice-t** [comment] 2016-06-12 17:42
Thank you for the pointers. I've been using a WM that doesn't automatically follow the mouse for the past few months and have gotten used to that behaviour, but perhaps I'll change it.

> The "<mouse-1> is undefined" message is not important just ignore it.

I understand that, but it's a bit annoying to have it wipe your current input for a second. Ideally that wouldn't be there.

> OTOH Reenabling the mouse bindings in helm would just allow loosing the focus in helm and its minibuffer and result in an big amount of bug reports.

If it was enabled in all of helm then I could understand, but I don't see this behaviour with just enabling the mouse in the prompt only (not all of helm).

For example, with the minimal bindings I posted above, only clicking in the minibuffer in helm has any effect. Clicking anywhere else does not make helm lose focus and it otherwise works the same as before. Am I missing something?

**Comment by thierryvolpiatto** [comment] 2016-06-12 18:42
fice-t <notifications@github.com> writes:

> I understand that, but it's a bit annoying to have it wipe your
> current input for a second. Ideally that wouldn't be there.

I disagree, these messages make clear what the mouse is doing here, that
is nothing, I will not change this, especially because that is a minor annoyance
if one.

Thanks for your understanding.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-06-13 05:50
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> fice-t <notifications@github.com> writes:
>
>> I understand that, but it's a bit annoying to have it wipe your
>> current input for a second. Ideally that wouldn't be there.
>
> I disagree, these messages make clear what the mouse is doing here, that
> is nothing, I will not change this, especially because that is a minor annoyance
> if one.

I finally found a solution that fit for everyone, specially from the
user point of view.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-06-13 11:50
Closing now feel free to reopen if needed.

Thanks.

**Closed by thierryvolpiatto** 2016-06-13 11:50 UTC

**Comment by fice-t** [comment] 2016-06-19 00:04
@thierryvolpiatto Thank you, that is an improvement.

Testing it out, I believe that the keybinding `<mode-line> <down-mouse-1>` is not taken into account. This happens when you click (not drag) on the mode-line. This brings the focus out of the helm session forcing you to manually abort it.

**Comment by thierryvolpiatto** [comment] 2016-06-19 05:00
fice-t <notifications@github.com> writes:

> @thierryvolpiatto Thank you, that is an improvement.
>
> Testing it out, I believe that the keybinding <mode-line>
> <down-mouse-1> is not taken into account. This happens when you click
> (not drag) on the mode-line. This brings the focus out of the helm
> session forcing you to manually abort it.

Thanks for testing, I will add m-l<down-mouse-1>.

-- 
Thierry
