### ISSUE TITLE
helm-mark-all skips entries ending with a period

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1940] opened 2017-12-29 20:51 UTC
## Expected behavior

Select all entries with `M-a` (helm-mark-all).

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

Entries ending with a period (`.`) are skipped.

## Steps to reproduce (recipe)

- `M-x eshell`
- `$ touch a a. b`
- `M-x helm-find-files`
- `M-a`

## Describe versions of Helm, Emacs, operating system, etc.

Emacs: GNU Emacs 25.3.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.26) of 2017-12-04
Helm: MELPA

**Comment by Ambrevar** [comment] 2017-12-29 21:34
Since it's probably related, let me post it here: using `helm-find-files` switching to a folder ending with a period will switch to the default-directory instead.

**Comment by thierryvolpiatto** [comment] 2017-12-29 21:51
Pierre Neidhardt <notifications@github.com> writes:

> Since it's probably related, let me post it here: using helm-find-files switching to a folder ending with a period will switch to the default-directory instead.

That's the indented behavior, not a bug but a feature.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2017-12-29 21:54
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
> Select all entries with M-a (helm-mark-all).
>
> Actual behavior (from emacs-helm.sh if possible, see note at the bottom)
>
> Entries ending with a period (.) are skipped.

Yes that's what is expected for "." and "..".

> Steps to reproduce (recipe)
>
>   * M-x eshell
>   * $ touch a a. b

"a." should be marked indeed, will look into this tomorrow (think I know
what's wrong).

Thanks.

-- 
Thierry

**Comment by Ambrevar** [comment] 2017-12-29 21:54
How do you use Helm to switch to a folder named, say, `foo.`?

**Comment by thierryvolpiatto** [comment] 2017-12-30 08:17
Pierre Neidhardt <notifications@github.com> writes:

> How do you use Helm to switch to a folder named, say, foo.?

Impossible! Now fixed.

Marking all fixed as well.

Thanks.

-- 
Thierry

**Closed** 2017-12-30 12:23 UTC
