### ISSUE TITLE
Why does helm-locate work relatively slow for a small number of candidates?

### ISSUE THREAD

**Issue by boykov** [emacs-helm/helm#840] opened 2015-01-25 02:18 UTC
There are two different cases in `helm-locate` behavior:

1) for example, pattern: **package**

`helm-locate` begins to show candidates immediately. (Note: `locate -i -e package` gives thousands of candidates.)

2) pattern: **package.rcp**

`helm-locate` waits a few seconds and begins to show candidates. (`locate -i -e package.rcp` gives 20+ candidates.)

I tried different patterns: 2) proceeds to 1) at aproximately 300 candidates. But `anything-locate` works quickly in both cases. How to make `helm-locate` work quickly for a small number of candidates?

**Comment by PythonNut** [comment] 2015-01-29 03:22
As far as I can tell from what you write, you can try the following, which limits the number of candidates to 100, which should be pretty fast.
```emacs
(with-eval-after-load 'helm-locate
  (setq helm-source-locate
    (helm-make-source "Locate" 'helm-locate-source
      :pattern-transformer 'helm-locate-pattern-transformer
      :candidate-number-limit 100)
    helm-locate-command "locate %s -r %s -be -l 100"))
```

**Comment by boykov** [comment] 2015-01-29 03:51
I tried these settings, but the problem lies elsewhere. If I use option  `-l 10` `helm-locate` works instantly, but I lose other candidates. The value of variable `:candidate-number-limit` doesn't matter because the delay **doesn't** arise in 1) case with 300+ candidates. And `anything-locate` works well in both cases. It seems like `helm-locate` waits something like "filling a buffer" before to display results. And in 2) case with 20+ candidates the event "`locate -i -e package.rcp` stops work" comes earlier than `helm-locate` starts to display results. In 1) case with 300+ candidates a hypothetical "buffer" filled quickly and `helm-locate` starts to display results quickly too.

**Comment by michael-heerdegen** [comment] 2015-01-29 09:33
It is very unlikely that something in Helm is the culprit.

Note that since the times of anything, the options we pass to locate have changed.  See helm-locate-set-command and check your value of helm-locate-command to see how locate is called. For me on Debian this is something like

```
locate -e -A --regex some-pattern
```

Please check whether the actual call to locate that helm makes is faster when you do it from the command line.

BTW, I don't see unacceptable long delays here.  Probably it also depends on your implementation of locate.

**Comment by boykov** [comment] 2015-01-29 11:13
...But `anything-locate` works with the same implementation of locate in my system. I uploaded the screencast http://youtu.be/xL9JggHZmfs There is a delay for 3 seconds in the case of `helm-locate` + string `package.rcp`.

**Comment by michael-heerdegen** [comment] 2015-01-29 13:14
Evgeny Boykov <notifications@github.com> writes:

> ...But anything-locate works with the same implementation of locate in
> my system.

Yes, but it calls locate differently.  Have you tried to call locate
with the same options as helm does, from the command line?  Is it faster
there?

**Comment by boykov** [comment] 2015-01-29 14:46
If I call pure `locate -i -e package.rcp` in the shell (my `helm-locate-command` is "locate %s -e %s", `anything-c-locate-options` is the same) then it immediately starts to give output line by line and generates full list (20+ items) for 3 seconds. `anything-locate` reproduce this behavior exactly, but `helm-locate` shows empty buffer for 3 seconds (screencast: 18, 19, 20 seconds) and displays the full list at once. Note that pure `locate -i -e anything-` generates full list for 3 seconds too, but there are 300+ items here. And in this case `helm-locate` starts to give output line by line without delay.

**Comment by michael-heerdegen** [comment] 2015-01-29 18:39
Ok.  Thanks for the screencast.

If you do M-x trace-function-background start-process-shell-command RET and reproduce the recipe, you see how Emacs calls locate in the buffer *trace-output*.

In your case, with the value of helm-locate-command you mentioned, the call when using helm-locate should look like:

```
(start-process-shell-command
   "locate-process" "*helm locate*" "locate -e package.rpc")
```

Please verify this.  When it is correct, what happens if you call this directly from Emacs with M-:

```
(let ((buffer "Test"))
  (start-process-shell-command
   "locate-process" buffer "locate -e package.rpc")
  (pop-to-buffer "Test"))
```

Do you get the same delay as with helm-locate?

**Comment by boykov** [comment] 2015-01-29 23:13
I prepared suitable experiment with *trace-output*:
- `helm-locate`

1 -> start-process-shell-command: name="locate-process" buffer="*helm locate*" args=("locate -i -e package.rcp ")
1 <- start-process-shell-command: <process locate-process>

- `(buffer "Test")`

1 -> start-process-shell-command: name="locate-process" buffer="Test" args=("locate -i -e package.rpc")
1 <- start-process-shell-command: <process locate-process>

- `anything-locate`

1 -> start-process-shell-command: name="locate-process" buffer=nil args=("locate -i -e package.rcp")
1 <- start-process-shell-command: <process locate-process>

In most cases the command 

    (let ((buffer "Test"))
      (start-process-shell-command
       "locate-process" buffer "locate -i -e package.rcp")
      (pop-to-buffer "Test"))

immediately starts to print all 20+ lines of output to buffer "Test" with the string "Process locate-process finished" at the end. Occasionally it doesn't print anything and "abnormally" fails, but I can't safely reproduce this case. So I can't say that I get the same delay as with `helm-locate`.

And there is fragment of *Debug Helm Log* with 3 seconds delay here (string "package.rcp"):

** 08:46:29.751891 (helm-update)
 end update
** 08:46:32.621889 (helm-output-filter-1)
 output-string =  ...`locate` output here...

and for string "package":

** 09:07:52.557605 (helm-update)
 end update
** 09:07:52.568744 (helm-output-filter-1)
 output-string = "/etc/alternatives/javafxpackager
...50 lines here...

**Comment by michael-heerdegen** [comment] 2015-01-30 08:52
Thanks.

Can you please check whether the behavior is the same from helm.sh (after setting helm-locate-command to the value you use)?  BTW, where is the definition for anything-locate from? Do you have helm and anything installed in parallel?

**Comment by boykov** [comment] 2015-01-30 16:20
First I just run default `./emacs-helm.sh`: the behavior is the same (3 secs delay), then I set up `helm-locate-command` in `./emacs-helm.sh` to the value I use - same here.

 So I can reproduce the behavior in this way:
1) clone emacs-helm/helm from github
2) make all
3) choose string which gives 20+ candidates in `locate` such as "package.rcp" (or "anything-c-", etc) in my system
4) ./emacs-helm.sh
5) M-x helm-locate RET package.rcp
6) String which gives 300+ candidates generates the behavior without delay as before.

I use http://repo.or.cz/r/anything-config.git where file `anything-config.el` contains my `anything-locate` settings. Yes, I have `helm` and `anything` in parallel until I get rid of `anything` completely - but `helm-locate` breaks my workflow.

**Comment by thierryvolpiatto** [comment] 2015-01-30 16:48
Evgeny Boykov <notifications@github.com> writes:

> Yes, I have helm and anything in parallel until I get rid of anything
> completely - but helm-locate breaks my workflow.

helm-locate is using the default transformer for file and it is probably
the culprit, I will look into this ASAP.

The simple command below should work as you expect:
(Don't try to jump to a file, I haven't added any action)

(defun helm-anything-locate ()
  (interactive)
  (let ((cmd (case system-type
               ('gnu/linux "locate -i -r %s")
               ('berkeley-unix "locate -i %s")
               ('windows-nt "es -i -r %s")
               (t "locate %s"))))
    (helm :sources (helm-build-async-source "helm anything locate"
                     :candidates-process
                     (lambda ()
                       (prog1
                           (start-process-shell-command "locate-process" nil
                                                        (format cmd helm-pattern))
                         (set-process-sentinel (get-process "locate-process")
                                               #'(lambda (process event)
                                                   (when (string= event "finished\n")
                                                     (with-helm-window
                                                       (force-mode-line-update nil)
                                                       (helm-update-move-first-line)))))))
                     :mode-line helm-generic-file-mode-line-string
                     :requires-pattern 3))))

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-01-30 17:01
Should be fast again now.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by boykov** [comment] 2015-01-30 20:24
Thank you, the patch [09bf987](https://github.com/emacs-helm/helm/commit/09bf98764b6d363326861780eeaba4e0f7993646) helped.

**Comment by thierryvolpiatto** [comment] 2015-01-31 22:38
Ok, closing, thanks for raising this issue.

**Closed by thierryvolpiatto** 2015-01-31 22:38 UTC
