### ISSUE TITLE
helm-esh-pcomplete leaves an extra space when canceled

### ISSUE THREAD

**Issue by justmytwospence** [emacs-helm/helm#1273] opened 2015-11-25 05:17 UTC
I've followed the setup for eshell in the wiki. When I press tab to activate helm-esh-pcomplete and then press escape to cancel it, I an extra spaces gets inserted, which is a little annoying. Can others replicate or is it something in my setup?

**Comment by justmytwospence** [comment] 2015-11-25 22:32
@thierryvolpiatto that commit now actually causes the opposite problem. Now the space just before when I press tab is deleted (both when cancelling helm and when selecting one of the helm items).

**Comment by thierryvolpiatto** [comment] 2015-11-26 06:32
Spencer Boucher <notifications@github.com> writes:

> @thierryvolpiatto that commit now actually causes the opposite
> problem. Now the space just before when I press tab is deleted (both
> when cancelling helm and when selecting one of the helm items).

Right, I have reverted this commit, I will fix this this later, not the
time now.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by justmytwospence** [comment] 2015-11-29 00:09
Thanks for fixing this!

**Comment by justmytwospence** [comment] 2015-11-30 17:32
whoopsadaisy looks like now a single character is sliced off of the end of the selected item.

**Comment by thierryvolpiatto** [comment] 2015-11-30 18:19
Spencer Boucher <notifications@github.com> writes:

> whoopsadaisy looks like now a single character is sliced off of the end of the selected item.

Please a recipe would help, can't reproduce for now.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by justmytwospence** [comment] 2015-12-01 20:11
Hmmm, I can't reproduce it myself now, nevermind.

**Comment by justmytwospence** [comment] 2015-12-02 20:26
Ah, figured it out. The problem only occurs when you press tab *before* typing any letters. So `<tab>cd<ret>` slices off the `d`, but `c<tab>d<ret>` does not.

**Comment by thierryvolpiatto** [comment] 2015-12-03 05:24
Spencer Boucher <notifications@github.com> writes:

> Ah, figured it out. The problem only occurs when you press tab before
> typing any letters. So <tab>cd<ret> slices off the d, but c<tab>d<ret>
> does not.

Ah, great you found it, we have to check if last char is a space before
deleting it, should be fixed now.

Thanks.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Closed** 2015-12-07 06:14 UTC
Labels: bug, need_more_info
