### ISSUE TITLE
`wrong-type-argument stringp nil`

### ISSUE THREAD

**Issue by CyberShadow** [emacs-helm/helm#1467] opened 2016-04-11 03:57 UTC
I got this when I opened `helm-for-files`:

![](http://dump.thecybershadow.net/671e08c1e69e34af529bb923b35beb3a/helmbug.png)

It looks like the backtrace buffer has no `default-directory`, so calling `abbreviate-file-name` fails.

**Comment by CyberShadow** [comment] 2016-04-11 04:01
https://github.com/emacs-helm/helm/pull/1468

**Comment by thierryvolpiatto** [comment] 2016-04-11 05:38
Vladimir Panteleev <notifications@github.com> writes:

> I got this when I opened helm-for-files:
>
> [687474]
>
> It looks like the backtrace buffer has no default-directory, so calling abbreviate-file-name fails.

Why your backtrace buffer doesn't have a default-directory ?
It have always a default-directory like all emacs buffers.

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub*


-- 
Thierry

**Comment by CyberShadow** [comment] 2016-04-11 14:49
Sorry, I don't know. It just started happening.

**Comment by michael-heerdegen** [comment] 2016-04-11 21:05
We need to be sure about the reason.  Maybe the next time `default-directory' is bound to a number, or to a string for that `abbreviate-file-name' fails...

AFAIK, default-directory should not be bound to nil normally.

**Comment by CyberShadow** [comment] 2016-04-17 09:52
> We need to be sure about the reason.

I reproduced it. It happens when something is causing Emacs to be stuck, and you send a SIGUSR2 to the emacs process. This causes a backtrace buffer to appear. The thus-created backtrace buffer seems to lack a default-directory.

**Comment by michael-heerdegen** [comment] 2016-04-17 10:45
Does this depend on this "something"?

When I send SIGUSR2 to my Emacs, the debugger buffer has `default-directory -> "~/"`.

**Comment by thierryvolpiatto** [comment] 2016-04-25 10:06
As this is very specific and more related to an emacs bug and also not reproductible, I am closing, feel free to reopen if more infos.

**Closed by thierryvolpiatto** 2016-04-25 10:06 UTC

**Comment by CyberShadow** [comment] 2016-04-25 12:31
It hasn't happened since my last comment, so OK. I'll let you know if I find a way to reproduce it reliably.

**Comment by CyberShadow** [comment] 2016-04-25 16:28
It happened again :/ It definitely happens after I send a SIGUSR2 (I think when Emacs is waiting on a subprocess), but it only seems to happen sometimes.

The patch I proposed in #1467 is small and personally I don't see a problem with merging it.

**Comment by thierryvolpiatto** [comment] 2016-04-25 16:59
Vladimir Panteleev <notifications@github.com> writes:

> The patch I proposed in #1467 is small and personally I don't see a problem with merging it.

Done, thanks.

> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub*


-- 
Thierry
