### ISSUE TITLE
helm-org-in-buffer-headings doesn't work in cloned buffer

### ISSUE THREAD

**Issue by LeoUfimtsev** [emacs-helm/helm#1071] opened 2015-06-22 18:28 UTC
If I run `helm-org-in-buffer-headings` in a cloned buffer, I get : 

      find-file-noselect: Wrong type argument: stringp, nil [2 times]

Maybe it's got something to do with the fact that there are '<2>' brackets in the buffer name?

I have been observing this issue for a very long time (months).
Emacs 25.0.50.6 & helm: 20150610.1327.

**Comment by thierryvolpiatto** [comment] 2015-06-22 19:11
LeoUfimtsev <notifications@github.com> writes:

> If I run helm-org-in-buffer-headings in a cloned buffer, I get :
>
>   find-file-noselect: Wrong type argument: stringp, nil [2 times]
>
> I have been observing this issue for a very long time (months).
> Emacs 25.0.50.6 & helm: 20150610.1327.

You sent a bug report #987 for this and I fixed the issue in
df84654cffdd19643866def141e7a6ae09825f05
Please reinstall helm correctly, it is working with the recipe you sent
in issue #987.

PS Please next time reopen the old bug, if needed and follow what is happening
on your bug report, this will save my time.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-06-22 20:43
Duplicate of #987 which have been already fixed, closing.

**Closed by thierryvolpiatto** 2015-06-22 20:43 UTC

**Comment by LeoUfimtsev** [comment] 2015-06-24 14:58
My apologies for the duplicate submission. I completely forgot that I submitted it. I thought I had updated & tried latest helm but upon closer inspection I was using an older version. With the new version all works well. Thank you for bugfix.
