### ISSUE TITLE
Read only text breaks helm-mark-ring

### ISSUE THREAD

**Issue by PythonNut** [emacs-helm/helm#1176] opened 2015-09-18 17:54 UTC
Steps to reproduce:

1. `emacs24.5 -Q`
2. <kbd>&lt;up&gt;</kbd> <kbd>&lt;up&gt;</kbd> <kbd>C-SPC</kbd> <kbd>C-SPC</kbd> to set a mark on a non-empty line
3. <kbd>M-x</kbd> `package-initialize` (for autoloading `helm`)
4. <kbd>M-x</kbd> `helm-mark-ring`

Attempt to type a query. You should get:

> Error running timer: (text-read-only)

**Comment by thierryvolpiatto** [comment] 2015-09-18 18:44
PythonNut <notifications@github.com> writes:

> Steps to reproduce:
>
>  1. emacs24.5 -Q
>  2. <up> <up> C-SPC C-SPC to set a mark on a non-empty line
>  3. M-x package-initialize (for autoloading `helm)
>  4. M-x helm-mark-ring
>
> Attempt to type a query. You should get:
>
>     Error running timer: (text-read-only)

Can't reproduce.
 
-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by PythonNut** [comment] 2015-09-18 18:50
Wait a minute, I forgot the most important step: adding the read-only text properties.

Steps to reproduce:

1. `emacs24.5 -Q`
2. <kbd>&lt;up&gt;</kbd> <kbd>&lt;up&gt;</kbd> <kbd>C-SPC</kbd> <kbd>C-SPC</kbd> to set a mark on a non-empty line
3. <kbd>M-:</kbd> `(add-text-properties (point-min) (point-max) '(read-only t))` <kbd>RET</kbd>
4. <kbd>M-x</kbd> `package-initialize` <kbd>RET</kbd> (for autoloading `helm`) 
5. <kbd>M-x</kbd> `helm-mark-ring` <kbd>RET</kbd>

**Comment by thierryvolpiatto** [comment] 2015-09-18 19:08
PythonNut <notifications@github.com> writes:

> Wait a minute, I forgot the most important step: adding the read-only text properties.

Hmm, change nothing, still not reproductible.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by PythonNut** [comment] 2015-09-18 19:15
It's reproducing for me just fine. I'll check if I can reproduce it on another machine later.

**Comment by PythonNut** [comment] 2015-09-19 02:51
@thierryvolpiatto just reproduced on a completely different machine. Are you sure?

**Comment by thierryvolpiatto** [comment] 2015-09-19 05:35
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto just reproduced on a completely different machine. Are you sure?

Could reproduce finally, I forgot typing something in minibuffer.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by PythonNut** [comment] 2015-09-29 22:37
@thierryvolpiatto this problem seems to have resurfaced on the latest master.... weird.

**Comment by thierryvolpiatto** [comment] 2015-09-30 04:41
PythonNut <notifications@github.com> writes:

> @thierryvolpiatto this problem seems to have resurfaced on the latest master.... weird.

Recipe ?

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment] 2015-09-30 05:42
Should be fixed now.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment] 2015-09-30 18:30
Thanks, closing now, feel free to reopen if something wrong.

**Closed by thierryvolpiatto** 2015-09-30 18:30 UTC
