### ISSUE TITLE
Glitch when helm-follow-mode is activated programmatically

### ISSUE THREAD

**Issue by jagrg** [emacs-helm/helm#1556] opened 2016-07-07 10:32 UTC
It gets worse when `helm-autoresize-mode` is on. To reproduce:

```elisp
(helm-autoresize-mode 1)

(defun foo-bar ()
  (interactive)
  (let ((words nil))
    (save-excursion
      (goto-char (point-min))
      (while (re-search-forward "^word1\\|^word2" nil t)
	(let ((match (thing-at-point 'word t)))
	  (cl-pushnew match words :test #'equal))))
    (helm :sources
	  (helm-build-sync-source "Foo bar"
	    ;; glitches:
	    ;; :follow 1
	    ;; this also glitches:
	    :init (lambda () (helm-attrset 'follow 1))
	    ;; works with a delay?
	    ;; :init (lambda () (run-with-timer 0 nil
	    ;; 				     (lambda ()
	    ;; 				       (helm-attrset 'follow 1))))
	    :persistent-action (lambda (_candidate) (ignore))
	    :candidates (mapcar (lambda (x)
				  (format "%s" x))
				(nreverse words))))))

word1
word2
```

**Comment by thierryvolpiatto** [comment] 2016-07-07 11:13
Jonathan Gregory <notifications@github.com> writes:

> It gets worse when helm-autoresize-mode is on. To reproduce:
>
> (helm-autoresize-mode 1)
>
> (defun foo-bar ()
>   (interactive)
>   (let ((words nil))
>     (save-excursion
>       (goto-char (point-min))
>       (while (re-search-forward "^word1\\|^word2" nil t)
>     (let ((match (thing-at-point 'word t)))
>       (cl-pushnew match words :test #'equal))))
>     (helm :sources
>       (helm-build-sync-source "Foo bar"
>         ;; glitches:
>         ;; :follow 1
>         ;; this also glitches:
>         :init (lambda () (helm-attrset 'follow 1))
>         ;; works with a delay?
>         ;; :init (lambda () (run-with-timer 0 nil
>         ;;                   (lambda ()
>         ;;                     (helm-attrset 'follow 1))))
>         :persistent-action (lambda (_candidate) (ignore))
>         :candidates (mapcar (lambda (x)
>                   (format "%s" x))
>                 (nreverse words))))))

Please explain what is getting worse, the code above is irrelevant what
do you expect from such code ?

-- 
Thierry

**Comment by jagrg** [comment] 2016-07-07 11:42
I'm not sure if glitch is the right word to describe the problem.

With: `:init (lambda () (helm-attrset 'follow 1))`, or `:follow 1` I get:
![lb](https://cloud.githubusercontent.com/assets/8846979/16652092/0d99f98e-4440-11e6-9ecb-00743f8f9de8.gif)


With
```
:init (lambda () (run-with-timer 0 nil
				 (lambda ()
				   (helm-attrset 'follow 1))))
```
I get:
![lb2](https://cloud.githubusercontent.com/assets/8846979/16652109/266b1268-4440-11e6-92b8-36a982dafbe8.gif)


The last image is what I would expect to happen with the first code.

**Comment by thierryvolpiatto** [comment] 2016-07-07 14:08
Jonathan Gregory <notifications@github.com> writes:

> I'm not sure if glitch is the right word to describe the problem.
>
> With: :init (lambda () (helm-attrset 'follow 1)), or :follow 1 I get:
> lb      
>
> With
>
> :init (lambda () (run-with-timer 0 nil
>                  (lambda ()
>                    (helm-attrset 'follow 1))))

Please use the : follow keyword instead of using :init.

:follow 1

> I get:
> lb2     
>
> The last image is what I would expect to happen with the first code.

Sorry but I see no difference and still don't understand what you want
to achieve, follow+autoresize is working here as expected AFAICT.

-- 
Thierry

**Comment by jagrg** [comment] 2016-07-07 14:52
I tested with emacs -Q and I still get the glitch (fig 1), which I believe is a bug. The same happens with the `:follow` keyword, irrespective of whether helm-autoresize-mode is activated. But if you cannot reproduce it (and you are sure about that ;)), then I guess we can close the issue.

**Comment by thierryvolpiatto** [comment] 2016-07-08 06:47
Sorry but I still do not understand what you call the glitch and what is your issue, I am closing this, please come back if needed with a new bug report describing exactly what the issue is.

**Comment by tuhdo** [comment] 2016-07-08 07:06
I think what he meant is that in fig 1, Helm window appeared with default size then reduced to small size. In fig 2, the window appeared small immediately.

**Comment by jagrg** [comment] 2016-07-08 08:27
There are two problems here. One, as @@tuhdo describes (thanks!), is that the helm window pops with the default size first, before reducing to the small size (see fig 1). I'm not sure how this is done, but maybe the follow function needs to be activated later (?).

The second problem, and this is not related to `helm-autoresize-mode`, is that the helm window shows up with two different layouts. Here are the screenshots of when this transition occurs:

Before:
![screen shot 2016-07-08 at 09 14 44](https://cloud.githubusercontent.com/assets/8846979/16681558/576ea00c-44ed-11e6-8893-29224784801b.png)

After:
![screen shot 2016-07-08 at 09 15 18](https://cloud.githubusercontent.com/assets/8846979/16681580/6fe981ce-44ed-11e6-9e68-5c1dfbc07391.png)

And here is the problem in action without `helm-autorize-mode` activated:
![lb3](https://cloud.githubusercontent.com/assets/8846979/16681616/b417b712-44ed-11e6-81df-97e5e6a2812a.gif)

**Comment by thierryvolpiatto** [comment] 2016-07-08 12:27
Tu Do <notifications@github.com> writes:

> I think what he meant is that in fig 1, Helm window appeared with
> default size then reduced to small size. In fig 2, the window appeared
> small immediately.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-07-08 12:30
Here a small recipe working here as expected from ./emacs-helm.sh:

```elisp
(helm-autoresize-mode 1)
(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e)
                 :follow 1)
      :buffer "*helm test*")
```

**Comment by thierryvolpiatto** [comment] 2016-07-08 12:33
For the 3rd issue you described, I don't understand what you mean by two layouts.

**Comment by jagrg** [comment] 2016-07-08 16:54
> Here a small recipe working here as expected from ./emacs-helm.sh:

I still see the same problem. Does this happen to you, @tuhdo?

> For the 3rd issue you described, I don't understand what you mean by two layouts.

I made a screenshot of the before and after (this is what I meant by two layouts). Please refer to those images and you will see the difference, specifically in the minibuffer, modeline and persistent help. This is one reason why the window blinks (fig 1). It also blinks when `helm-autoresize-mode` is on, as I described earlier. The helm window pops up and down, when it should pop only to its smaller size.

I'm using GNU Emacs 24.5.1 and helm-20160707.305:

**Comment by thierryvolpiatto** [comment] 2016-07-08 17:37
I think I start understanding what you mean, even if it is difficult to see something in your screenshots.
Does this patch fix your problem ?

```diff

diff --git a/helm.el b/helm.el
index cc88f69..f0386ca 100644
--- a/helm.el
+++ b/helm.el
@@ -2226,7 +2226,8 @@ value of `helm-full-frame' or `helm-split-window-default-side'."
                (not helm-split-window-in-side-p))
       (delete-other-windows))
     (display-buffer
-     buffer `(nil . ((window-height . ,helm-display-buffer-default-size))))))
+     buffer `(nil . ((window-height . ,helm-display-buffer-default-size))))
+    (helm-log-run-hook 'helm-window-configuration-hook)))
 
 
 ;;; Core: initialize
```

**Comment by jagrg** [comment] 2016-07-08 18:08
Thanks. This fixes the first issue (the window moving up and down).

The second issue is easier to see with a delay:

```elisp
(helm-autoresize-mode 1)
(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e)
		 :follow-delay 1
                 :follow 1)
      :buffer "*helm test*")
```

After 1 second, the helm window changes. Do you see it?

**Comment by thierryvolpiatto** [comment] 2016-07-08 18:56
Jonathan Gregory <notifications@github.com> writes:

> Thanks. This fixes the first issue (the window moving up and down).
>
> The second issue is easier to see with a delay:
>
> (helm-autoresize-mode 1)
> (helm :sources (helm-build-sync-source "test"
>                  :candidates '(a b c d e)
>          :follow-delay 1
>                  :follow 1)
>       :buffer "*helm test*")
>
> After 1 second, the helm window changes. Do you see it?

I see, but seems it is not the window itself but the header-line.
I will look into this tomorrow.

Thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-07-09 06:21
Jonathan Gregory <notifications@github.com> writes:

> Thanks. This fixes the first issue (the window moving up and down).
>
> The second issue is easier to see with a delay:
>
> (helm-autoresize-mode 1)
> (helm :sources (helm-build-sync-source "test"
>                  :candidates '(a b c d e)
>          :follow-delay 1
>                  :follow 1)
>       :buffer "*helm test*")
>
> After 1 second, the helm window changes. Do you see it?

This second issue should be fixed now.
This fix change a little the behavior of follow in that the first
candidate of source (or preselected) is not followed on startup, follow start only when
starting going to (next/previous)-line, which is better IMO.

-- 
Thierry

**Comment by jagrg** [comment] 2016-07-09 08:49
This fixes the second issue, thanks!

But we need to follow the first candidate on startup. When I run the following code I would expect "a" to appear as soon as it opens, otherwise we would have to press `C-p` for "a" to appear, which doesn't seem right (or intuitive) to me.

```elisp
(helm :sources (helm-build-sync-source "test"
                 :candidates '(a b c d e)
		 :persistent-action (lambda (candidate)
				      (message candidate))
                 :follow 1)
      :buffer "*helm test*")
```

**Comment by thierryvolpiatto** [comment] 2016-07-09 11:32
Jonathan Gregory <notifications@github.com> writes:

> This fixes the second issue, thanks!
>
> But we need to follow the first candidate on startup. When I run the
> following code I would expect "a" to appear as soon as it opens,
> otherwise we would have to press C-p for "a" to appear, which doesn't
> seem right (or intuitive) to me.

I can reenable this behavior without letting the window blink, 
note that when reenabled, the minibuffer will always popup _after_ the
persistent action runs.

-- 
Thierry

**Comment by jagrg** [comment] 2016-07-09 15:23
@thierryvolpiatto, I think you're right.

The follow keyword should mimic what `helm-follow-mode` (`C-c C-f`) does interactively, which is to call the persistent action after pressing `C-n`.

Could you revert that last commit? Many thanks for this. Everything is working as expected.

**Comment by thierryvolpiatto** [comment] 2016-07-09 15:46
Jonathan Gregory <notifications@github.com> writes:

> @thierryvolpiatto, I think you're right.
>
> The follow keyword should mimic what helm-follow-mode (C-c C-f) does
> interactively, which is to call the persistent action after pressing
> C-n.

Yes, I don't use much follow-mode, but the few times I tried enabling it
persistently in helm-occur, I found this behavior annoying.

> Could you revert that last commit?

Done.

> Many thanks for this. Everything is working as expected.

Great, thanks for your help.

-- 
Thierry

**Closed** 2016-07-09 16:38 UTC
