### ISSUE TITLE
Eshell completion goes wrong on `../../`

### ISSUE THREAD

**Issue by Ambrevar** [emacs-helm/helm#1832] opened 2017-08-07 14:32 UTC
## Expected behavior

Path completion on `../../` (and more levels back) should work just like vanilla `eshell-pcomplete`.

## Actual behavior

- `ls ../../<TAB>` expands to `ls ./`.
- `ls ../../../<TAB>` expands to `ls ./` and so on.
- `ls ../../anything-completable-but-double-dots` does not yield anything.

## Steps to reproduce (recipe)

Add this to your init file:
```
(define-key eshell-mode-map [remap eshell-pcomplete] 'helm-esh-pcomplete)
```

Open Eshell and try out the aforementioned `ls...` commands.

## Describe versions of helm, emacs, operating system etc.

- helm: latest MELPA
- Emacs 25.2

**Comment by thierryvolpiatto** [comment] 2017-08-07 21:04
Pierre Neidhardt <notifications@github.com> writes:

> Expected behavior
>
> Path completion on ../../ (and more levels back) should work just like vanilla eshell-pcomplete.

Thanks, should work now.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment] 2017-08-08 08:41
It does fix the `../../` issue but it broke completion of anything but filenames: command, args, etc.

**Comment by thierryvolpiatto** [comment] 2017-08-08 09:43
Pierre Neidhardt <notifications@github.com> writes:

> It does fix the ../../ issue but it broke completion of anything but filenames: command, args, etc.

I made a quick fix, should work now.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment] 2017-08-08 12:06
Still a corner case: it does not complete subcommands, e.g. `git <TAB>` does not do anything.

**Comment by Ambrevar** [comment] 2017-08-08 12:10
Note that I'm using a custom completion function to generate `git`'s completion.

**Comment by thierryvolpiatto** [comment] 2017-08-08 13:21
Pierre Neidhardt <notifications@github.com> writes:

> Still a corner case: it does not complete subcommands, e.g. git <TAB>
> does not do anything.

Not only for git but for many other commands, some are implemented but
are not working with sudo etc...

See https://github.com/leoliu/pcmpl-git-el
and https://github.com/thierryvolpiatto/pcomplete-extension

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-08 13:26
Completing git command with pcmpl-git:

![capture d ecran_2017-08-08_15-16-52](https://user-images.githubusercontent.com/1533939/29073899-b484600e-7c4d-11e7-9247-4b8fe7422912.png)

**Comment by Ambrevar** [comment] 2017-08-08 14:41
Here is my config: I default to using fish shell for completion (it's awesome):

```
(setq eshell-default-completion-function 'eshell-fish-completion)
(defun eshell-fish-completion ()
  (while (pcomplete-here
          (let ((comp-list
                 (let* ((raw-prompt (buffer-substring-no-properties (save-excursion (eshell-bol) (point)) (point)))
                        ;; Keep spaces at the end with OMIT-NULLS=nil in `split-string'.
                        (toks (split-string raw-prompt split-string-default-separators nil))
                        ;; The first non-empty `car' is the command. Discard
                        ;; leading empty strings.
                        (tokens (progn (while (string= (car toks) "")
                                         (setq toks (cdr toks)))
                                       toks))
                        ;; Fish does not support subcommand completion. We make
                        ;; a special case of 'sudo' and 'env' since they are
                        ;; the most common cases involving subcommands.  See
                        ;; https://github.com/fish-shell/fish-shell/issues/4093.
                        (prompt (if (not (member (car tokens) '("sudo" "env")))
                                    raw-prompt
                                  (setq tokens (cdr tokens))
                                  (while (and tokens
                                              (or (string-match "^-.*" (car tokens))
                                                  (string-match "=" (car tokens))))
                                    ;; Skip env/sudo parameters, like LC_ALL=C.
                                    (setq tokens (cdr tokens)))
                                  (mapconcat 'identity tokens " "))))
                   ;; Completion result can be a filename.  pcomplete expects
                   ;; cannonical file names (i.e. withou '~') while fish preserves
                   ;; non-cannonical results.  If the result contains a directory,
                   ;; expand it.
                   (mapcar (lambda (e)(car (split-string e "\t")))
                           (split-string
                            (with-output-to-string
                              (with-current-buffer standard-output
                                (call-process "fish" nil t nil "-c" (format "complete -C'%s'" prompt))))
                            "\n" t)))))
            (if (file-name-directory (car comp-list))
                (pcomplete-dirs-or-entries)
              comp-list)))))
```

It works well without Helm.

**Comment by Ambrevar** [comment] 2017-08-08 14:43
Sorry, I just realized it works if I complete >=1 character.
I.e. `git p<TAB>` works while `git <TAB>` does not.

**Comment by thierryvolpiatto** [comment] 2017-08-09 04:58
Pierre Neidhardt <notifications@github.com> writes:

> Here is my config: I default to using fish shell for completion (it's awesome):

Thanks, that's interesting, but it is out of topic, it is about building
pcomplete functions, the bug report is about helm completion in eshell.

If helm is not completing stuff like e.g git, it is not an helm bug,
just that the pcomplete for this command is missing.

So let focus on our bug for now, to see if completion on "../" is
working without breaking anything else (we could talk about pcomplete in
another topic, it is just to not get lost about this bug).

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment] 2017-08-09 08:09
You misunderstood, there _is_ a regression with your last 2 commits on helm-eshell: before that `git <TAB>` worked just fine with my custom `eshell-default-completion-function`.  Completion also works fine without Helm.

**Comment by thierryvolpiatto** [comment] 2017-08-09 10:58
Pierre Neidhardt <notifications@github.com> writes:

> You misunderstood, there is a regression with your last 2 commits on
> helm-eshell: before that git <TAB> worked just fine with my custom
> eshell-default-completion-function.

Ah! ok, I indeed didn't understand that.
I have commited another change that should work.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment] 2017-08-09 18:12
Almost there, I could still find a few tests that don't pass. Here is my (certainly incomplete) list:

- command: PASS
- command options: PASS
- subcommand: PASS
- relative forward path: PASS
- `/`: PASS
- `~/`: PASS
- `~`: FAIL: should display user names.
- `../`: PASS
- `../../`: PASS
- `../a`: PASS
- `../../a`: FAIL:
- insert space after completion: FAIL

The last one is important or else when you press `git add<TAB>` it will act just like `git nonexistent<TAB>`, misleading the user into thinking the element does not exist.

**Comment by thierryvolpiatto** [comment] 2017-08-11 04:11
Pierre Neidhardt <notifications@github.com> writes:

> Almost there, I could still find a few tests that don't pass. Here is my (certainly incomplete) list:
>
>   * command: PASS
>   * command options: PASS
>   * subcommand: PASS
>   * relative forward path: PASS
>   * /: PASS
>   * ~/: PASS
>   * ~: FAIL: should display user names.
This one is not fixed, will look later what I can do, perhaps you can
open a new issue for this one.

>   * ../: PASS
>   * ../../: PASS
>   * ../a: PASS

>   * ../../a: FAIL:
Now PASS.

>   * insert space after completion: FAIL
Now PASS.

Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-11 04:53
Thierry Volpiatto <thievol05@zoho.eu> writes:

>>   * ~: FAIL: should display user names.
> This one is not fixed, will look later what I can do, perhaps you can
> open a new issue for this one.

Finally don't, have been fixed too :-)

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by Ambrevar** [comment] 2017-08-11 08:53
>   * insert space after completion: FAIL
> Now PASS.

Not completely: when completing folders, a slash should be appended but _not a space_.  This is to keep on completing without having to backspace.
Conversely, files should always insert a space after completion.

For instance
```
$ ls
unique-folder
$ cd unique-fo<TAB>
$ cd unique-folder/<*>
```
(`<*>` is the point)

Current behaviour is
```
$ cd unique-fo<TAB>
$ cd unique-folder/ <*>
```
Notice the space before the point.  This is not very convenient.

**Comment by thierryvolpiatto** [comment] 2017-08-11 12:44
Pierre Neidhardt <notifications@github.com> writes:

>       + insert space after completion: FAIL
>         Now PASS.
>
> Not completely: when completing folders, a slash should be appended
> but not a space. This is to keep on completing without having to
> backspace.  Conversely, files should always insert a space after
> completion.

Indeed, fixed this one.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-12 05:54
Another one, which is an emacs bug I think:

cd foo
cd ~/.<TAB>

helm just add a space => wrong
emacs vanilla eshell add a "/" which is not better.

M-x shell is completing properly with all files under "~/" beginning
with ".", which is the expected behavior (bash is doing this too).

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-12 07:23
Thierry Volpiatto <thievol05@zoho.eu> writes:

> Another one, which is also an emacs bug:

..<TAB> should complete to "../" but is says no completion of ".." whereas
bash complete as expected to "../".

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-14 14:50
Pierre Neidhardt <notifications@github.com> writes:

> What's up with the commit wave?

Not fully finished, there is still some problems to fix, but it's in
good way.

> My last tests are all positive.

Yeah, but some other tests are not working as expected, I hope finishing
this this week.

> Did you implement some workarounds?

Yes, now ..<TAB> add the final /, many levels of recursion are working
too i.e ../../../ and completion on hidden files when starting with an
abbreviated path is working too i.e ~/.<TAB> or ~/.emacs.d/.<TAB>
(emacs bug#28064).

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-14 15:14
BTW, if you have done some more tests since last time, can you provide them so that I can merge yours with mines, like this we should have a pretty good list of possible use cases.

Thanks.

**Comment by thierryvolpiatto** [comment] 2017-08-14 16:55
Pierre Neidhardt <notifications@github.com> writes:

> I haven't noticed any issue so far, the test cases pretty much cover all my use cases.

Great, let's try eshell a couple of days and if we don't notice
something wrong we will close this bug.

Thanks.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-16 14:46
Ok closing now, I didn't notice wrong behavior.

Thanks.

**Closed by thierryvolpiatto** 2017-08-16 14:46 UTC
