### ISSUE TITLE
Helm issued errors: helm-match-from-candidates in source `Minibuffer History': void-function (helm-mp-exact-match) query-replace-read-from: 

### ISSUE THREAD

**Issue by Jamsa** [emacs-helm/helm#1610] opened 2016-09-21 04:33 UTC
Helm issued errors: helm-match-from-candidates in source `Minibuffer History': void-function (helm-mp-exact-match) query-replace-read-from: Command attempted to use minibuffer while in minibuffer

**Comment by thierryvolpiatto** [comment] 2016-09-21 05:15
Jamsa <notifications@github.com> writes:

> Helm issued errors: helm-match-from-candidates in source `Minibuffer
> History': void-function (helm-mp-exact-match) query-replace-read-from:
> Command attempted to use minibuffer while in minibuffer

This is not reproductible.

There is a template in issue interface, please USE IT (I don't know what
you are doing and where you started from).

Thanks.

--
Thierry

**Comment by thierryvolpiatto** [comment] 2016-09-21 05:38
Closing, please make a new issue with a correct title and the form filled.

Thanks.

**Closed by thierryvolpiatto** 2016-09-21 05:38 UTC

**Comment by thierryvolpiatto** [comment] 2016-09-21 16:53
BTW note that `helm-mp-exact-match` have been renamed to `helm-mm-exact-match` since months, so I think your helm installation is bad.

**Comment by Jamsa** [comment] 2016-09-22 03:20
It worked after i delete ~/.emacs.d/.session and ~/.emacs.d/.emacs.desktop.

or remove the code from init.el
```emacs-lisp
(custom-set-variables
 '(session-use-package t nil (session)))
```

Thanks.
