### ISSUE TITLE
helm-ff-skip-boring-files t messes with typing in helm-find-files

### ISSUE THREAD

**Issue by rrthomas** [emacs-helm/helm#1844] opened 2017-08-29 10:38 UTC
## Expected behavior

I have `helm-find-files` bound to C-xC-f. When I type `C-x C-f ~/.` I expect to get:

`Find files or url: /home/rrt/.`

in the minibuffer.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

Unless I wait a while between typing `/` and `.`, I get:

`Find files or url: /home/rrt`

That is, the `.` is lost.

## Steps to reproduce (recipe)

0. Start emacs-helm.sh
1. Set `helm-ff-skip-boring-files` to `t`.
2. Type C-x C-f
3. (Quickly!) type `~/.`

Note that the minibuffer prompt now displays:

`/home/USER/`

## Describe versions of helm, emacs, operating system etc.

Emacs 25.2, Ubuntu 16.04, helm 2.8.2 (from MELPA).

**Comment by thierryvolpiatto** [comment] 2017-08-29 12:04
Reuben Thomas <notifications@github.com> writes:

> Steps to reproduce (recipe)
>
>  0. Start emacs-helm.sh
>  1. Set helm-ff-skip-boring-files to t.
>  2. Type C-x C-f
>  3. (Quickly!) type ~/.
>
> Note that the minibuffer prompt now displays:
>
> /home/USER/

I can't reproduce, I always end up with "/home/me/.".

-- 
Thierry

**Comment by rrthomas** [comment] 2017-08-29 12:33
I just double-checked, and it reproduces reliably for me. Is there anything else I can tell you?

**Comment by thierryvolpiatto** [comment] 2017-08-29 13:34
Reuben Thomas <notifications@github.com> writes:

> I just double-checked, and it reproduces reliably for me.

Hmm, I couldn't reproduce from emacs-24.5 and emacs-26 (remacs), I will
try tonight with 25.1/2.

> Is there anything else I can tell you?

Is the contents of "/home/you" displayed or you end up with an empty
helm-buffer?

If so (empty buffer) are you using outside of emacs a clipboard manager?

Also how many candidates are displayed in "/home/you"?

What is the value of `helm-boring-file-regexp-list`? (is is default value?)

To type in "~/" are you first deleting the minibuffer contents or are
you entering "~/" at end of pattern ?
e.g /home/you/somewhere/elswhere/~/ or C-k and ~/

Thanks.

--
Thierry

**Comment by rrthomas** [comment] 2017-08-29 14:10
Thanks very much for looking into this.

The contents of "/home/me" is displayed, with "441 File(s)".

helm-boring-file-regexp-list is default value (recall, I'm using `emacs-helm.sh`).

I am entering `~/" at the end of the pattern (as per the instructions for reproduction I gave above).

**Comment by thierryvolpiatto** [comment] 2017-08-29 19:27
Thanks for the infos.

Reuben Thomas <notifications@github.com> writes:

> The contents of "/home/me" is displayed, with "441 File(s)".

That's ok, that's not too much, helm-find-files starts to be slow at around
5000 files.

> helm-boring-file-regexp-list is default value (recall, I'm using emacs-helm.sh).

Ok, but I prefer asking to be sure.

> I am entering `~/" at the end of the pattern (as per the instructions for reproduction I gave above).

Ok, I failed to reproduce like this also.

For now I have no idea, I have now switched to an emacs-25.2 and still
can't reproduce.

Are you experimenting the same problem with `helm-ff-skip-boring-files`
disabled (nil) ?

Oh and are you using the melpa-stable version or the melpa version
(last) ?

-- 
Thierry

**Comment by rrthomas** [comment] 2017-08-29 22:02
There is no problem with the default (nil) value for `helm-ff-skip-boring-files`. I bisected my settings and found it was setting that to true which caused the problem.

I am using the melpa-stable version 2.8.2.

**Comment by thierryvolpiatto** [comment] 2017-08-30 04:18
Reuben Thomas <notifications@github.com> writes:

> There is no problem with the default (nil) value for
> helm-ff-skip-boring-files.
> I bisected my settings and found it was setting that to true which
> caused the problem.

Ok thanks, I have commited a change to `helm-boring-file-regexp-list`
while I was at it but I doubt it is related to your problem.

> I am using the melpa-stable version 2.8.2.

Hmm, still failing to reproduce with 2.8.2.


-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2017-08-30 05:03
Reuben Thomas <notifications@github.com> writes:

> I am using the melpa-stable version 2.8.2.

Can you try also with the melpa version (or master branch from git) ?

Thanks.

-- 
Thierry

**Comment by rrthomas** [comment] 2017-08-30 08:34
I installed MELPA version 20170829.2056; exactly the same problem.

I do use a clipboard manager, though I have Emacs patched to ignore `SELECTION_REQUEST_EVENT` in `while-no-input` (Emacs git is already patched to fix this bug more generally). I tried disabling my clipboard manager, just in case, and it didn't affect the result.

**Comment by thierryvolpiatto** [comment] 2017-08-30 09:39
Reuben Thomas <notifications@github.com> writes:

> I installed MELPA version 20170829.2056; exactly the same problem.
>
> I do use a clipboard manager, though I have Emacs patched to ignore
> SELECTION_REQUEST_EVENT in while-no-input (Emacs git is already
> patched to fix this bug more generally). I tried disabling my
> clipboard manager, just in case, and it didn't affect the result.

Yes, you would endup with a helm buffer empty if you were affected by
this problem.  Is your patched emacs modify original default value of
completion-ignored-extensions ?

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by rrthomas** [comment] 2017-08-30 09:45
I do customize `completion-ignored-extensions`, but of course when running `emacs-helm.sh` I get the default value. It's certainly not hard-patched in my build (that's just the emacs-25 branch of Emacs git with the `while-no-input` patch).

**Comment by thierryvolpiatto** [comment] 2017-08-30 10:02
Reuben Thomas <notifications@github.com> writes:

> I do customize completion-ignored-extensions, but of course when
> running emacs-helm.sh I get the default value. It's certainly not
> hard-patched in my build (that's just the emacs-25 branch of Emacs git
> with the while-no-input patch).

Ok, was just asking in case.  Thanks.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-08-30 11:01
I finally could reproduce by adding 500 empty files to my home directory and made a fix which works, I will try to optimize this fix in next days (I think it can be faster), let me know if it works for you.

**Comment by rrthomas** [comment] 2017-08-30 11:10
That's fantastic, thanks! When will MELPA (unstable) next be updated?

**Comment by thierryvolpiatto** [comment] 2017-08-30 16:31
Reuben Thomas <notifications@github.com> writes:

> That's fantastic, thanks! When will MELPA (unstable) next be updated?

You can know this approximatively by looking at their website:

https://melpa.org

You should see something like this:

    [Current build started: an hour ago, last took 4 hours]

-- 
Thierry

**Comment by rrthomas** [comment] 2017-08-30 17:32
Thanks for the reminder; I wasn't sure that it was a fully automated process (i.e. that you didn't have to make a release).

**Comment by thierryvolpiatto** [comment] 2017-08-30 18:28
Reuben Thomas <notifications@github.com> writes:

> (i.e. that you didn't have to make a release).

Only for melpa-stable.

-- 
Thierry

**Comment by rrthomas** [comment] 2017-08-30 20:57
Confirmed that this works with a current build. A great big THANK-YOU for your patience investigating and fixing this bug, especially as it took you so much work simply to reproduce it!

Is there some easy way I can find out when the fix ends up in a stable release so I can revert to MELPA stable?

**Comment by thierryvolpiatto** [comment] 2017-08-31 02:51
Reuben Thomas <notifications@github.com> writes:

> Confirmed that this works with a current build. A great big THANK-YOU
> for your patience investigating and fixing this bug, especially as it
> took you so much work simply to reproduce it!

You are welcome, thanks.

> Is there some easy way I can find out when the fix ends up in a stable
> release so I can revert to MELPA stable?

I should tag soon, you can see in relases when this happen:

https://github.com/emacs-helm/helm/releases

--
Thierry

**Comment by rrthomas** [comment] 2017-08-31 10:38
Bad news, I'm afraid. I tried 2.8.3 and the problem has returned. I tried the latest MELPA unstable version (20170830.2114), and again, the problem has returned. Fortunately, I had a copy of last night's version on another machine (20170830.357) and that still works fine.

**Comment by thierryvolpiatto** [comment] 2017-08-31 13:05
Reuben Thomas <notifications@github.com> writes:

> Bad news, I'm afraid. I tried 2.8.3 and the problem has returned. I
> tried the latest MELPA unstable version (20170830.2114), and again,
> the problem has returned.

Indeed, just tried again on the machine with many files in HOME.

> Fortunately, I had a copy of last night's version on another machine
> (20170830.357) and that still works fine.

I hardly see how it could work better, you may type less fast probably
or use in another context, nevermind, I think I understand what is
happening.  The fix I did works just by chance because of a different
timing in computation of candidate.

The real problem IIUC is that (expand-file-name "~/.") is returning
"/home/you" but not "/home/you/.".  I have been confronted to same
problem recently, but can't remember right now how I solved it and where
it was, I will look ASAP how I can fix it (possibly tomorrow morning).

The positive point is that I corrected the code parsing the
helm-boring-file-regexp-list which is now faster.

Thanks to follow up on this.

--
Thierry

**Comment by thierryvolpiatto** [comment] 2017-09-01 05:49
Reuben Thomas <notifications@github.com> writes:

> Bad news, I'm afraid. I tried 2.8.3 and the problem has returned.

Ok, hopefully should be fixed now, can you check out master (or MELPA
once updated) and give it a try?

To reproduce reliably, instead of typing fast type first `C-!`, then
enter quietly "~/." and then again `C-!`.

Thanks.


-- 
Thierry

**Comment by rrthomas** [comment] 2017-09-01 13:18
Thanks again. Using helm 20170901.128 from MELPA, it works fine, either with your reproduction method, or at my normal typing speed.

**Comment by thierryvolpiatto** [comment] 2017-09-01 13:52
Reuben Thomas <notifications@github.com> writes:

> Thanks again. Using helm 20170901.128 from MELPA, it works fine,
> either with your reproduction method, or at my normal typing speed.

Great, thanks to confirm.
I will make soon a quick release so that you can use again melpa-stable.

--
Thierry

**Comment by thierryvolpiatto** [comment] 2017-09-04 02:53
The fix is now included in 2.8.4 so you can use now melpa-stable again.

Thanks, closing now.

**Closed by thierryvolpiatto** 2017-09-04 02:53 UTC

**Comment by rrthomas** [comment] 2017-09-04 09:17
Thanks again: I'm now back on stable with things working fine, that's great!
