### ISSUE TITLE
The titles of org-links are not matched by helm-org-headlines.

### ISSUE THREAD

**Issue by tmalsburg** [emacs-helm/helm#964] opened 2015-04-01 23:06 UTC
I have a link in an org-headline:

    * This is the [[http://URL][link]].

In org-mode, this headline displays as

    * This is the link.

with `link` being blue and underlined.

The problem is that when I use `helm-org-headlines` to search for the string `link`, this headline doesn't match. I'm using the current development version of Emacs, the current version of Helm on MELPA, and a very recent development version of org-mode.

**Comment by thierryvolpiatto** [comment] 2015-04-02 04:51
Titus von der Malsburg <notifications@github.com> writes:

> I have a link in an org-headline:
>
> * This is the [[http://URL][link]].
>
> In org-mode, this headline displays as
>
> * This is the link.
>
> with link being blue and underlined.
>
> The problem is that when I use helm-org-headlines to search for the
> string link, this headline doesn't match. I'm using the current
> development version of Emacs, the current version of Helm on MELPA,
> and a very recent development version of org-mode.

I can't reproduce, just tried by adding an entry in one of my org files:
** Google this is the [[http://www.google.fr][link]].

when I type link this line is matched as expected, pressing RET go to
it.

Did I miss something ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tmalsburg** [comment] 2015-04-02 22:00
Ok, I found out that the issue is actually not related to links but to the length of the headline.  Some headlines are truncated in `helm-org-headlines` and when the search term occurs in the truncated part, it isn't matched.

Example:

    * Webseiten und Email accounts
    ** [[http://www.google.com][MyTrav]]

Is displayed completely in `helm-org-headlines`:

    * filename.org.gpg:/Webseiten and Emails accounts/[[http://www.google.com][MyTrav]]

However, the following

    * Webseiten und Email accounts
    ** [[http://www.google.com][MyTravel]]

is displayed as

    * filename.org.gpg:/Webseiten and Emails accounts/[[http://www.goog..

and when I search for *MyTravel* I don't get a match.

The weird thing is that some other headlines are way longer but they are not truncated.

**Comment by thierryvolpiatto** [comment] 2015-04-03 05:12
Titus von der Malsburg <notifications@github.com> writes:

> Ok, I found out that the issue is actually not related to links but to
> the length of the headline.

Right, this is a bug introduced by last PR on this file, will look into
this soon.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-07-12 10:21
The fix I did seems to work well for now, I am closing, feel free to reopen if needed.

Thanks.

**Closed by thierryvolpiatto** 2015-07-12 10:21 UTC
Labels: bug

**Comment by tmalsburg** [comment] 2015-12-14 20:33
`helm-org-headlines` was apparently removed in a recent update.  I switched to `helm-org-in-buffer-headings` but that seems to suffer from the problem described above.

Sidenote: `helm-org-headlines` is still referenced in helm-easymenu.el.  This should be fixed.

**Comment by tmalsburg** [comment] 2015-12-14 20:45
If I understand correctly, `helm-get-org-candidates-in-file` returns a list of candidates that are already truncated.  Wouldn't it be more natural to return untruncated candidates and to truncate them in the candidate transformer?
