### ISSUE TITLE
enable helm-source-findutils to pass options to find

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm#828] opened 2015-01-19 02:11 UTC
Hi,

helm-find is really great.  But sometimes I really miss a mean to pass additional args to the find binary - just like helm-locate. It would for example be quite cool if I could let helm only list files that are newer than one day etc.

Any idea what minibuffer "syntax" we could use for that purpose? Thanks.

**Comment by michael-heerdegen** [comment] 2015-01-19 05:49
Though, I think in any case we should keep the option to specify several name patterns in the minibuffer.

**Comment by thierryvolpiatto** [comment] 2015-01-20 16:24
`find` command is quite tricky to setup, we are actually doing this with `find-cmd` which is handy to do this, I have no ideas for now how to add extras args to the actual command without breaking it.

**Comment by michael-heerdegen** [comment] 2015-01-21 00:28
You can specify strings in the symbolic expression of a find-cmd call. They are then just copied to the result.  See the definition of find-to-string.

**Comment by thierryvolpiatto** [comment] 2015-01-21 15:50
Michael Heerdegen <notifications@github.com> writes:

> You can specify strings in the symbolic expression of a find-cmd
> call. They are then just copied to the result. See the definition of
> find-to-string.

I already read this when I wrote the actual code, this doesn't help
much...

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-01-22 01:59
Thierry Volpiatto <notifications@github.com> writes:

> I already read this when I wrote the actual code, this doesn't help
> much...

Why doesn't it help?  You're question was about adding additional
options that the user specifies in the minibuffer to our find-cmd call,
and I said, just integrate these strings as they are into the find-cmd
call we have.  That would work and not break anything.  Where's the
problem?

**Comment by michael-heerdegen** [comment] 2015-01-22 04:08
BTW, the findutils stuff currently doesn't use the prefix arg.   If we don't find a nice solution to let the user specify additional find options (such an approach is naturally limited in what can be expressed), we alternatively could define a new function that implements a generic helm interface to find.  It would be called when the user calls a findutils command with prefix arg.

**Comment by thierryvolpiatto** [comment] 2015-01-22 06:00
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> I already read this when I wrote the actual code, this doesn't help
>> much...
>
> Why doesn't it help?

The problem is to parse the command line and the new command line is
what you will have in pattern, so when adding extra args we have to
separate the new args from the pattern itself, e.g:
pattern: foo bar @ -ctime 2

(split-string pattern "@") => ("foo bar " " -ctime 2")

so the user will have to enter e.g "@" before entering new args.

and now we pass "foo*bar" and "-ctime 2" to find-cmd.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-01-22 06:44
Thierry Volpiatto <notifications@github.com> writes:

> (split-string pattern "@") => ("foo bar " " -ctime 2")

Yes, something like that.  Not fun to write, but doable.

**Comment by thierryvolpiatto** [comment] 2015-01-22 06:56
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> (split-string pattern "@") => ("foo bar " " -ctime 2")
>
> Yes, something like that. Not fun to write, but doable.

PR welcome.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-01-22 10:28
Thierry Volpiatto <notifications@github.com> writes:

> >> (split-string pattern "@") => ("foo bar " " -ctime 2")

> PR welcome.

Ok, will do.  Though, I would rather use a separator that is not
valid/useful as a shell pattern nor as a regexp, like "*".

**Comment by michael-heerdegen** [comment] 2015-01-22 12:46
I went with "*". Please see https://github.com/emacs-helm/helm/pull/836.

**Comment by thierryvolpiatto** [comment] 2015-01-22 13:54
Thanks for this, merged,
could you write a brief docstring on how to use find now, how to pass
args etc... I will make a special documentation string to use with C-c ?
then.  Just post it here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-01-22 14:15
Yip - tomorrow.

**Comment by michael-heerdegen** [comment] 2015-01-24 06:08
Here's a small fix: http://github.com/emacs-helm/helm/pull/839

Additional args should not be decisive for whether using case folding.  E.g. when the user specifies "-size +1M", the capital M should not trigger trigger turning on case fold.  Only globbing patterns should be decisive.

I give the flag a name different from case-fold-search, since the latter is a special variable, but we use the flag only to decide how to call find, so the name was misleading.

**Comment by michael-heerdegen** [comment] 2015-01-24 06:10
Typo: I meant "should not trigger turning OFF case fold".

**Comment by michael-heerdegen** [comment] 2015-01-24 06:35
Thierry Volpiatto <notifications@github.com> writes:

> could you write a brief docstring on how to use find now, how to pass
> args etc... I will make a special documentation string to use with C-c
> ?  then. Just post it here.

Ok, how about this (you may have to quote some quotation marks):

```
Recursively search files using "find".

Candidates are all filenames that match all given globbing patterns.
This respects the options `helm-case-fold-search' and
`helm-findutils-search-full-path'.

You can pass arbitrary options directly to find after a "*" separator.
For example, this would find all files matching "book" that are larger
than 1 megabyte:

    book * -size +1M

```

**Comment by thierryvolpiatto** [comment] 2015-01-25 16:51
Michael Heerdegen <notifications@github.com> writes:

> Ok, how about this (you may have to quote some quotation marks):

Great, will add it in the week, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Closed** 2015-02-01 08:56 UTC
Labels: enhancement
