### ISSUE TITLE
helm-semantic-or-imenu offers only function prototypes as candidates

### ISSUE THREAD

**Issue by gperaza** [emacs-helm/helm#1250] opened 2015-10-29 14:06 UTC
When attempting to narrow candidates inside helm-semantic-or-imenu for a function with prototype, only the prototype is offered as a candidate making it impossible to jump to the function definition. Both entries are available before input a matching pattern with the same name. This makes it troublesome to navigate buffers with many functions using imenu.
I believe the issue was addressed before in  https://github.com/emacs-helm/helm/issues/337 which is marked as closed, but I find the problem still exists.

**Comment by thierryvolpiatto** [comment] 2015-10-30 06:46
It was fixed indeed in #337 but for some (unknow) reason the duplicates have been forbidden.
They are reenabled now, hope that fix your problem.

Thanks.

**Comment by gperaza** [comment] 2015-11-03 17:40
Now both candidates appears, but each of them appears duplicated three times (total six candidates instead of two).
Despite that it is more useful this way.

**Comment by thierryvolpiatto** [comment] 2015-11-14 19:58
So I don't understand what the issue is, I will revert this change, please try to provide a complete recipe I can reproduce (with a sample file if possible).

Thanks.

**Comment by michael-heerdegen** [comment] 2015-11-15 06:05
I think he means that there are now real duplicates, i.e. the completion list displays more entries than there are actually matches in the buffer.  I guess that was the reason why duplicates had been turned off.

**Comment by thierryvolpiatto** [comment] 2015-11-15 15:39
As an example, when I am in helm.el and I use `helm-semantic-or-imenu`, I type "helm$" in prompt and I have two candidates:

types:helm
function:helm

so what's the problem here ?

**Comment by michael-heerdegen** [comment] 2015-11-16 09:34
@gperaza Can you provide an example file were it doesn't work?

**Comment by gperaza** [comment] 2015-11-19 23:29
Hello, sorry for the delay. 
@michael-heerdegen was right with the issue I was experiencing after the fix. But after trying to reproduce it on a different file everything  was working fine. So I guess my second problem is about something else. If you can reapply the fix I think we can close this issue.
Thanks.

**Comment by thierryvolpiatto** [comment] 2015-11-20 12:50
> If you can reapply the fix I think we can close this issue.

You mean that you don't have anymore duplicates with the fix  I sent and then reverted (:allow-dups) ?

**Comment by thierryvolpiatto** [comment] 2015-11-20 20:01
Sorry, but with `:allow-dups` I still have duplicates in emacs lisp files.
I still don't know what to do to reproduce your bug, a recipe with a sample file would be welcome.
Thanks.

**Closed** 2016-08-12 20:19 UTC
Labels: need_more_info, not_reproducible
