### ISSUE TITLE
helm-org-in-buffer-headings errors if buffer contains read-only parts

### ISSUE THREAD

**Issue by alphapapa** [emacs-helm/helm#1755] opened 2017-04-23 00:07 UTC
Hi Thierry,

After updating Helm recently, I've noticed that `helm-org-in-buffer-headings` now gives an error if parts of an Org buffer are marked read-only.  For example, I have used this code for several years to make subtrees read-only:

```el
;; http://kitchingroup.cheme.cmu.edu/blog/2014/09/13/Make-some-org-sections-read-only/

(defun org-mark-readonly ()
  (interactive)
  (org-map-entries
   (lambda ()
     (let* ((element (org-element-at-point))
            (begin (org-element-property :begin element))
            (end (org-element-property :end element)))
       (add-text-properties begin (- end 1) '(read-only t))))
   "read_only")
  (message "Made readonly!"))
(defun org-remove-readonly ()
  (interactive)
  (org-map-entries
   (lambda ()
     (let* ((element (org-element-at-point))
            (begin (org-element-property :begin element))
            (end (org-element-property :end element))
            (inhibit-read-only t))
       (remove-text-properties begin (- end 1) '(read-only t))))
   "read_only"))

(add-hook 'org-mode-hook 'org-mark-readonly)
```

Here's a test file:

```org
* Heading 1                                                       :read_only:
** Heading 2
* Heading 3
```

If you run `helm-org-in-buffer-headings` in that buffer, it works fine.  But if you then run `org-mark-readonly` and try to run `helm-org-in-buffer-headings` again, as soon as you type in the minibuffer, an error is shown: `Error running timer: (text-read-only)`.

I tried digging into this but wasn't able to figure it out with the time I had.

Thanks.

**Comment by thierryvolpiatto** [comment] 2017-04-23 05:26
alphapapa <notifications@github.com> writes:

> Hi Thierry,
>
> After updating Helm recently, I've noticed that
> helm-org-in-buffer-headings now gives an error if parts of an Org
> buffer are marked read-only. For example, I have used this code for
> several years to make subtrees read-only:

Should be fixed now, this was in recent code for mouse usage.
However, I understand we have such error when helm-allow-mouse is
enabled but it still strange that we have such (timer this time) error
when helm-allow-mouse is nil - i.e the offending code should not run -
and even more strange is that the error occur one time at first run, and
then doesn't appear anymore, I suspect an error somewhere in emacs (in
the way timers read code ?).

Anyway it is fixed, thanks for great recipe.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment] 2017-04-23 06:08
Thanks, Thierry, works great.  That was fast!  :)

**Comment by alphapapa** [comment] 2017-06-20 01:45
Hi Thierry,

Using helm and helm-core MELPA builds from June 19, I'm getting this bug again.

**Comment by thierryvolpiatto** [comment] 2017-06-20 05:19
alphapapa <notifications@github.com> writes:

> Hi Thierry,
>
> Using helm and helm-core MELPA builds from June 19, I'm getting this bug again.

I can't reproduce in master branch with the recipe you sent previously.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment] 2017-06-21 23:20
I've found that it only happens when `helm-org-headings-fontify` is non-nil.  e.g.:

```el
(let ((helm-org-headings-fontify t))
  (helm-org-in-buffer-headings))
```

**Comment by alphapapa** [comment] 2017-06-21 23:56
Seems to have been introduced in the set of changes merged in bc49f126d730c917d5d7870dbc56efc85e3a9b85.

**Comment by alphapapa** [comment] 2017-06-22 00:08
Sorry, I meant the changes merged in 6e47e1f1b690911a5f12ec02d9a353e1bc96b0d8, which is actually #1777.

(Sending this as a separate comment since I know Thierry reads via email, so I guess he won't see edited comments.)

**Comment by alphapapa** [comment] 2017-06-22 00:54
Ok, please disregard that.  Sorry, I've been having a hard time tracking this down because `emacs-helm.sh` hasn't been working properly (a separate bug I'll have to file).

I bisected, and it seems that the bad commit is actually 87188973d26dcd820d7247693a5adeacf3bd9047, but that seems strange to me since it's from April of last year.  I will do a bit more testing to confirm.

**Comment by alphapapa** [comment] 2017-06-22 01:17
Yes, strange as it seems, that is the bad commit.  This version of `helm-fuzzy-default-highlight-match` from the previous commit, https://github.com/emacs-helm/helm/commit/8985d2c630a57909c606ed413c15c25a3a9e0a69, works fine:

```el
(defun helm-fuzzy-default-highlight-match (candidate)
  "The default function to highlight matches in fuzzy matching.
It is meant to use with `filter-one-by-one' slot."
  (let* ((pair (and (consp candidate) candidate))
         (display (helm-stringify (if pair (car pair) candidate)))
         (real (cdr pair))
         (regex (helm--maybe-get-migemo-pattern helm-pattern))
         ;; FIXME This is called at each turn, cache it to optimize.
         (mp (helm-aif (helm-attr 'match-part (helm-get-current-source))
                 (funcall it display))))
    (with-temp-buffer
      (insert (propertize (or mp display) 'read-only nil)) ; Fix (#1176)
      (goto-char (point-min))
      (if (re-search-forward regex nil t)
          (add-text-properties
           (match-beginning 0) (match-end 0) '(face helm-match))
          (cl-loop with multi-match
                   with patterns = (if (string-match-p " " helm-pattern)
                                       (prog1 (split-string helm-pattern)
                                         (setq multi-match t))
                                       (split-string helm-pattern "" t))
                   for p in patterns
                   for re = (helm--maybe-get-migemo-pattern p)
                   do
                   (if multi-match
                       (progn
                         (while (re-search-forward re nil t)
                           (add-text-properties
                            (match-beginning 0) (match-end 0)
                            '(face helm-match)))
                         (goto-char (point-min)))
                     (when (re-search-forward re nil t)
                       (add-text-properties
                        (match-beginning 0) (match-end 0)
                        '(face helm-match))))))
      (setq display (if (and mp (string-match mp display))
                        (replace-match (buffer-string) t t display)
                      (buffer-string))))
    (if real (cons display real) display)))
```

But this version of the function, from https://github.com/emacs-helm/helm/commit/87188973d26dcd820d7247693a5adeacf3bd9047, gives the error:

```el
(defun helm-fuzzy-default-highlight-match (candidate)
  "The default function to highlight matches in fuzzy matching.
It is meant to use with `filter-one-by-one' slot."
  (if (string= helm-pattern "")
      candidate
    (let* ((pair (and (consp candidate) candidate))
           (display (helm-stringify (if pair (car pair) candidate)))
           (multi-match (string-match-p " " helm-pattern))
           (real (cdr pair))
           (regex (helm--maybe-get-migemo-pattern helm-pattern))
           ;; FIXME This is called at each turn, cache it to optimize.
           (mp (helm-aif (helm-attr 'match-part (helm-get-current-source))
                   (funcall it display)))
           (count 0))
      (with-temp-buffer
        (insert (propertize (or mp display) 'read-only nil)) ; Fix (#1176)
        (goto-char (point-min))
        (while (re-search-forward regex nil t)
          (cl-incf count)
          (add-text-properties
           (match-beginning 0) (match-end 0) '(face helm-match)))
        (when (zerop count)
          (cl-loop with patterns = (if multi-match
                                       (split-string helm-pattern)
                                     (split-string helm-pattern "" t))
                for p in patterns
                for re = (helm--maybe-get-migemo-pattern p)
                do
                (if multi-match
                    (progn
                      (while (re-search-forward re nil t)
                        (add-text-properties
                         (match-beginning 0) (match-end 0)
                         '(face helm-match)))
                      (goto-char (point-min)))
                  (when (re-search-forward re nil t)
                    (add-text-properties
                     (match-beginning 0) (match-end 0)
                     '(face helm-match))))))
        (setq display (if (and mp (string-match mp display))
                          (replace-match (buffer-string) t t display)
                        (buffer-string))))
      (if real (cons display real) display))))
```

**Comment by alphapapa** [comment] 2017-06-22 02:16
This commit (please ignore the first duplicate) seems to fix it, but I don't know that it's the right way to do so.

As best I can figure, the error is delayed, caused by the candidates which are inserted before any pattern is entered by the user.  When the user enters a pattern, a timer executes and tries to highlight the match parts, but the display parts which were already entered have the `read-only` property set because it is not removed when `helm-pattern` is empty.

**Comment by alphapapa** [comment] 2017-06-22 02:24
Changed it to `cl-typecase` instead of the more complicated `pcase`.

**Comment by alphapapa** [comment] 2017-06-22 02:31
Ok, that should be it.  Sorry for all the extraneous commits.  I have Emacs configured to cleanup whitespace and indenting on save, and then I accidentally staged hunks that were just the whitespace fixes.

On that note, there is a lot of incorrectly indented code in this file, and a lot of trailing whitespace.  Not that it really matters, but you might consider setting these to be fixed automatically on save by setting some dir-local variables.  That would help avoid whitespaces issues like this when commits are prepared by different people with different settings.

**Comment by thierryvolpiatto** [comment] 2017-06-22 04:10
alphapapa <notifications@github.com> writes:

> Ok, that should be it. Sorry for all the extraneous commits. I have
> Emacs configured to cleanup whitespace and indenting on save,

You should not do this, this is a bad idea, you should do this only in
separate commits when needed.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-06-22 04:29
alphapapa <notifications@github.com> writes:

> I've found that it only happens when helm-org-headings-fontify is non-nil. e.g.:
>
> (let ((helm-org-headings-fontify t))
>   (helm-org-in-buffer-headings))

I am also using helm-org-headings-fontify and I can't reproduce the bug.
I have followed your recipe using your function `org-mark-readonly`.

Please start by cloning a fresh master and installing from it, then make
a new recipe from ./emacs-helm.sh describing exactly what you are doing.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment] 2017-06-22 05:04
> You should not do this, this is a bad idea, you should do this only in separate commits when needed.

Yes, that is what I always do, stage only the relevant lines.  In one commit I accidentally staged a larger hunk than I intended, and I didn't notice because the whitespace parts were off the bottom of the screen.

> Please start by cloning a fresh master and installing from it, then make a new recipe from ./emacs-helm.sh describing exactly what you are doing.

I ran `git clean -dfx` before these tests, so the working tree was correct.  `emacs-helm.sh` isn't working; I filed as #1800.  I ran these tests by manually running these lines from `emacs-helm.sh` in `emacs -Q`:

```el
(progn
    (add-to-list 'load-path "~/.emacs.d/elpa/async-20170610.2241")
    (setq package-load-list '((helm-core t) (helm t) (async t) (popup t)))
    (package-initialize)
    (require 'helm-config)
    (helm-mode 1)
    (define-key global-map [remap dabbrev-expand] 'helm-dabbrev)
    (global-set-key (kbd "M-x") 'helm-M-x)
    (find-file "/tmp/test.org")
    (org-map-entries
     (lambda ()
       (let* ((element (org-element-at-point))
              (begin (org-element-property :begin element))
              (end (org-element-property :end element)))
         (add-text-properties begin (- end 1) '(read-only t))))
     "read_only")
    (let ((helm-org-headings-fontify t))
      (helm-org-in-buffer-headings)))
```

**Comment by alphapapa** [comment] 2017-06-22 18:19
Ok, I pulled the fix to `emacs-helm.sh` from master, and I can reproduce this bug like so:

1.  Save this to `/tmp/test.org`:
```org
* Heading 1                                                       :read_only:
** Heading 2
* Heading 3
```
2.  Run `emacs-helm.sh`.
3.  Eval this form:
```el
(progn
  (find-file "/tmp/test.org")
  (org-map-entries
   (lambda ()
     (let* ((element (org-element-at-point))
	    (begin (org-element-property :begin element))
	    (end (org-element-property :end element)))
       (add-text-properties begin (- end 1) '(read-only t))))
   "read_only")
  (let ((helm-org-headings-fontify t))
    (helm-org-in-buffer-headings)))
```
4.  Type any character in the minibuffer, and the error will appear.

**Comment by thierryvolpiatto** [comment] 2017-06-22 21:05
alphapapa <notifications@github.com> writes:

> Ok, I pulled the fix to emacs-helm.sh from master, and I can reproduce this bug like so:
>
>  1. Save this to /tmp/test.org:
>
> * Heading 1                                                       :read_only:
> ** Heading 2
> * Heading 3
>
>  2. Run emacs-helm.sh.
>  3. Eval this form:
>
> (progn
>   (find-file "/tmp/test.org")
>   (org-map-entries
>    (lambda ()
>      (let* ((element (org-element-at-point))
>             (begin (org-element-property :begin element))
>             (end (org-element-property :end element)))
>        (add-text-properties begin (- end 1) '(read-only t))))
>    "read_only")
>   (let ((helm-org-headings-fontify t))
>     (helm-org-in-buffer-headings)))
>
>  4. Type any character in the minibuffer, and the error will appear.

Thanks, could reproduce like this, I commited a fix which seems to work,
have a try.

Anyway there is a problem here with emacs-lisp itself, normally binding
inhibit-read-only on top of the offending code should suffice to fix the
problem, but apparently it is not sufficient.

Perhaps also org add special sticky properties somewhere ? Don't know...

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by alphapapa** [comment] 2017-06-22 21:37
Thanks.  I guess with this change, this line in `helm-fuzzy-default-highlight-match` is no longer necessary?

```el
 (insert (propertize (or mp display) 'read-only nil)) ; Fix (#1176)
```

> Anyway there is a problem here with emacs-lisp itself, normally binding
inhibit-read-only on top of the offending code should suffice to fix the
problem, but apparently it is not sufficient.

Yeah, that confused me too, because I tried adding that in several functions, but it didn't help.

> Perhaps also org add special sticky properties somewhere ? Don't know...

Me neither.  :)

The good news is that, although this seems like an obscure problem, other modes besides Org could have read-only text in them for one reason or another, and the way you did this fix should prevent the problem in all cases!  :)  (I think...)

**Comment by xiongtx** [comment] 2017-06-22 21:39
Doesn't `inhibit-read-only` only apply to `(current-buffer)`? Or am I missing something here?

**Comment by alphapapa** [comment] 2017-06-22 21:41
@xiongtx Not according to https://www.gnu.org/software/emacs/manual/html_node/elisp/Read-Only-Buffers.html, if I understand it correctly.  But I wouldn't be surprised if there are nuances (bugs?).

**Closed** 2017-06-22 21:42 UTC
