### ISSUE TITLE
`helm-find-files` not showing meaningful/useful results in some cases

### ISSUE THREAD

**Issue by abingham** [emacs-helm/helm#870] opened 2015-02-13 16:56 UTC
Depending on where my cursor is when I execute `helm-find-files`, the command sometimes seems to get a bit lost and start navigation in the root of my filesystem. For example, if I'm at the beginning of a typical HTML file:
```
<!doctype html>
^ point is here
```
and I run `helm-find-files`, instead of getting a window showing the files in that directory, I seem to start navigating at the root of my filesystem.

I initially asked about this [on stackexchange](http://emacs.stackexchange.com/questions/8205/why-does-helm-find-files-change-behavior-depending-on-my-current-location), and one commenter thought that helm just sometimes gets confused.

**Comment by PythonNut** [comment] 2015-02-13 17:53
Yes! This can also be a problem in helm commands with many sources, as the phantom insertions aren't async so it causes _all_ sources to catch up before helm becomes usable.

**Comment by michael-heerdegen** [comment] 2015-02-13 18:37
@abingham  I can reproduce the problem.

@thierryvolpiatto The problem seems to be that helm-find-files-initial-input receives the empty string as first arg (from ffap-guesser) in this case and it passes through the whole function so that it is finally returned.

**Comment by michael-heerdegen** [comment] 2015-02-13 18:39
@PythonNut I don't see any relation of your comment to the OPs problem.  What you say is probably true (have you reported this problem?) but I don't see a connection to this bug here.

**Comment by PythonNut** [comment] 2015-02-13 18:41
@michael-heerdegen Yes, sorry. I was following the SO thread which mentions that simply disabling the ffap functionality might help (but it can't currently be done). I wanted to add that I would really like this too, for other reasons.

Now that I'm reading the this issue, it seems that it's not quite what was under discussion on SO. Should I make a new issue?

**Comment by michael-heerdegen** [comment] 2015-02-13 18:47
Ok, no problem.

What's SO, btw?

**Comment by PythonNut** [comment] 2015-02-13 18:49
@michael-heerdegen bleck. It's a reference to StackOverflow, the most popular section of the StackExchange network, of which emacs.stackexchange is peer. I really should have said Emacs.SE.

**Comment by michael-heerdegen** [comment] 2015-02-13 18:54
And have the problems discussed there been raised here?  If not, can you give us a link to that discussions? Thanks.

**Comment by PythonNut** [comment] 2015-02-13 18:55
@michael-heerdegen there is a link to the question in the OP.

**Comment by michael-heerdegen** [comment] 2015-02-13 18:57
Ah, thanks, I'll have a look when i get the time.

**Comment by michael-heerdegen** [comment] 2015-02-13 19:06
But there is nothing about slowdowns in this thread. Can you elaborate what problems you experience involving slowdowns?

FWIW the helm user group is probably a better forum for such questions. Maybe raise your issue there. Or create an issue here if it is reproducible with the initial setup.

**Comment by thierryvolpiatto** [comment] 2015-02-13 19:30
Michael Heerdegen <notifications@github.com> writes:

> @abingham I can reproduce the problem.
>
> @thierryvolpiatto The problem seems to be that
> helm-find-files-initial-input receives the empty string as first arg
> (from ffap-guesser) in this case and it passes through the whole
> function so that it is finally returned.

The problem is that ffap is becoming more silly at each new emacs
release, we have to get rid of it for most cases except url's and mails.
But actually if I remove all others uses, we loose completion in
filenames which is useful.
I will work on this ASAP, not an urgency though, even if it is annoying
sometimes.
 

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by PythonNut** [comment] 2015-02-13 19:42
@michael-heerdegen I'm pretty sure the slowdowns are unavoidable. On that page, @abingham asks this:
> Is there any way to turn this behavior off, or is it baked in? I've tried changing e.g. helm-ff-url-regexp but with no noticeable results.

Slowdowns are another _reason_ the option to disable ffap would be useful.

**Comment by michael-heerdegen** [comment] 2015-02-13 19:42
Thierry Volpiatto <notifications@github.com> writes:

> Michael Heerdegen <notifications@github.com> writes:
>
> > @abingham I can reproduce the problem.
> >
> > @thierryvolpiatto The problem seems to be that
> > helm-find-files-initial-input receives the empty string as first arg
> > (from ffap-guesser) in this case and it passes through the whole
> > function so that it is finally returned.
>
> The problem is that ffap is becoming more silly at each new emacs

Probably.  FWIW, it treats the "<" as a shell prompt - see
ffap-shell-prompt-regexp.  Though, sure, it's not very intelligent to
derive the empty string as file name from that.

**Comment by michael-heerdegen** [comment] 2015-02-13 19:49
PythonNut <notifications@github.com> writes:

> Slowdowns are another reason the option to disable ffap would be
> useful.

I don't see why slowdowns would be necessary, given the functionality we
offer.  In which cases do you experience slowdowns?  Do you have a
recipe?

**Comment by thierryvolpiatto** [comment] 2015-02-15 16:13
>Yes! This can also be a problem in helm commands with many sources, as the phantom insertions >aren't async so it forces all sources to catch up before helm becomes usable, which can lead to >massive, nondeterministic slowdowns depending on the position of the point.

@PythonNut ffap is not used in any multi sources e.g helm-for-files,

**Comment by PythonNut** [comment] 2015-02-15 21:51
@thierryvolpiatto it is used when you roll it yourself with `(helm :source '(...))`, as I do.

**Comment by michael-heerdegen** [comment] 2015-02-24 01:02
If we don't have a recipe for any further problems, I guess this can be closed.

**Comment by PythonNut** [comment] 2015-02-24 03:02
Sorry! I've been super busy with school. Here's a trimmed down snippet from [my config](https://github.com/PythonNut/emacs-config/blob/dev/modules/config-helm.el#L127).

If you try it out, you will notice that it does pick up the current symbol under the cursor. This may not be slow for you (this computer is incredibly slow), but it can be for me.

**Comment by michael-heerdegen** [comment] 2015-02-24 03:27
Thanks!

Mmh, I'm not sure if that is really the cause for the slow down - or if it is just a consequence.  But yes, the slowdown is annoying.

You might want to use the built in profiler to find out what causes the slowdown (I mean the super-duper-trivial-to-use profiler.el). But AFAIK, Thierry hates what you do (using that many sources in one session, even including async ones), so he'll probably be not that enthusiastic to invest time unless it is a reproducible problem under different (intended) circumstances.

**Comment by michael-heerdegen** [comment] 2015-02-24 03:30
No problem if you are busy ATM of course.

**Comment by PythonNut** [comment] 2015-02-24 03:46
@michael-heerdegen 

> You might want to use the built in profiler to find out what causes the slowdown

I tried that a while ago. It led to [this](http://emacs.stackexchange.com/questions/7344/make-profiler-report-columns-wider).

> But AFAIK, Thierry hates what you do \[that\] (using that many sources in one session, even including async ones)

I suppose this amounts to a difference in philosophy. I've been slowly sharpening this function for a long time, and it works _beautifully_. I absolutely love and adore it and would not switch to any other editor because of this single function. Casting a wide net lowers my cognitive load to the point where you can mash <kbd>C-c</kbd> <kbd>C-o</kbd> type _anything_ and `helm` will automagically transport you where you want to go.

**Comment by michael-heerdegen** [comment] 2015-02-24 04:16
PythonNut <notifications@github.com> writes:

> I tried that a while ago. It led to this.

I see.  Try this:

```
(setq profiler-report-cpu-line-format
      '((70 left)
        (24 right ((19 right)
                   (5 right)))))
```

If you don't care about aligned columns, this does also work:

```
(setq buffer-invisibility-spec '(t))
```

since lines are truncated by making the end invisible.

> I suppose this amounts to a difference in philosophy. I've been slowly
> sharpening this function for a long time, and it works beautifully. I
> absolutely love and adore it and would not switch to any other editor
> because of this single function. Casting a wide net lowers my
> cognitive load to the point where you can mash C-c C-o type anything
> and helm will automagically transport you where you want to go.

We are all different.  I also don't share the opinion of Thierry, but I
respect that he must set priorities.  BTW, what you do seems to be quite
popular, I guess every second helm uses something similar.

**Comment by thierryvolpiatto** [comment] 2015-02-24 05:58
PythonNut <notifications@github.com> writes:

> @michael-heerdegen
>
>     You might want to use the built in profiler to find out what causes the slowdown
>    
> I tried that a while ago. It led to this.

This is unrelated to helm-find-files and the initial problem reported
here.

You are also using different packages that are not in helm (helm-ag
etc...), and it is not a question of philosophy, it is mechanical, if
you put all the sources you find in one command expect slowdown.
I can do nothing for you, sorry.

Please close this bugreport.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Closed** 2015-02-27 08:00 UTC
