### ISSUE TITLE
Enabling `flyspell-mode` in a Helm completion buffer breaks "complete as I type".

### ISSUE THREAD

**Issue by ntc2** [emacs-helm/helm#1761] opened 2017-04-30 03:54 UTC
## Expected behavior

Helm completes as I type after `C-x C-f`, `C-h v`, etc.

## Actual behavior from `emacs-helm.sh` if possible (See note at bottom)

I have reproduced this in `emacs-helm.sh`; see below.

If `flyspell-mode` is enabled for all modes, then Helm completion only works correctly the *first* time you start a Helm completion buffer in a new Emacs. Each time after that when you start a Helm completion buffer, the completions are delayed a *long* time (perhaps 10 seconds!). Entering `<space>` still updates the completion list automatically, but this workaround does not help e.g. with fuzzy completion, since that's disabled after first space.

Note: I believe that enabling `flyspell-mode` in the Helm completion buffers is probably a stupid thing to do, as it serves no purpose. However, the breakage is subtle and was hard to debug -- I had to bisect my Emacs config until I'd identified the probablematic settings. I'm not sure this should be addressed in Helm in any way, so you might want to just close this issue. But at least other people experiencing this problem might be able to Google this issue now and realize what's going on.

## Steps to reproduce (recipe)

Run `emacs-helm.sh` and then do
```
M-: (add-hook 'font-lock-mode-hook (lambda () (flyspell-mode 1))) RET
```
now try `C-x C-f` and enter some non-space characters: note that it takes about 10 seconds for the completion list to update.

## Describe versions of helm, emacs, operating system etc.

Helm helm-20170428.1125 from ELPA.
Emacs 24.5.1.
Ubuntu 16.04 x86_64.

**Comment by thierryvolpiatto** [comment] 2017-04-30 05:23
Nathan Collins <notifications@github.com> writes:

> Expected behavior
>
> Helm completes as I type after C-x C-f, C-h v, etc.
>
> Actual behavior from emacs-helm.sh if possible (See note at bottom)
>
> I have reproduced this in emacs-helm.sh; see below.
>
> If flyspell-mode is enabled for all modes, then Helm completion only
> works correctly the first time you start a Helm completion buffer in a
> new Emacs. Each time after that when you start a Helm completion
> buffer, the completions are delayed a long time (perhaps 10
> seconds!). Entering <space> still updates the completion list
> automatically, but this workaround does not help e.g. with fuzzy
> completion, since that's disabled after first space.

flycheck-mode should be disabled in helm, see flycheck-global-modes.
helm have a mode-class property "special".
Did you have modified this variable ?

> Note: I believe that enabling flyspell-mode in the Helm completion
> buffers is probably a stupid thing to do, as it serves no
> purpose. However, the breakage is subtle and was hard to debug -- I
> had to bisect my Emacs config until I'd identified the probablematic
> settings. I'm not sure this should be addressed in Helm in any way,

If helm-major-mode is not anymore setting its mode-class properly for
some reasons, yes this bug should be addressed here.

--
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by thierryvolpiatto** [comment] 2017-04-30 05:35
Nathan Collins <notifications@github.com> writes:

> Run emacs-helm.sh and then do
>
> M-: (add-hook 'font-lock-mode-hook (lambda () (flyspell-mode 1))) RET

Huh! What is this ? 
Why are you enabling flyspell like this ?!
I guess that with flyspell running in this mode you force its usage
everywhere.


You have global-flycheck-mode to enable flycheck everywhere, with it
enabled here, I can't reproduce your bug, it seems flycheck is correctly
detecting the helm mode-class and doesn't kick in in helm buffer.
And yes the mode-class is set in helm-major-mode:
    (get 'helm-major-mode 'mode-class) => special.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by ntc2** [comment] 2017-04-30 19:38
On Sat, Apr 29, 2017 at 10:35 PM, Thierry Volpiatto <
notifications@github.com> wrote:

>
> Nathan Collins <notifications@github.com> writes:
>
> > Run emacs-helm.sh and then do
> >
> > M-: (add-hook 'font-lock-mode-hook (lambda () (flyspell-mode 1))) RET
>
> Huh! What is this ?
> Why are you enabling flyspell like this ?!
> I guess that with flyspell running in this mode you force its usage
> everywhere.
>

In the past  -- several years ago -- I found that if I tried to turn on
`flyspell-prog-mode` after `flyspell-mode` had been enabled that I had
problems, so in my Emacs config I hardcoded a list of modes to use
`flyspell-prog-mode` in and the turned on `flyspell-mode` in all other
modes. The above is a simplified version of that (since Helm was not in the
`flyspell-prog-mode` modes, it's equivalent here).

However, this is probably The Wrong Way for me to be using `flyspell-mode`
...



> You have global-flycheck-mode to enable flycheck everywhere, with it
> enabled here, I can't reproduce your bug, it seems flycheck is correctly
> detecting the helm mode-class and doesn't kick in in helm buffer.
> And yes the mode-class is set in helm-major-mode:
> (get 'helm-major-mode 'mode-class) => special.
>

You keep saying `fly*check*`. Note that the problematic mode is
`fly*spell*` mode. Are they related?

**Comment by thierryvolpiatto** [comment] 2017-04-30 20:12
Nathan Collins <notifications@github.com> writes:


> However, this is probably The Wrong Way for me to be using `flyspell-mode`

Yes adding it to font-lock-mode-hook is not a good idea IMO and I can't
do something on the helm side to prevent this.

> You keep saying `fly*check*`. Note that the problematic mode is
> `fly*spell*` mode. Are they related?

Absolutely not! It's just a mistake, I confuse flyspell and flycheck in
my head!

Sorry.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by ntc2** [comment] 2017-05-01 01:07
On Sun, Apr 30, 2017 at 1:12 PM, Thierry Volpiatto <notifications@github.com
> wrote:

>
> Nathan Collins <notifications@github.com> writes:
>
>
> > However, this is probably The Wrong Way for me to be using
> `flyspell-mode`
>
> Yes adding it to font-lock-mode-hook is not a good idea IMO and I can't
> do something on the helm side to prevent this.


Sounds fair to me. So how about you close this issue and I'll just come up
with a less crazy `flyspell` configuration :) If someone else has the same
crazy configuration and problem as me they still might find the closed the
issue via Google and solve which will help with debugging, which was the
hard part for me here (`flyspell` breaking Helm was not intuitive to me,
and I wouldn't be surprised if it's messing up other modes where spelling
correction makes no sense).

Thanks for maintaining Helm, it's great!

**Comment by thierryvolpiatto** [comment] 2017-05-01 04:25
Nathan Collins <notifications@github.com> writes:

> Sounds fair to me. So how about you close this issue and I'll just come up
> with a less crazy `flyspell` configuration :)

Ok so closing now. Thanks.

> If someone else has the same crazy configuration and problem as me
> they still might find the closed the issue via Google and solve which
> will help with debugging, which was the hard part for me here
> (`flyspell` breaking Helm was not intuitive to me, and I wouldn't be
> surprised if it's messing up other modes where spelling correction
> makes no sense).

Yes me too, my advice is to not enable it globally but only in the
needed places, when it is the case in whole buffer, just use the mode
hook, otherwise when it is needed in only some parts of buffers it is
more complicated but possible, I actually use auto-fill-mode in only
comments and docstring in source code, I could easily add flyspell if
needed, see https://github.com/thierryvolpiatto/emacs-tv-config/blob/master/.emacs.el#L1757 
HTH.

> Thanks for maintaining Helm, it's great!

Thanks for using helm.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Closed** 2017-05-01 04:50 UTC
