### ISSUE TITLE
Rename files issue

### ISSUE THREAD

**Issue by tomhk215** [emacs-helm/helm#1333] opened 2016-01-12 08:19 UTC
Under `helm-find-files`, the rename function is not working as expected.

If more than one files are selected, `helm-ff-run-rename-file` just ask for new file name once. It tries to rename all selected files to that name.  As a result, all files are overwritten until the last one.

And serial rename files is not working also.

**Comment by thierryvolpiatto** [comment] 2016-01-12 08:51
tomhk215 <notifications@github.com> writes:

> Under helm-find-files, the rename function is not working as expected
>
> If more than one files are selected, helm-ff-run-rename-file just ask
> for new file name for one time It tries to rename all selected files
> to that name As a result, all files are overwritten until the last one

Not reproductible, works fine here.

> And serial rename files is not working also

And works fine too here.

Please try to use ./emacs-helm.sh first before sending bugreports.

-- 
Thierry

**Comment by tomhk215** [comment] 2016-01-12 10:33
This is a gif for renaming by `helm-ff-run-rename-file`
![out](https://cloud.githubusercontent.com/assets/16475673/12261234/be3c7d1e-b95a-11e5-84cd-f130fd00d8a6.gif)

The serial rename is fine under emacs-helm.sh.
Thanks

**Comment by thierryvolpiatto** [comment] 2016-01-12 11:05
tomhk215 <notifications@github.com> writes:

> This is a gif for renaming by helm-ff-run-rename-file
> out     

You can't rename more than one file to a target which is not a
directory.
Helm was not raising an error when doing so, it does now.
 
-- 
Thierry

**Comment by tomhk215** [comment] 2016-01-12 11:12
Thanks.
Sorry, I am not trying to create troubles.
I am just trying different functions of your awesome package. XD

**Comment by thierryvolpiatto** [comment] 2016-01-12 11:37
tomhk215 <notifications@github.com> writes:


> Sorry, I am not trying to create troubles.

I know, you are welcome to send bugs reports, this last one was useful,
raising an error here was indeed missing.

Thanks ;-)

> I am just trying different functions of your awesome package. XD

Thanks to use helm.

PS: Don't forget to use ./emacs-helm.sh to reproduce your bugs to be
sure it is really a helm bug and not a bug coming from another package
or your config file.

Also once you see your bug is fixed you can close it.

Thanks.

-- 
Thierry

**Closed** 2016-01-12 11:51 UTC
