### ISSUE TITLE
helm completion errors out for magit-submodule-add

### ISSUE THREAD

**Issue by vkz** [emacs-helm/helm#1933] opened 2017-12-18 13:58 UTC
Go to git repo with submodules.
M-x magit-submodule-add
paste URL for sobmodule e.g. https://github.com/tpope/vim-repeat.git

## Expected behavior

Correctly add URL string and proceed to the next step - specifying local path for submodule.

Note that without Helm `magit-submodule-add` works fine.

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

helm errors out reporting `(wrong-type-argument stringp nil)`

## Steps to reproduce (recipe)
Use minimal `init.el` with only magit and helm installed:

```elisp
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(unless (file-exists-p (concat user-emacs-directory "elpa/archives/melpa"))
  (package-refresh-contents))

(defvar required-packages
  '(exec-path-from-shell
    interaction-log
    magit
    helm))

(let ((install #'(lambda (package)
                   (unless (package-installed-p package)
                     (package-install package))
                   (require package))))
  (message "Installing required packages %s" required-packages)
  (mapc install required-packages)
  (delete-other-windows))

(exec-path-from-shell-initialize)

(require 'magit)
(require 'helm)
(require 'helm-config)
(helm-mode 1)

(require 'interaction-log)
(interaction-log-mode +1)
(split-window-right)
```
## Backtraces if any (`M-x toggle-debug-on-error`)

Sorry, had to trim the report, cause github can't handle its size.

```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-as-directory(nil)
  helm-comp-read-get-candidates(read-file-name-internal file-directory-p nil nil "")
  #()
  #()
  apply
  helm-funcall-with-source
  helm-funcall-foreach(init)
  helm-initial-setup("~/.config/vim-repeat")
  helm-initialize
  helm-internal
  apply(helm-internal ((((must-match) (name . "magit-submodule-add") )) ))
  helm((((must-match) (name . "magit-submodule-add"))))
  apply(helm (()))
  helm(:sources (((must-match) (name . "magit-submodule-add")  )) :input "~/.config/vim-repeat" :default "~/.config/vim-repeat" :preselect nil :prompt "Add submodules at path: " :resume noresume :allow-nest nil :candidate-number-limit 100 :case-fold-search smart :history file-name-history :buffer "*helm-mode-magit-submodule-add*")
  helm-comp-read("Add submodules at path: " read-file-name-internal :test file-directory-p :history file-name-history :reverse-history t :input-history file-name-history :must-match nil :alistp nil :help-message helm-comp-read-help-message :name "magit-submodule-add" :requires-pattern 0 :candidates-in-buffer t :exec-when-only-one nil :fuzzy nil :buffer "*helm-mode-magit-submodule-add*" :default "~/.config/vim-repeat" :initial-input "~/.config/vim-repeat")
  helm-completing-read-default-1("Add submodules at path: " read-file-name-internal file-directory-p nil ("~/.config/vim-repeat" . 10) file-name-history "~/.config/vim-repeat" nil "magit-submodule-add" "*helm-mode-magit-submodule-add*" t)
  helm-completing-read-default-handler("Add submodules at path: " read-file-name-internal file-directory-p nil ("~/.config/vim-repeat" . 10) file-name-history "~/.config/vim-repeat" nil "magit-submodule-add" "*helm-mode-magit-submodule-add*")
  helm--completing-read-default("Add submodules at path: " read-file-name-internal file-directory-p nil ("~/.config/vim-repeat" . 10) file-name-history "~/.config/vim-repeat" nil)
  apply(helm--completing-read-default ("Add submodules at path: " read-file-name-internal file-directory-p nil ("~/.config/vim-repeat" . 10) file-name-history "~/.config/vim-repeat" nil))
  #[128 "\300\301\"\207" [apply helm--completing-read-default completing-read-default nil] 4 nil]("Add submodules at path: " read-file-name-internal file-directory-p nil ("~/.config/vim-repeat" . 10) file-name-history "~/.config/vim-repeat" nil)
  completing-read("Add submodules at path: " read-file-name-internal file-directory-p nil ("~/.config/vim-repeat" . 10) file-name-history "~/.config/vim-repeat")
  read-file-name-default("Add submodules at path: " "/Users/user/.config/" "/Users/user/.config/vim-repeat" nil "vim-repeat" file-directory-p)
  read-file-name("Add submodules at path: " "/Users/user/.config/" "/Users/user/.config/vim-repeat" nil "vim-repeat" file-directory-p)
  read-directory-name("Add submodules at path: " nil nil nil "vim-repeat")
  byte-code("\302 \211\2033\211\303\304!\305\306\307\310\311\312\211\211\313\314	\"\205!\315\316	\"%!!)\306!\317!E\266\202)\2025\320 \207" [default-directory read-file-name-function magit-toplevel magit-read-string-ns "Add submodule (remote url)" read-file-name-default directory-file-name file-relative-name read-directory-name "Add submodules at path: " nil string-match "\\([^./]+\\)\\(\\.git\\)?$" match-string 1 magit-submodule-read-name-for-path magit--not-inside-repository-error] 12)
  call-interactively(magit-submodule-add)
  magit-invoke-popup-action(97)
  funcall-interactively(magit-invoke-popup-action 97)
  call-interactively(magit-invoke-popup-action nil nil)
  command-execute(magit-invoke-popup-action)
```

## Describe versions of Helm, Emacs, operating system, etc.

GNU Emacs 25.3.1 (x86_64-apple-darwin17.2.0, NS appkit-1561.10 Version 10.13.1 (Build 17B48)) of 2017-11-12

```
  drwxr-xr-x  12 russki  staff   384 Dec 18 13:39 async-20171015.2239
  drwxr-xr-x   6 russki  staff   192 Dec 18 13:39 dash-20171028.854
  drwxr-xr-x   6 russki  staff   192 Dec 18 13:39 exec-path-from-shell-20170508.4
  drwxr-xr-x   8 russki  staff   256 Dec 18 13:39 ghub-20171217.1309
  drwxr-xr-x   6 russki  staff   192 Dec 18 13:39 git-commit-20171214.929
  drwxr-xr-x  79 russki  staff  2528 Dec 18 13:39 helm-20171206.2200
  drwxr-xr-x  12 russki  staff   384 Dec 18 13:39 helm-core-20171130.2340
  drwxr-xr-x   6 russki  staff   192 Dec 18 13:39 interaction-log-20160305.501
  drwxr-xr-x   6 russki  staff   192 Dec 18 13:39 let-alist-1.0.5
  drwxr-xr-x  80 russki  staff  2560 Dec 18 13:39 magit-20171217.1409
  drwxr-xr-x   8 russki  staff   256 Dec 18 13:39 magit-popup-20171217.1235
  drwxr-xr-x   6 russki  staff   192 Dec 18 13:39 popup-20160709.729
  drwxr-xr-x   8 russki  staff   256 Dec 18 13:39 with-editor-20171217.1239
```
## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

no

## IMPORTANT NOTE

Helm provides a script named `emacs-helm.sh` which runs Helm in a neutral
environment: no other packages and only minimal settings.

When possible, use it to reproduce your Helm issue to ensure no other package is
interfering.

To run it, simply switch to the directory where Helm is installed and call `./emacs-helm.sh`.

Thanks.

**Comment by vkz** [comment] 2017-12-18 16:59
I stepped through with edebug. Looks like the error occurs after `helm-basedir` which is passed an empty string [here](https://github.com/emacs-helm/helm/blob/master/helm-mode.el#L271), which helm-basedir doesn't handle - it returns `nil` - and that is passed to `file-name-as-directory` which blows up. Whether this should never be the case I don't know, but that's what magit passes it. Could be an edge case to handle gracefully?

Here's the trace that might help:
```
{ read-file-name-default args: (Add submodules at path:  ~/ /Users/russki/vim-repeat nil vim-repeat file-directory-p)
:{ helm-comp-read-get-candidates args: (read-file-name-internal file-directory-p nil nil )
```

**Comment by thierryvolpiatto** [comment] 2017-12-19 05:06
Ok, I could reproduce with this snippet extracted from `magit-submodule-add`:

```
(let* ((url (magit-read-string-ns "Add submodule (remote url)"))
            (path (let ((read-file-name-function #'read-file-name-default))
                    (directory-file-name
                     (file-relative-name
                      (read-directory-name
                       "Add submodules at path: " nil nil nil
                       (and (string-match "\\([^./]+\\)\\(\\.git\\)?$" url)
                            (match-string 1 url))))))))
       (list url
             (directory-file-name path)
             (magit-submodule-read-name-for-path path)))
```
It should be fixed now, however the `read-directory-name` will not work as expected because the `read-file-name-function` have been let-bounded with `read-file-name-default` which defeat helm completion, I wonder why @tarsius is doing this.

**Comment by tarsius** [comment] 2017-12-19 13:14
No need to wonder - just ask `M-x magit-blame`.

> 47eb9bec8735885a63e34d11f03a1445e307c44b contains: Force the use of `read-file-name-default` because `ido-read-file-name` behaves strangely (the users choice is ignored the first time and s/he is prompted again, this time with a different initial input).

I have now limited that kludge to only affect Ido.

**Comment by vkz** [comment] 2017-12-19 13:37
ok, thank you both!  I guess its time to try [borg](https://github.com/emacscollective/borg/blob/master/README.md) and sync up with your latest and greatest

**Comment by thierryvolpiatto** [comment] 2017-12-20 06:17
Jonas Bernoulli <notifications@github.com> writes:

> No need to wonder - just ask M-x magit-blame.

Of course! Didn't think at it for this.
    
> I have now limited that kludge to only affect Ido.

Great thanks.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2017-12-20 06:49
Thanks to both, closing now.

**Closed by thierryvolpiatto** 2017-12-20 06:49 UTC
