### ISSUE TITLE
helm-org-in-buffer-headings problems with large file

### ISSUE THREAD

**Issue by dfeich** [emacs-helm/helm#1567] opened 2016-07-17 20:26 UTC
I have a large org mode tasks file which is the main component of my agenda that has >1000 headings. Apart from this I have two other smaller files that are part of the agenda. helm-org-in-buffer-headings sometimes just does not work, i.e. the candidates list in the helm window stays empty. Sometimes when I type something and erase by CTRL-K, the candidates appear. But other times it just does not work. This never seems to happen with smaller files.

Since helm is the greatest way for me to navigate my agenda, this really affects my workflow. Can this be addressed by some configuration setting?

Thanks,
Derek

**Comment by thierryvolpiatto** [comment] 2016-07-17 20:54
Derek <notifications@github.com> writes:

> I have a large org mode tasks file which is the main component of my
> agenda that has >1000 headings. Apart from this I have two other
> smaller files that are part of the agenda. helm-org-in-buffer-headings
> sometimes just does not work, i.e. the candidates list in the helm
> window stays empty. Sometimes when I type something and erase by
> CTRL-K, the candidates appear. But other times it just does not
> work. This never seems to appear with smaller files.
>
> Since helm is the greatest way for me to navigate my agenda, this
> really affects my workflow. Can this be addressed by some
> configuration setting?

Are you using default settings ?
Did you try from ./emacs-helm.sh ?

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-07-18 03:22
Derek <notifications@github.com> writes:

> I have a large org mode tasks file which is the main component of my
> agenda that has >1000 headings.

Here helm-org-agenda-files-headings popup with 1188 headings instantly,
one of the file is 17000+ lines.
Your problem maybe related to org itself because you have a particular
heading that slowdown display.
One related problem maybe also bidi which depending context (special
headings, emacs version, locale etc...) you can turn it off to see if it
changes something: (setq-default bidi-display-reordering nil)

> Apart from this I have two other smaller files that are part of the
> agenda. helm-org-in-buffer-headings sometimes just does not work,
> i.e. the candidates list in the helm window stays empty.

Perhaps try to split your file in small files to see which part of the
file is causing the slowdown.
i.e I think it is a slowdown, not sure though, you can verify by waiting
if helm popup after some time.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-07-24 06:45
No news on this and not reproductible, closing.

**Closed by thierryvolpiatto** 2016-07-24 06:45 UTC

**Comment by dfeich** [comment] 2018-06-27 09:42
I was never fully able to bisect my immense file systematically and hunt down the problem. But I can report that when I chaned to emacs 26.1 the behavior went away... could also be that a helm-update at that time did it, but I suspect that it was emacs 26.1. I had seen before that gc seemed to have some influence on it, but not very systematically. For me, this is now completely fixed.

Best
Derek
