### ISSUE TITLE
Keyboard input while helm-imenu is being autoloaded breaks the result

### ISSUE THREAD

**Issue by dgutov** [emacs-helm/helm#841] opened 2015-01-26 18:55 UTC
1. Install Helm as a package, don't do any additonal setup.

2. Open some Emacs Lisp file with several function definitions.

3. Type `M-x helm-imenu`, don't wait for the interface to show up, type the first letter of the input.

4. See the empty list.

Repeated `M-x helm-imenu` invocations show the empty list as well. Only if after I make a buffer modification, `M-x helm-imenu` will show the right results.

**Comment by michael-heerdegen** [comment] 2015-01-27 12:58
Confirmed.  Good catch!

**Comment by michael-heerdegen** [comment] 2015-01-27 13:02
Maybe this small change: https://github.com/emacs-helm/helm/pull/843 is already sufficient?

**Comment by michael-heerdegen** [comment] 2015-01-27 13:18
BTW, what do I do wrong with my pull requests so that they don't automatically appear in the issue's thread?  I thought "fixes #issue" in the commit message would do that, but obviously not.  How do you do it?

**Comment by dgutov** [comment] 2015-01-27 13:36
> Maybe this small change: #843 is already sufficient?

Looks like it is, thanks! I don't understand how/why, though.

> what do I do wrong with my pull requests so that they don't automatically appear in the issue's thread

Maybe you should put the reference into the pull request description, instead of the title? Not sure.

> I thought "fixes #issue" in the commit message would do that

You forgot the hash char in that commit message.

**Comment by michael-heerdegen** [comment] 2015-01-27 14:30
Dmitry Gutov <notifications@github.com> writes:

>     Maybe this small change: #843 is already sufficient?
>
> Looks like it is, thanks! I don't understand how/why, though.

It was not an autoload thing.

We wrap candidate collection stuff in `while-no-input' to be able to
abort when new input arrives.

For helm-imenu, there is a flag remembering the buffer modification tick
from the last call; it starts with nil.  From the flag's value we derive
whether we must rebuild the imenu cache.

The problem was that we updated that flag before building the cache.
When input arrived before that stuff had been finished, the flag told
helm that the initialization had successfully finished and the cache is
up-to-date, which is an error.

My patch just changed the code to set the flag after the cache
calculation.  When we jump out of that code, the flag is not set.

> You forgot the hash char in that commit message.

Oh, thanks, that could have been the problem.

**Comment by dgutov** [comment] 2015-01-27 14:44
> For helm-imenu, there is a flag remembering the buffer modification tick
from the last call; it starts with nil.  From the flag's value we derive
whether we must rebuild the imenu cache.

That explains why the subsequent `helm-imenu` invocations succeed (which was also a problem). But since the first one was interrupted, shouldn't it abort and show the empty list? Or does Helm try again, in a loop?

**Comment by michael-heerdegen** [comment] 2015-01-27 15:47
Dmitry Gutov <notifications@github.com> writes:

> That explains why the subsequent helm-imenu invocations succeed (which
> was also a problem). But since the first one was interrupted,
> shouldn't it abort and show the empty list? Or does Helm try again, in
> a loop?

I also wondered why my patch also works for the first invocation to be
honest.

OTOH, when my patch would not fix also the first invocation, we would
have (had) a problem in lots of other sources as well.

Looking at the code, it seems that the candidates slot is indeed
(re)evaluated for every update.  But I'm not sure about this part.

**Comment by tuhdo** [comment] 2015-01-27 16:34
It is better not to generate candidates in `:candidates` slot. I had that problem with `helm-semantic` before, where I tried the same thing. When you assign to `:candidates` slot, the candidates should all be ready to be display because at this point a Helm buffer and window is created. If candidates are not ready by the time window is display, you get an empty Helm buffer. See this PR that fixed this issue: https://github.com/emacs-helm/helm/pull/671

It is also the time to update `helm-source-imenu` to use the function `helm-build-sync-source` to build a source instead of `defvar`. This is advisable way to create a source.

**Closed** 2015-01-27 18:27 UTC

**Comment by michael-heerdegen** [comment] 2015-01-28 10:32
Tu Do <notifications@github.com> writes:

> It is better not to generate candidates in :candidates slot. I had
> that problem with helm-semantic before, where I tried the same thing.
> When you assign to :candidates slot, the candidates should all be
> ready to be display because at this point a Helm buffer and window is
> created.

Why?

> If candidates are not ready by the time window is display, you get an
> empty Helm buffer.

In which case?  I don't see that happen with my patch.  I'm also not
able to provoke the problem you describe with an example:

```
(defun helm-test-candidates ()
  (let ((cands (mapcar #'prin1-to-string
                       (number-sequence 1 25))))
    (cl-dolist (i (number-sequence 1 1000000))
      (* i i)) ;make Emacs busy for a while
    (cl-callf2 nconc
        (mapcar #'prin1-to-string (number-sequence 26 40))
        cands)
    cands))

(defclass helm-test-source (helm-source-sync)
  ((candidates :initform 'helm-test-candidates)
   (action :initform 'helm-imenu-action)))

(defun test ()
  (interactive)
  (helm :sources (helm-make-source "Test"
                     'helm-test-source)))
```

Seems to work as expected, all candidates always appear, no matter when
and how often you interrupt Emacs/Helm with new input.  What do I miss?

**Comment by michael-heerdegen** [comment] 2015-01-28 10:37
And there is also an advantage in doing stuff in the candidates slot value: There is no initial delay when the user calls the command, you can start typing immediately.

**Comment by tuhdo** [comment] 2015-01-28 10:51
Probably this is fixed or it is strange behaviour interacting between Semantic and Helm. I had to generate candidates in `init` slot, otherwise frequently getting empty Helm buffer.

**Comment by thierryvolpiatto** [comment] 2015-01-28 10:55
Michael Heerdegen <notifications@github.com> writes:

> Tu Do <notifications@github.com> writes:
>
>> It is better not to generate candidates in :candidates slot. I had
>> that problem with helm-semantic before, where I tried the same thing.
>> When you assign to :candidates slot, the candidates should all be
>> ready to be display because at this point a Helm buffer and window is
>> created.
>
> Why?

@tuhdo You are confused with :candidates used in helm-source-sync and
the candidates list generated in a buffer with helm-source-in-buffer
(typically in :data or :init slots).
The former is generated in :candidates slot dynamically (or not, a plain
static list works also), while the second is a list of candidates
generated at initialization of helm, stored in a buffer, and then
narrowed as you type.
 
-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment] 2015-01-28 11:13
@thierryvolpiatto I see. Thanks for the explanation.

**Comment by michael-heerdegen** [comment] 2015-01-28 11:44
Tu Do <notifications@github.com> writes:

> Probably this is fixed or it is strange behaviour interacting between
> Semantic and Helm. I had to generate candidates in init slot,
> otherwise frequently getting empty Helm buffer.

Ok.  Anyway, thanks for pointing out that issue.

**Comment by thierryvolpiatto** [comment] 2015-01-28 12:04
Michael Heerdegen <notifications@github.com> writes:

> Tu Do <notifications@github.com> writes:
>
>> Probably this is fixed or it is strange behaviour interacting between
>> Semantic and Helm. I had to generate candidates in init slot,
>> otherwise frequently getting empty Helm buffer.
>
> Ok. Anyway, thanks for pointing out that issue.

There is no issue, he had to generate candidates in init because the
class used is helm-source-in-buffer, there is no problem at all
generating candidates from slot :candidates when using helm-source-sync.
Thus, if you try to create a source with in-buffer method using
:candidates slot you will immediately have an error (which is what expected).

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by michael-heerdegen** [comment] 2015-01-28 12:36
Thierry Volpiatto <notifications@github.com> writes:

> > Ok. Anyway, thanks for pointing out that issue.

> There is no issue

You misunderstood.  I know everything is ok now ;-) I just wanted to
thank Tu To for alluding a potential problem, even when it turned out to
be unrelated to the bug here.  But thanks for elaborating.
