### ISSUE TITLE
"No match" displayed when I hit RET in helm-M-x, even though a match is highlighted

### ISSUE THREAD

**Issue by rrthomas** [emacs-helm/helm#2070] opened 2018-07-27 16:02 UTC
## Expected behavior

The display appears to be ready, so helm should admit as much!

## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)

I can't reproduce this reliably.

## Steps to reproduce (recipe)

M-x, type something, sometimes, even though there's a match and the display has reached its final form, hitting RET produces the error "Display not ready".

## Describe versions of Helm, Emacs, operating system, etc.

Helm 2.9.8 from melpa-stable, Emacs 26.1 (built from source), Ubuntu 16.04, 

## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):

No, sorry! If I work out a way to repro it reliably, I will!

This seems very like bug #1157, but happens more rarely, and with an Emacs version that is supposedly immune to the problem.

FWIW, I had a similar rare occurrence of the problem with a patched Emacs 25 (using the patch that hard-wired `while-no-input` to ignore `EVENT_SELECTION_REQUEST`.

I have `while-no-input-ignore-events` set to its default value, i.e. including `selection-request`. The obvious suspicion therefore is that some other non-input event is being let through and mistaken for input, and I should be able to fix it just by adding that to the list. Any suggestions?

(Thanks in the mean time for your work on helm, it's probably the best level-up my Emacs has had in the last 5 years.)

**Comment by thierryvolpiatto** [comment] 2018-07-27 16:54
Reuben Thomas <notifications@github.com> writes:

> ## Expected behavior
>
> If a match is highlighted, it should be used.
>
> ## Actual behavior (from `emacs-helm.sh` if possible, see note at the bottom)
>
> I can't reproduce this reliably.

I can't reproduce either.

> ## Are you using `emacs-helm.sh` to reproduce this bug (yes/no):
>
> No, sorry! If I work out a way to repro it reliably, I will!

It's easy to ru emacs-helm.sh and guarantee there is nothing else that
trigger the bug.

> This seems very like bug #1157, but happens more rarely, and with an Emacs version that is supposedly immune to the problem.
>
> FWIW, I had a similar rare occurrence of the problem with a patched Emacs 25 (using the patch that hard-wired `while-no-input` to ignore `EVENT_SELECTION_REQUEST`.
>
> I have `while-no-input-ignore-events` set to its default value,
> i.e. including `selection-request`. The obvious suspicion therefore is
> that some other non-input event is being let through and mistaken for
> input, and I should be able to fix it just by adding that to the
> list. Any suggestions?

Is it possible you have a new event that run on your system that is not
listed in `while-no-input-ignore-events`? IOW Do you have something
special on your machine that may cause new kind of event not handled by emacs?


> (Thanks in the mean time for your work on helm, it's probably the best level-up my Emacs has had in the last 5 years.)

Thanks.

-- 
Thierry

**Comment by rrthomas** [comment] 2018-07-27 17:07
> It's easy to ru emacs-helm.sh and guarantee there is nothing else that trigger the bug.

Sure, it's just that I trigger the bug less than once per hour. If I can work out a way to trigger it often, I'll be straight to `emacs-helm

> Is it possible you have a new event that run on your system that is not listed in `while-no-input-ignore-events`? IOW Do you have something special on your machine that may cause new kind of event not handled by emacs?

Not that I'm aware of, only the same old ClipIt. If it continues I can try quitting various proprietary background apps I run (Slack, Zoom, Skype), and see if that helps.

I absolutely don't expect you to put serious effort into this without a better report! It's been happening for months, and has just annoyed me enough now that I thought it worth putting some effort in to tracking down.Hopefully I'll be able to get some sort of repro method before too long.

**Comment by thierryvolpiatto** [comment] 2018-07-27 17:20
Reuben Thomas <notifications@github.com> writes:

>> It's easy to ru emacs-helm.sh and guarantee there is nothing else that trigger the bug.
>
> Sure, it's just that I trigger the bug less than once per hour. If I can work out a way to trigger it often, I'll be straight to `emacs-helm
>
>> Is it possible you have a new event that run on your system that is not listed in `while-no-input-ignore-events`? IOW Do you have something special on your machine that may cause new kind of event not handled by emacs?
>
> Not that I'm aware of, only the same old ClipIt.

This one should be handled by `selection-request`, so no problem.

> If it continues I can try quitting various proprietary background apps
> I run (Slack, Zoom, Skype), and see if that helps.

Perhaps don't know.

> I absolutely don't expect you to put serious effort into this without
> a better report! It's been happening for months, and has just annoyed
> me enough now that I thought it worth putting some effort in to
> tracking down.Hopefully I'll be able to get some sort of repro method
> before too long.

Anyway, I have no ideas of what I could do...
Keep this open and see if others can reproduce and wait for more infos,
will see.

Thanks.

--
Thierry

**Comment by rrthomas** [comment] 2018-08-14 13:29
I have not had another instance of this happening since I reported it. For much of that time I have been running with all the proprietary apps I mentioned, and of course with my (libre) clipboard manager.

**Comment by rrthomas** [comment] 2018-09-16 12:56
After more testing, it seems definitely to be caused by the proprietary Skype application (version 8.x, which is Electron-based, not sure if that's significant). Obviously, this is not a Helm bug, but it would be interesting to know which event is interfering (since presumably it's not the clipboard event—I keep clipit running without any problem), as it might be an event that I can safely add to the ignore list.

**Comment by titaniumbones** [comment] 2019-02-12 00:34
I have something similar --  this occurs sometimes, but not always.  In my case, I type (e.g.) `M-x mu` and the completions buffer pops up but remains empty. I hten have to type backspace, and then re-enter `u`; suually by the 2nd or 3rd entry the options buffer wil lin fact populate.  Not sure if this is the same bug, or how I hsould try to figure that out.

**Comment by thierryvolpiatto** [comment] 2019-10-22 10:21
Closing as I never been able to reproduce such issue, feel free to reopen with more infos if needed.

**Closed by thierryvolpiatto** 2019-10-22 10:21 UTC
Labels: need_more_info, not_reproducible
