### ISSUE TITLE
Conflict with multiple-cursors

### ISSUE THREAD

**Issue by Pitometsu** [emacs-helm/helm#960] opened 2015-03-31 12:15 UTC
If I call *mc* from `helm-M-x` screen got to jump to each offscreen fake cursor on each move.

**Comment by Pitometsu** [comment] 2015-03-31 12:21
https://github.com/magnars/multiple-cursors.el/issues/190

**Comment by thierryvolpiatto** [comment] 2015-03-31 13:28
Netsu <notifications@github.com> writes:

> If I call mc from helm-M-x screen got to jump to each offscreen fake cursor on each move.

I don't know and don't use multiple-cursors, so if you want something to
be fixed, you will have to develop and find out what is wrong by yourself.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment] 2015-03-31 13:32
Does it happen with stock `M-x`?

**Comment by lewang** [comment] 2015-03-31 14:38
multiple-cursors does not support M-x - look at "Known Limitations" here:
https://github.com/magnars/multiple-cursors.el

On Tue, Mar 31, 2015 at 9:32 AM, Tu Do <notifications@github.com> wrote:

> Does it happen with stock M-x?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emacs-helm/helm/issues/960#issuecomment-88086187>.
>



-- 
Le

**Comment by Pitometsu** [comment] 2015-03-31 16:09
@tuhdo seems like stock `M-x` is ok.

**Comment by Pitometsu** [comment] 2015-03-31 16:12
@lewang 
> Commands run with M-x won't be repeated for all cursors.
For sure I can't use `M-x` under *mc*, but I can start *mc* from `M-x`, as I know. Any suggestions, please? Is it work for you?

**Comment by thierryvolpiatto** [comment] 2015-04-01 10:33
Looks that is a multiple-cursors issue according to @lewang , closing.

**Closed by thierryvolpiatto** 2015-04-01 10:33 UTC

**Comment by lewang** [comment] 2015-04-01 13:47
@Pitometsu I don't understand how you're using M-x in conjunction with multiple-cursors.  If you can provide detailed repo steps to clear up my misunderstanding, I will reopen this.

**Comment by andrebeat** [comment] 2015-09-01 11:05
I'm experiencing the same issue. The issue is not using `M-x` in conjunction with multiple-cursors (as that is not supported), the issue is calling multiple cursors itself either from `M-x` (which works) or from `helm-M-x` (doesn't work).

If you want to reproduce this it's simple: 
* Without helm:
  * select a region;
  * hit `M-x` and select the command `mc/edit-lines`;
  * works as expected, i.e. you'll get a cursor for each line.

* With helm:
  * select a region;
  * call `helm-M-x` and select the command `mc/edit-lines`;
  * you'll get a cursor for each line, but the `helm-M-x` input box will keep appearing for each line that was selected, and afterwards all the cursors will be gone.

**Comment by smurphy8** [comment] 2016-09-18 14:16
I have the same issue that @andrebeat is describing.  His description is what I experience. I'd be glad to run any tests to figure this out.

**Comment by smurphy8** [comment] 2016-09-18 14:21
It is a pretty easy workaround though, just bind `mc/edit-lines` to a key and you can use it.
