### ISSUE TITLE
errors when working with R noweb (Rnw) files

### ISSUE THREAD

**Issue by Jehops** [emacs-helm/helm#1126] opened 2015-08-10 23:05 UTC
When I work with R noweb files, I see errors such as the ones below.

    Error in post-command-hook (helm--update-header-line): (error "No buffer named *helm*")
    Error in post-command-hook (helm--maybe-update-keymap): (error "No buffer named *helm*")

Also, if I try to open a file from the shell with `emacsclient -n some_file` I will sometimes see

    jrm@gly ~ % emacsclient -n some_file
    *ERROR*: No buffer named *helm*

Unfortunately the problems aren't consistent.  Sometimes things work as normal other times not.  The problems only seem to happen when I'm working with R noweb files though.  This may be related to issue #88.  I've found others describing similar issues, e.g. https://github.com/kaz-yos/emacs/blob/master/init.d/200_emacsclient-related.el (See lines 28-).

**Comment by thierryvolpiatto** [comment] 2015-08-11 07:34
Please describe exactly what you are doing.
What OS are you using ?
What emacs version ?
Can you reproduce when using a minimal setting of helm (./emacs-helm.sh) ?
The second problem (emacsclient) is not reproductible here.

**Comment by Jehops** [comment] 2015-08-11 13:21
Today I tried

    (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/async-20150807.1724")
    (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/helm-20150810.1135")
    (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/helm-core-20150808.1327")
    (require 'helm-config)
    (helm-mode 1)

    (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/ess-20150810.826/lisp")
    (load "ess-site")

and opened an R noweb file and so far I'm not seeing the issue.  I normally have AUCTeX setup, so I'll try getting that in the mix and then I'll try dissecting my init.el to nail things down.  It might take me a few days to reply.

`M-x emacs-version`  says `GNU Emacs 24.5.1 (amd64-portbld-freebsd10.1, X toolkit) of 2015-04-28 on 10amd64-default-job-01`
I'm running GNU Emacs 24.5.1

**Comment by thierryvolpiatto** [comment] 2015-08-11 13:58
Joseph Mingrone <notifications@github.com> writes:

> Today I tried
>
> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/async-20150807.1724")
> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/helm-20150810.1135")
> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/helm-core-20150808.1327")
> (require 'helm-config)
> (helm-mode 1)
>
> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/ess-20150810.826/lisp")
> (load "ess-site")

You don't need to add to load-path stuff installed from elpa, just add
to your init file (on top):

(package-initialize)

This will add all your elpa packages to load-path and load the relevant
autoloads files.

> and opened an R noweb file and so far I'm not seeing the issue.

Great, have you recompiled helm files ? (or upgraded from melpa ?)
How do you open your "R noweb" file ? (I know nothing about R and noweb)

> I normally have AUCTeX setup, so I'll try getting that in the mix and
> then I'll try dissecting my init.el to nail things down. It might take
> me a few days to reply.

Ok thanks.

> M-x emacs-version says GNU Emacs 24.5.1 (amd64-portbld-freebsd10.1, X
> toolkit) of 2015-04-28 on 10amd64-default-job-01
> I'm running GNU Emacs 24.5.1

Good, me too.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Jehops** [comment] 2015-08-11 14:11
Thierry Volpiatto <notifications@github.com> writes:

> Joseph Mingrone <notifications@github.com> writes:

>> Today I tried

>> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/async-20150807.1724")
>> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/helm-20150810.1135")
>> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/helm-core-20150808.1327")
>> (require 'helm-config)
>> (helm-mode 1)

>> (add-to-list 'load-path "/home/jrm/.emacs.d/elpa/ess-20150810.826/lisp")
>> (load "ess-site")

> You don't need to add to load-path stuff installed from elpa, just add
> to your init file (on top):

> (package-initialize)

> This will add all your elpa packages to load-path and load the relevant
> autoloads files.

Yes, this is (basically) what I normally do.  This was just for testing
a minimal instance.  I should have put `emacs -Q` at the top of that
code block.

>> and opened an R noweb file and so far I'm not seeing the issue.

> Great, have you recompiled helm files ? (or upgraded from melpa ?)
> How do you open your "R noweb" file ? (I know nothing about R and
> noweb)

I have the latest helm from melpa.

With ESS installed, simply open a file with a .Rnw extension.  Here is
an example file:
https://github.com/yihui/knitr/blob/master/inst/examples/knitr-minimal.Rnw

You can see the file is LaTeX with R chunks between <<>>= ... @, e.g., 

<<boring-random>>=
set.seed(1121)
(x=rnorm(20))
mean(x);var(x)
@

>> I normally have AUCTeX setup, so I'll try getting that in the mix and
>> then I'll try dissecting my init.el to nail things down. It might take
>> me a few days to reply.

> Ok thanks.

>> M-x emacs-version says GNU Emacs 24.5.1 (amd64-portbld-freebsd10.1, X
>> toolkit) of 2015-04-28 on 10amd64-default-job-01
>> I'm running GNU Emacs 24.5.1

> Good, me too.

**Comment by thierryvolpiatto** [comment] 2015-08-11 15:00
Joseph Mingrone <notifications@github.com> writes:

> Yes, this is (basically) what I normally do. This was just for testing
> a minimal instance. I should have put `emacs -Q` at the top of that
> code block.

Ok.

> I have the latest helm from melpa.

Good.

> With ESS installed, simply open a file with a .Rnw extension. Here is
> an example file:
> https://github.com/yihui/knitr/blob/master/inst/examples/knitr-minimal.Rnw

Ah! thanks for the file, I have installed ess and could reproduce the
problem, not at every time, like you.

The problem comes IMO from the respectives local values of
post-command-hook of helm and ess, it seem there is a racing condition
that prevent helm from removing its hook when exiting, as a result, as
soon as you do anything in the remaining buffer the hooks run and die.

I made some changes that remove the hooks earlier and ensure they are
removed in the right buffer, seems I am now unable to reproduce, I will
keep trying some more few minutes if I can reproduce and then commit this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-08-11 15:42
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Joseph Mingrone <notifications@github.com> writes:
>
>> Yes, this is (basically) what I normally do. This was just for testing
>> a minimal instance. I should have put `emacs -Q` at the top of that
>> code block.
>
> Ok.
>
>> I have the latest helm from melpa.
>
> Good.
>
>> With ESS installed, simply open a file with a .Rnw extension. Here is
>> an example file:
>> https://github.com/yihui/knitr/blob/master/inst/examples/knitr-minimal.Rnw
>
> Ah! thanks for the file, I have installed ess and could reproduce the
> problem, not at every time, like you.
>
> The problem comes IMO from the respectives local values of
> post-command-hook of helm and ess, it seem there is a racing condition
> that prevent helm from removing its hook when exiting, as a result, as
> soon as you do anything in the remaining buffer the hooks run and die.
>
> I made some changes that remove the hooks earlier and ensure they are
> removed in the right buffer, seems I am now unable to reproduce, I will
> keep trying some more few minutes if I can reproduce and then commit this.

Ok I couldn't reproduce (good).
OTOH as soon I load "ess-site" and open your file, most helm keymaps become
broken in all buffers.
This is due to ESS which is breaking most other modes that use the same
vars/hooks.

Here is the offending function:

ess-noweb-make-variable-permanent-local

If I modify the function like this:

(defun ess-noweb-make-variable-permanent-local (var)
  "Declare VAR buffer local, but protect it from beeing killed
by major mode changes."
  ;; (make-variable-buffer-local var)
  ;; (put var 'permanent-local 't)
  (ignore)
  )

and reload emacs things are working normally.

So I think it is a bug in ess which is playing not safely with locals
vars.

I will commit anyway the change in helm that seems to prevent at least the
initial bug.

For the rest I suggest you submit a bugreport to ESS.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Jehops** [comment] 2015-08-11 15:53
Thierry Volpiatto <notifications@github.com> writes:
> For the rest I suggest you submit a bugreport to ESS.

I'll do that.  Thanks for the explanation and ridiculously fast action.

**Comment by thierryvolpiatto** [comment] 2015-08-12 15:08
Thierry Volpiatto <thierry.volpiatto@gmail.com> writes:

> Here is the offending function:
>
> ess-noweb-make-variable-permanent-local
>
> If I modify the function like this:
>
> (defun ess-noweb-make-variable-permanent-local (var)
>   "Declare VAR buffer local, but protect it from beeing killed
> by major mode changes."
>   ;; (make-variable-buffer-local var)
>   ;; (put var 'permanent-local 't)
>   (ignore)
>   )
>
> and reload emacs things are working normally.
>
> So I think it is a bug in ess which is playing not safely with locals
> vars.

To summarize ESS should not use `make-variable-buffer-local' on
`post-command-hook' (among others), and in addition should not make this
permanent-local (let add-hook handling this properly).

For more infos:

http://tinyurl.com/ohffm7d

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-08-15 09:18
So I am closing this now as it is a bug in ESS. Feel free to reopen if needed.

Thanks.

**Comment by Jehops** [comment] 2015-11-24 04:25
A recent change in either the helm or helm-core packages seems to have triggered this issue again.  After seeing the problem reappear on my laptop, I removed all the `make-variable-buffer-local` calls in `ess-noweb-mode.el` and byte compiled the files, but the problem remained.  Next I went to a different computer where the packages hadn't been updated recently.  I updated the `ess` packages and there were still no problems.  However, after updating the `helm` and `helm-core` packages, the problem started on the second computer.

Since you closed the issue, I don't have permission to reopen it.

**Comment by thierryvolpiatto** [comment] 2015-11-24 06:46
Joseph Mingrone <notifications@github.com> writes:

> A recent change in either the helm or helm-core packages seems to have
> triggered this issue again.

Again, I am not sure it is a problem with helm, I will try to reproduce
as soon as possible, can you remind me how to reproduce starting
with your sample file ?

> After seeing the problem reappear on my laptop, I removed all the
> make-variable-buffer-local calls in ess-noweb-mode.el and byte
> compiled the files, but the problem remained.

Can you get a backtrace ?

> Next I went to a different computer where the packages hadn't been
> updated recently. I updated the ess packages and there were still no
> problems. However, after updating the helm and helm-core packages, the
> problem started on the second computer.

Hmm, I don't see what have changed in helm that could trigger errors
with local variables, I think more of a bug in ess with local variable
handling, usage of `make-variable-buffer-local' is really tricky (should
be avoided generally).

> Since you closed the issue, I don't have permission to reopen it.

Really ? I think it's possible for you to reopen if needed, I reopened
it anyway.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Comment by thierryvolpiatto** [comment] 2015-11-24 07:18
Ok, I found the problem.
They are still making buffer-local `post-command-hook` which is very bad IMO.
Because we are now displaying the helm-buffer in same window as current-buffer (using display-buffer instead of pop-to-buffer) our `post-command-hook` are made buffer-local and continue running when quitting helm, if I fallback to `pop-to-buffer`, the errors disapear.
I could revert helm to use `pop-to-buffer` to avoid such errors, but this would be a regression, I would prefer that at ESS they stop making hooks buffer-local (not needed IMO, and not recommended anyway).

**Comment by Jehops** [comment] 2015-11-24 16:11
`ess-noweb-mode` is tricky because it has to deal with multiple modes.  It's also somewhat deprecated (meaning the maintainers are focused elsewhere), but its replacement isn't ready yet.

I changed the calls `make-variable-buffer-local` to `make-local-variable`.  The problem remained, but when I unmarked `post-command-hook` as permanent-local, all was good.  I'll try testing this for a few days and see if there is any new breakage in `ess-noweb-mode` and maybe submit a patch there.

As usual, thanks for the quick response and explanation.

**Comment by thierryvolpiatto** [comment] 2015-11-24 16:37
Joseph Mingrone <notifications@github.com> writes:

> I changed the calls make-variable-buffer-local to
> make-local-variable. The problem remained, but when I unmarked
> post-command-hook as permanent-local, all was good.

Yes, I also did the same here and couldn't reproduce.

> I'll try testing this for a few days and see if there is any new
> breakage in ess-noweb-mode and maybe submit a patch there.

Good, thanks.

> As usual, thanks for the quick response and explanation.

You are welcome.

-- 
Thierry
https://emacs-helm.github.io/helm/

**Closed** 2015-11-24 19:21 UTC
