### ISSUE TITLE
helm-do-grep, show file path?

### ISSUE THREAD

**Issue by davidcarslaw** [emacs-helm/helm#911] opened 2015-03-12 17:28 UTC
helm-do-grep is incredibly useful. Sometimes when searching through directories there can be multiple files with the same name. I know I can do C-z to have a look at each file but it would be useful if it was possible toggle the file path. Is that possible - or is there another way to get a bit more information concerning the actual location of the file?

Thaaks

**Comment by thierryvolpiatto** [comment] 2015-03-12 17:36
You can move the mouse pointer on the filename, is it enough ?

**Comment by davidcarslaw** [comment] 2015-03-12 17:43
Ah, didn't know that. Yes, that is very useful. Thanks! 

It would be nice to toggle the file path with C- ] the same as helm-find-files - but not so important now I can see the path in the way you suggest.

David

BTW, grep on my Mac was rather slow. However, installing and using GNU grep speeded things up a *lot*

**Comment by thierryvolpiatto** [comment] 2015-03-12 17:54
David Carslaw <notifications@github.com> writes:

> Ah, didn't know that. Yes, that is very useful. Thanks!
>
> It would be nice to toggle the file path with C- ] the same as
> helm-find-files

Yeah, the problem is the grep lines are generally long, so adding the
full path make it even more long and need truncating the end of the
line, it is why I never add this feature. 

> - but not so important now I can see the path in the way you suggest.
>
> David
>
> BTW, grep on my Mac was rather slow. However, installing and using GNU
> grep speeded things up a lot

Good to know, thanks, you can use also ack-grep, it is working very well
with helm, to speed up a little more (grep or ack-grep) you can
highlight match using the color provided by the backend you use (Ansi
colors).
See `helm-grep-default-command' for more infos on this.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-03-13 11:22
Closing this now, thanks.

**Closed by thierryvolpiatto** 2015-03-13 11:22 UTC
