### ISSUE TITLE
Some commands fail to load

### ISSUE THREAD

**Issue by MyFedora** [emacs-helm/helm#2608] opened 2023-07-31 12:21 UTC
### What happened?

I launched Emacs to search for an info article using Helm. But I got greeted with `(wrong-type-argument commandp helm-info-emacs)` instead of a Helm prompt.

### How to reproduce?

1. Use the following init.el file with Vanilla Emacs:
```elisp
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
  '(package-archives
   '(("gnu" . "https://elpa.gnu.org/packages/")
     ("nongnu" . "https://elpa.nongnu.org/nongnu/")
     ("melpa" . "https://melpa.org/packages/")))
 '(package-selected-packages
   '(helm)))

(require 'package)
(package-initialize)

(require 'helm-core)
(require 'helm)
```
2. `M-x package-refresh-contents`
3. `M-x package-install-selected-packages`
4. Restart
5. `C-x c h r` to generate error
6. `C-x c a` works as usual, and loads the missing commands for some reason
7. `C-x c h r` now works

### Helm Version

Melpa or NonGnuElpa

### Emacs Version

Emacs-28/29

### OS

GNU/Linux

### Relevant backtrace (if possible)

```text
Debugger entered--Lisp error: (wrong-type-argument commandp helm-info-emacs)
  call-interactively(helm-info-emacs nil nil)
  command-execute(helm-info-emacs)
```

### Minimal configuration

- [X] I agree using a minimal configuration

**Comment by thierryvolpiatto** [comment] 2023-07-31 18:54
MyFedora ***@***.***> writes:

> What happened?
>
> I launched Emacs to search for an info article using Helm. But I got
> greeted with (wrong-type-argument commandp helm-info-emacs) instead of
> a Helm prompt.

I think it is fixed now, but I will verify more carefully tomorrow
before merging.

Thanks.



-- 
Thierry

**Comment by rhoit** [comment] 2023-08-01 10:56
@thierryvolpiatto can you refer to the commit so that I can use it, not able to use emacs without helm. 😢

**Comment by thierryvolpiatto** [comment] 2023-08-01 11:16
rho ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> @thierryvolpiatto can you refer to the commit so that I can use it, not able to use emacs without helm. 😢

Now merged in Master. I did it early this morning so it should now has
make its way on Melpa. The commit is 3a861fbc.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by MyFedora** [comment] 2023-08-01 11:26
I updated the helm packages, and it appears like helm completely broke for me? Broke as in errors out during the initialization, the helm prefix is gone, etc.

helm 20230731.1852
helm-core 20230801.522
```
Debugger entered--Lisp error: (void-variable helm-info-source)
  byte-code("\301\10\302 \303\304\305\306\"\307\305\310\"\311\305\312\"\313\305\314\"$#\207" [helm-info-source defclass helm-source-in-buffer (info-file :initarg :info-file :initform nil :custom 'string) init :initform helm-info-init display-to-real helm-info-display-to-real get-line buffer-substring action (("Goto node" . helm-info-goto))] 10)
  require(helm-info)
  byte-code("\300\301!\210\300\302!\210\303\304\305\306\307\310%\210\311\312\313\314\315DD\316\317\320\321\322&\7\207" [require helm-lib helm-info custom-declare-group helm-global-bindings nil "Global bindings for Helm." :group helm custom-declare-variable helm-command-prefix-key funcall function #f(compiled-function () #<bytecode -0x85ca020d28a6ab6>) "The prefix key used to call Helm commands from the..." :type (choice (string :tag "Key") (const :tag "no binding")) :set #f(compiled-function (var key) #<bytecode 0x125edfd5dd41d9b3>)] 8)
  require(helm-global-bindings)
  byte-code("\300\301!\210\300\302!\210\303\304!\207" [require helm-core helm-global-bindings provide helm] 2)
  require(helm)
  eval-buffer(#<buffer  *load*> nil "/home/user/.config/emacs/init.el" nil t)  ; Reading at buffer position 1844
  load-with-code-conversion("/home/user/.config/emacs/init.el" "/home/user/.config/emacs/init.el" t t)
  load("/home/user/.config/emacs/init" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode 0x1873abf6cf4a5ca5>) #f(compiled-function () #<bytecode 0x18318643ffd2ed5f>) t)
  command-line()
  normal-top-level()
```

**Comment by pobermei** [comment] 2023-08-01 11:38
3a861fb works for me as expected. 

However, your latest commit on master 35b293c2 breaks it again:
```
Error (use-package): helm-bibtex/:init: Symbol’s value as variable is void: helm-info-source
Error (use-package): helm-bibtex/:catch: Symbol’s value as variable is void: helm-info-source
Error (use-package): org-ref-helm/:catch: Symbol’s value as variable is void: helm-info-source
Error (use-package): helm-org-ql/:catch: Symbol’s value as variable is void: helm-info-source
```

**Comment by MyFedora** [comment] 2023-08-01 11:55
#2609

**Comment by thierryvolpiatto** [comment] 2023-08-01 15:22
I have reverted for now 3a861fbc even if it seems the right fix.
For now @MyFedora you will have to require helm-info before calling one of its commands or calling `(helm-mode 1)`.

**Comment by thierryvolpiatto** [comment] 2023-08-01 17:07
Now trying to require helm-info from helm.el.
Let me know if it works.
Note that I am trying to fix this blindly for now as I can't reproduce reliabily.
I will try to install from package tomorrow to see if I can reproduce (I am always installing helm from source with make).

**Comment by pobermei** [comment] 2023-08-01 20:06
> Now trying to require helm-info from helm.el. Let me know if it works. Note that I am trying to fix this blindly for now as I can't reproduce reliabily. I will try to install from package tomorrow to see if I can reproduce (I am always installing helm from source with make).

Thank you for your effort!

FWIW, I tried e3894eb , but encountered the same error messages as mentioned [above](https://github.com/emacs-helm/helm/issues/2608#issuecomment-1660139030). I also tested a minimal config only requesting
```
(use-package helm :straight t :demand t)
```
with the same result.

The errors disappeared when reverting back to fef7bb1d282079fa3bb3c8457f053270b3502776

**Comment by thierryvolpiatto** [comment] 2023-08-01 20:34
Philipp Obermeier ***@***.***> writes:

>     Now trying to require helm-info from helm.el. Let me know if it works. Note that I am trying to fix this blindly for now as I can't reproduce reliabily. I will try to install from
>     package tomorrow to see if I can reproduce (I am always installing helm from source with make).
>    
> Thank you for your effort!
>
> FWIW, I tried e3894eb , but encountered the same error messages as mentioned above. I also tested a minimal config only requesting
>
> (use-package helm :straight t :demand t)
>
> with the same result.

Hmm, I tried to install helm from package.el and had no problems.

What would be helpful is to have a simple recipe to reproduce, by simple
I mean without use-package, straight etc... Just a fresh install of
helm, then (require 'helm) and then C-x c h r.

> The errors disappeared when reverting back to fef7bb1

Yes, this is same as before.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by michael-heerdegen** [comment] 2023-08-02 01:31
Thierry Volpiatto ***@***.***> writes:

> I have reverted for now 3a861fb even if it seems the right fix.

Looks like an appropriate fix indeed.

But the posted backtrace above hints at the fact that the file had been
compiled without "eieio" loaded (`defclass' is obviously being handled
like a function call, evaluating the arguments).

I think your removed dependencies are the cause, and you just may need
to (require 'eieio) in "helm-info".

**Comment by michael-heerdegen** [comment] 2023-08-02 01:59
Michael Heerdegen ***@***.***> writes:

> Thierry Volpiatto ***@***.***> writes:
>
> > I have reverted for now 3a861fb even if it seems the right fix.
>
> Looks like an appropriate fix indeed.

I didn't check for other dependency problems and also didn't test.

But maybe the simplest way to fix this would be to add explicit autoload
calls (at least for 'helm-info-at-point', 'helm-info-emacs',
'helm-info-gnus'): the actual problem is only that no autoload cookies
are created for these commands when installing.  But we are sure that
these will always be installed, so we can add these manually.

Something to care about as well is that 'helm-default-info-index-list'
has a setter - what happens when a user customizes that variable and
loads the custom file before loading helm?  The setter is not
autoloaded.

**Comment by thierryvolpiatto** [comment] 2023-08-02 05:18
Michael Heerdegen ***@***.***> writes:

> Thierry Volpiatto ***@***.***> writes:
>
>> I have reverted for now 3a861fb even if it seems the right fix.
>
> Looks like an appropriate fix indeed.
>
> But the posted backtrace above hints at the fact that the file had been
> compiled without "eieio" loaded (`defclass' is obviously being handled
> like a function call, evaluating the arguments).
>
> I think your removed dependencies are the cause, and you just may need
> to (require 'eieio) in "helm-info".

Yes the backtrace make this clear (helm-source-info is treated as a
variable whereas it is a class), this is why I modify this change and
require helm-info just after requiring helm-core which require
helm-source which require eieio.  I will try anyway to follow your
advice and require eieio on top of helm-info.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by michael-heerdegen** [comment] 2023-08-02 05:31
Thierry Volpiatto ***@***.***> writes:

> [...] this is why I modify this change and require helm-info just
> after requiring helm-core which require helm-source which require
> eieio.

AFAIU, the crucial point is compiling.  If helm-info gets compiled
before loading the other files when installing the package, eieio is not
loaded.

**Comment by thierryvolpiatto** [comment] 2023-08-02 05:40
Michael Heerdegen ***@***.***> writes:

> Michael Heerdegen ***@***.***> writes:
>
>> Thierry Volpiatto ***@***.***> writes:
>>
>> > I have reverted for now 3a861fb even if it seems the right fix.
>>
>> Looks like an appropriate fix indeed.
>
> I didn't check for other dependency problems and also didn't test.
>
> But maybe the simplest way to fix this would be to add explicit autoload
> calls (at least for 'helm-info-at-point', 'helm-info-emacs',
> 'helm-info-gnus'): the actual problem is only that no autoload cookies
> are created for these commands when installing. But we are sure that
> these will always be installed, so we can add these manually.

The problem is that all these commands are not defined explicitely, they
are build when helm-info is loaded by the setter you mention below.

> Something to care about as well is that 'helm-default-info-index-list'
> has a setter - what happens when a user customizes that variable and
> loads the custom file before loading helm? The setter is not
> autoloaded.

Yes completely, adding an autoload to the setter may fix this.

Thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2023-08-02 06:30
Here some recipes:

I) From source:
1) Download helm or get it with git clone.
2) cd to helm dir and make && sudo make install
3) emacs -q (-q not -Q)
4) in scratch buffer `(require 'helm)`
5) `C-x c h r`

II) from package installation:
1) Install helm with package-install from your main emacs
2) run emacs -Q
3) eval `(package-initialize)`
4) `(require 'helm)`
5) `C-x c h r`

Is one of these two recipes work?
NOTE: For second recipe please wait Melpa update before installing Helm.

**Comment by thierryvolpiatto** [comment] 2023-08-02 06:36
Michael Heerdegen ***@***.***> writes:

> Thierry Volpiatto ***@***.***> writes:
>
>> [...] this is why I modify this change and require helm-info just
>> after requiring helm-core which require helm-source which require
>> eieio.
>
> AFAIU, the crucial point is compiling. If helm-info gets compiled
> before loading the other files when installing the package, eieio is not
> loaded.

Right, I explicitely required helm-source on top of helm-info, let see
if it works like this.

>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by rhoit** [comment] 2023-08-02 15:50
> Here some recipes:
> 
> I) From source:
> 
>     1. Download helm or get it with git clone.
> 
>     2. cd to helm dir and make && sudo make install
> 
>     3. emacs -q (-q not -Q)
> 
>     4. in scratch buffer `(require 'helm)`
> 
>     5. `C-x c h r`
> 
> 
> II) from package installation:
> 
>     1. Install helm with package-install from your main emacs
> 
>     2. run emacs -Q
> 
>     3. eval `(package-initialize)`
> 
>     4. `(require 'helm)`
> 
>     5. `C-x c h r`
> 
> 
> Is one of these two recipes work? NOTE: For second recipe please wait Melpa update before installing Helm.

Really great full for your effort, its works 🥳, for me from melpa.

**Comment by thierryvolpiatto** [comment] 2023-08-02 17:41
rho ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> there seems to be problem with helm-ring, here is the backtrace
>
> Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "helm-ring")
>   (helm-show-kill-ring)
>   (progn (undo-only) (if (= (point) repetitive_yank_region_point) (progn (progn (goto-char repetitive_yank_region_mark) (set-mark-command nil) (goto-char repetitive_yank_region_point) (delete-selection-helper "yank")))) (helm-show-kill-ring))
>   (if (string= last-command "yank") (progn (undo-only) (if (= (point) repetitive_yank_region_point) (progn (progn (goto-char repetitive_yank_region_mark) (set-mark-command nil) (goto-char repetitive_yank_region_point) (delete-selection-helper "yank")))) (helm-show-kill-ring)) (progn (if (use-region-p) (progn (setq repetitive_yank_region_mark (mark)) (setq repetitive_yank_region_point (point)) (message "%s" repetitive_yank_region_point) (delete-selection-helper "yank"))) (yank)))
>   repetitive-yanking()
>   funcall-interactively(repetitive-yanking)
>   command-execute(repetitive-yanking)

Where is repetitive-yanking command coming from?

> for now I have directly loaded the helm-ring.el to get things working
>
> (load "/home/rho/.config/emacs/elpa/helm-20230802.1453/helm-ring.el")
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2023-08-02 17:42
rho ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
>     Here some recipes:
>    
>     I) From source:
>    
>     1. Download helm or get it with git clone.
>     
>     2. cd to helm dir and make && sudo make install
>     
>     3. emacs -q (-q not -Q)
>     
>     4. in scratch buffer `(require 'helm)`
>     
>     5. `C-x c h r`
>     
>     II) from package installation:
>    
>     1. Install helm with package-install from your main emacs
>     
>     2. run emacs -Q
>     
>     3. eval `(package-initialize)`
>     
>     4. `(require 'helm)`
>     
>     5. `C-x c h r`
>     
>     Is one of these two recipes work? NOTE: For second recipe please wait Melpa update before installing Helm.
>    
> Really great full for your effort, its works 🥳, for me from melpa.

Great, thanks.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by rhoit** [comment] 2023-08-02 18:13
> rho ***@***.***> writes:
> 1. ( ) text/plain (*) text/html there seems to be problem with helm-ring, here is the backtrace Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "helm-ring") (helm-show-kill-ring) (progn (undo-only) (if (= (point) repetitive_yank_region_point) (progn (progn (goto-char repetitive_yank_region_mark) (set-mark-command nil) (goto-char repetitive_yank_region_point) (delete-selection-helper "yank")))) (helm-show-kill-ring)) (if (string= last-command "yank") (progn (undo-only) (if (= (point) repetitive_yank_region_point) (progn (progn (goto-char repetitive_yank_region_mark) (set-mark-command nil) (goto-char repetitive_yank_region_point) (delete-selection-helper "yank")))) (helm-show-kill-ring)) (progn (if (use-region-p) (progn (setq repetitive_yank_region_mark (mark)) (setq repetitive_yank_region_point (point)) (message "%s" repetitive_yank_region_point) (delete-selection-helper "yank"))) (yank))) repetitive-yanking() funcall-interactively(repetitive-yanking) command-execute(repetitive-yanking)
> Where is repetitive-yanking command coming from?
> […](#)
> for now I have directly loaded the helm-ring.el to get things working (load "/home/rho/.config/emacs/elpa/helm-20230802.1453/helm-ring.el") — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.*Message ID: ***@***.***>
> -- Thierry

oops! that was on me, thanks for pointing something from my config, everything looks good now!

**Comment by thierryvolpiatto** [comment] 2023-08-02 18:21
rho ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> there seems to be problem with helm-ring, here is the backtrace
>
> Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "helm-ring")
>   (helm-show-kill-ring)
>   (progn (undo-only) (if (= (point) repetitive_yank_region_point) (progn (progn (goto-char repetitive_yank_region_mark) (set-mark-command nil) (goto-char repetitive_yank_region_point) (delete-selection-helper "yank")))) (helm-show-kill-ring))
>   (if (string= last-command "yank") (progn (undo-only) (if (= (point) repetitive_yank_region_point) (progn (progn (goto-char repetitive_yank_region_mark) (set-mark-command nil) (goto-char repetitive_yank_region_point) (delete-selection-helper "yank")))) (helm-show-kill-ring)) (progn (if (use-region-p) (progn (setq repetitive_yank_region_mark (mark)) (setq repetitive_yank_region_point (point)) (message "%s" repetitive_yank_region_point) (delete-selection-helper "yank"))) (yank)))
>   repetitive-yanking()
>   funcall-interactively(repetitive-yanking)
>   command-execute(repetitive-yanking)

Ok, I found that repetitive-yanking is a function in your config!
The helm-ring.el file is not found because your helm directory is not
yet in load-path when you call your command, ensure initialization of
your packages first.
It seems you use a non standard user-emacs-directory (instead of
".emacs.d") expect complications to make this fully working.

> for now I have directly loaded the helm-ring.el to get things working
>
> (load "/home/rho/.config/emacs/elpa/helm-20230802.1453/helm-ring.el")

That's it, you should not have to do this, all subdirs in
"/home/rho/.config/emacs/elpa/" should be in load-path if you initialize
your packages correctly.

Hope that helps.

> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.*Message ID: ***@***.***>


-- 
Thierry

**Comment by rhoit** [comment] 2023-08-02 18:47
😆 thanks for giving feedback of my config, its more like mess of snippets every where, lisp is not my thing.

**Comment by michael-heerdegen** [comment] 2023-08-03 00:21
Thierry Volpiatto ***@***.***> writes:

> > But maybe the simplest way to fix this would be to add explicit autoload 
> > calls (at least for 'helm-info-at-point', 'helm-info-emacs', 
> > 'helm-info-gnus'): the actual problem is only that no autoload cookies 
> > are created for these commands when installing. But we are sure that 
> > these will always be installed, so we can add these manually. 
>
> The problem is that all these commands are not defined explicitely, they 
> are build when helm-info is loaded by the setter you mention below. 

What I meant was that you could add explicit autoload _calls_ (autoload
...) for the commands that are bound in the keymaps (there are three).
That would solve the original problem without changing any file
dependencies.

What the better way of fixing is I don't know.

> Yes completely, adding an autoload to the setter may fix this. 

Hmm - when I only load the files required in helm-info, and then load
helm-info in a fresh Emacs session I get (shortened)

| Debugger entered--Lisp error: (void-variable helm-map)
|   symbol-value(helm-map)
|   (if (symbolp it) (symbol-value it) it)
|   (let* ((map (if (symbolp it) (symbol-value it) it)) (must-match-map (if (slot-value source 'must-match) (progn (let ((map ...)) (define-key map (kbd "RET") 'helm-confirm-and-exit-minibuffer) map)))) (loc-map (if must-match-map (make-composed-keymap must-match-map map) map))) (let* ((v source)) (eieio-oset v 'keymap loc-map)))
|   (if it (let* ((map (if (symbolp it) (symbol-value it) it)) (must-match-map (if (slot-value source 'must-match) (progn (let (...) (define-key map ... ...) map)))) (loc-map (if must-match-map (make-composed-keymap must-match-map map) map))) (let* ((v source)) (eieio-oset v 'keymap loc-map))))
|   (let ((it (slot-value source 'keymap))) (if it (let* ((map (if (symbolp it) (symbol-value it) it)) (must-match-map (if (slot-value source 'must-match) (progn (let ... ... map)))) (loc-map (if must-match-map (make-composed-keymap must-match-map map) map))) (let* ((v source)) (eieio-oset v 'keymap loc-map)))))
|   (progn (if (slot-value source 'group) nil (let* ((v source)) (eieio-oset v 'group 'helm))) (if (slot-value source 'delayed) (progn (warn "Deprecated usage of helm `delayed' slot in `%s'" (slot-value source 'name)))) (let ((it (slot-value source 'keymap))) (if it (let* ((map (if (symbolp it) (symbol-value it) it)) (must-match-map (if (slot-value source ...) (progn ...))) (loc-map (if must-match-map (make-composed-keymap must-match-map map) map))) (let* ((v source)) (eieio-oset v 'keymap loc-map))))) (let ((it (slot-value source 'persistent-help))) (if it (let* ((v source)) (eieio-oset v 'header-line (helm-source--persistent-help-string it source))) (let* ((v source)) (eieio-oset v 'header-line (helm-source--header-line source))))) (if (slot-value source 'fuzzy-match) (progn (progn (or helm-fuzzy-sort-fn (cl--assertion-failed 'helm-fuzzy-sort-fn "Wrong type argument functionp: nil" (list) (list))) nil) (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let ((it ...)) (if it (append ... ...) (list helm-fuzzy-sort-fn))))))) (if (slot-value source 'nohighlight) nil (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let ((it (slot-value source ...))) (if it (append (helm-mklist it) (list ...)) (list #'helm-fuzzy-highlight-matches)))))) (if (numberp (helm-interpret-value (slot-value source 'multiline))) (progn (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let ((it ...)) (if it (append ... ...) (list ...))))))) (let ((it (slot-value source 'requires-pattern))) (if it (let ((val (if (symbolp it) (symbol-value it) it))) (let* ((v source)) (eieio-oset v 'requires-pattern val))))) (let ((sname (slot-value source 'name))) (let* ((val (slot-value source 'before-init-hook))) (cond ((functionp val) (cond ((let* ... ...) (let ... ... ...)) ((consp val) (let ... ... ...)))) ((consp val) (let ((val nil)) (ignore val) (warn "Helm source `%s': before-init-hook Should be defin..." sname))))) (let* ((val (slot-value source 'after-init-hook))) (cond ((functionp val) (cond ((let* ... ...) (let ... ... ...)) ((consp val) (let ... ... ...)))) ((consp val) (let ((val nil)) (ignore val) (warn "Helm source `%s': after-init-hook Should be define..." sname)))))))
|   (progn (progn (if (slot-value source 'group) nil (let* ((v source)) (eieio-oset v 'group 'helm))) (if (slot-value source 'delayed) (progn (warn "Deprecated usage of helm `delayed' slot in `%s'" (slot-value source 'name)))) (let ((it (slot-value source 'keymap))) (if it (let* ((map (if ... ... it)) (must-match-map (if ... ...)) (loc-map (if must-match-map ... map))) (let* ((v source)) (eieio-oset v 'keymap loc-map))))) (let ((it (slot-value source 'persistent-help))) (if it (let* ((v source)) (eieio-oset v 'header-line (helm-source--persistent-help-string it source))) (let* ((v source)) (eieio-oset v 'header-line (helm-source--header-line source))))) (if (slot-value source 'fuzzy-match) (progn (progn (or helm-fuzzy-sort-fn (cl--assertion-failed 'helm-fuzzy-sort-fn "Wrong type argument functionp: nil" (list) (list))) nil) (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let (...) (if it ... ...)))))) (if (slot-value source 'nohighlight) nil (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let ((it ...)) (if it (append ... ...) (list ...)))))) (if (numberp (helm-interpret-value (slot-value source 'multiline))) (progn (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let (...) (if it ... ...)))))) (let ((it (slot-value source 'requires-pattern))) (if it (let ((val (if ... ... it))) (let* ((v source)) (eieio-oset v 'requires-pattern val))))) (let ((sname (slot-value source 'name))) (let* ((val (slot-value source 'before-init-hook))) (cond ((functionp val) (cond (... ...) (... ...))) ((consp val) (let (...) (ignore val) (warn "Helm source `%s': before-init-hook Should be defin..." sname))))) (let* ((val (slot-value source 'after-init-hook))) (cond ((functionp val) (cond (... ...) (... ...))) ((consp val) (let (...) (ignore val) (warn "Helm source `%s': after-init-hook Should be define..." sname))))))))
|   (closure (helm-mm-default-match-functions helm-mm-default-search-functions helm-fuzzy-search-fn helm-fuzzy-match-fn helm-fuzzy-sort-fn t) (source) (progn (progn (if (slot-value source 'group) nil (let* ((v source)) (eieio-oset v 'group 'helm))) (if (slot-value source 'delayed) (progn (warn "Deprecated usage of helm `delayed' slot in `%s'" (slot-value source ...)))) (let ((it (slot-value source ...))) (if it (let* (... ... ...) (let* ... ...)))) (let ((it (slot-value source ...))) (if it (let* (...) (eieio-oset v ... ...)) (let* (...) (eieio-oset v ... ...)))) (if (slot-value source 'fuzzy-match) (progn (progn (or helm-fuzzy-sort-fn ...) nil) (let* (...) (eieio-oset v ... ...)))) (if (slot-value source 'nohighlight) nil (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let ... ...)))) (if (numberp (helm-interpret-value (slot-value source ...))) (progn (let* (...) (eieio-oset v ... ...)))) (let ((it (slot-value source ...))) (if it (let (...) (let* ... ...)))) (let ((sname (slot-value source ...))) (let* ((val ...)) (cond (... ...) (... ...))) (let* ((val ...)) (cond (... ...) (... ...)))))))(#<helm-info-source helm-info-source-156d9fb5d2ba>)
|   apply((closure (helm-mm-default-match-functions helm-mm-default-search-functions helm-fuzzy-search-fn helm-fuzzy-match-fn helm-fuzzy-sort-fn t) (source) (progn (progn (if (slot-value source 'group) nil (let* ((v source)) (eieio-oset v 'group 'helm))) (if (slot-value source 'delayed) (progn (warn "Deprecated usage of helm `delayed' slot in `%s'" (slot-value source ...)))) (let ((it (slot-value source ...))) (if it (let* (... ... ...) (let* ... ...)))) (let ((it (slot-value source ...))) (if it (let* (...) (eieio-oset v ... ...)) (let* (...) (eieio-oset v ... ...)))) (if (slot-value source 'fuzzy-match) (progn (progn (or helm-fuzzy-sort-fn ...) nil) (let* (...) (eieio-oset v ... ...)))) (if (slot-value source 'nohighlight) nil (let* ((v source)) (eieio-oset v 'filtered-candidate-transformer (let ... ...)))) (if (numberp (helm-interpret-value (slot-value source ...))) (progn (let* (...) (eieio-oset v ... ...)))) (let ((it (slot-value source ...))) (if it (let (...) (let* ... ...)))) (let ((sname (slot-value source ...))) (let* ((val ...)) (cond (... ...) (... ...))) (let* ((val ...)) (cond (... ...) (... ...))))))) #<helm-info-source helm-info-source-156d9fb5d2ba>)
|   helm-define-info-index-sources(("auth" "autotype" "bovine" "calc" "ccmode" "cl" "dbus" "dired-x" "ebrowse" "ede" "ediff" "edt" "efaq-w32" "efaq" "eglot" "eieio" "eintr" "elisp" "emacs-gnutls" "emacs-mime" "emacs" "epa" "erc" "ert" "eshell" "eudc" "eww" "flymake" "forms" "gnus" "htmlfontify" "idlwave" "ido" "info" "mairix-el" "message" "mh-e" "modus-themes" "newsticker" "nxml-mode" "octave-mode" "org" "pcl-cvs" "pgg" "rcirc" "reftex" "remember" "sasl" "sc" "semantic" ...) t)
|   helm-info-index-set(helm-default-info-index-list ("auth" "autotype" "bovine" "calc" "ccmode" "cl" "dbus" "dired-x" "ebrowse" "ede" "ediff" "edt" "efaq-w32" "efaq" "eglot" "eieio" "eintr" "elisp" "emacs-gnutls" "emacs-mime" "emacs" "epa" "erc" "ert" "eshell" "eudc" "eww" "flymake" "forms" "gnus" "htmlfontify" "idlwave" "ido" "info" "mairix-el" "message" "mh-e" "modus-themes" "newsticker" "nxml-mode" "octave-mode" "org" "pcl-cvs" "pgg" "rcirc" "reftex" "remember" "sasl" "sc" "semantic" ...))
|   custom-declare-variable
|   eval-buffer()

Thx,

Michael.

**Comment by thierryvolpiatto** [comment] 2023-08-03 06:07
Michael Heerdegen ***@***.***> writes:

> 1.  ( ) text/plain          (*) text/html           
>
> Thierry Volpiatto ***@***.***> writes:
>
>> > But maybe the simplest way to fix this would be to add explicit autoload
>> > calls (at least for 'helm-info-at-point', 'helm-info-emacs',
>> > 'helm-info-gnus'): the actual problem is only that no autoload cookies
>> > are created for these commands when installing. But we are sure that
>> > these will always be installed, so we can add these manually.
>>
>> The problem is that all these commands are not defined explicitely, they
>> are build when helm-info is loaded by the setter you mention below.
>
> What I meant was that you could add explicit autoload _calls_ (autoload
> ...) for the commands that are bound in the keymaps (there are three).
> That would solve the original problem without changing any file
> dependencies.

Yes, that's the best way to fix this, I didn't think of "only three in
keymap", and yes it is only what we need at this point.
Many thanks for this!

> What the better way of fixing is I don't know.

I added the autoloads in helm.el (after removing the require to
helm-info) and replaced the dependencies more or less as before in
helm-info.

>> Yes completely, adding an autoload to the setter may fix this.
>
> Hmm - when I only load the files required in helm-info, and then load
> helm-info in a fresh Emacs session I get (shortened)

What you suggested above fix this as well, you can even require helm-info
directly and C-x c h r is working.

I will merge this soon after verifying one more time it works with a
package installation (thanks to the new package-vc-install!).


Thanks.


-- 
Thierry

**Closed** 2023-10-10 14:43 UTC
Labels: bug
