### ISSUE TITLE
Spurious input when typing moderately fast with a long candidate list

### ISSUE THREAD

**Issue by bard** [emacs-helm/helm#2411] opened 2021-05-01 10:28 UTC
## Expected behavior

Only what I type in the minibuffer appears in the minibuffer and is used for completion.

## Actual behavior (from `emacs-helm.sh` if possible, see note above)

Part of the what I type appears twice, breaking completion.

## Steps to reproduce (recipe)

1. Launch `emacs-helm.sh` under X11
2. Attempt to complete from a big candidate list, e.g. with `describe-function`
3. Type 3 or more characters relatively fast, without pause, e.g. "fund"
4. First character appears in the minibuffer; there is a pause; second and third character appear, then second and third again, then the rest, e.g.:
    1. `f`
    2. `f[pause]`
    3. `fun`
    4. `funund`

See recording below.

Does not happen when running in the terminal.

Does not happen with a 1- or 2-character input.

Does not happen if, after the second character, I wait for Helm to display completions, then continuing to type.

![screencast](https://user-images.githubusercontent.com/19322/116779739-01e86a80-aa70-11eb-84c3-25618895e77e.gif)

## Backtraces if any (`M-x toggle-debug-on-error`)

None.

## Describe versions of Helm, Emacs, operating system, etc.

emacs: 28.0.50.147973-1
OS: Arch Linux
xorg: 1.20.11-1
helm: 20210426.551
helm-core: 20210425.1928

## Are you using `emacs-helm.sh` to reproduce this bug? (yes/no):

yes

**Comment by Chaformbintrano** [comment] 2021-05-04 21:45
It happens to me as well. My computer being slow at times makes it even worse.

Emacs: native-comp 28.0.50-180.9c7b0a1
OS: Guix
X: 1.20.10
Helm: 3.7.0

**Comment by thierryvolpiatto** [comment] 2021-05-05 05:12
This is a duplicate of #2312, please continue on this thread, I am closing this one.

**Comment by bard** [comment] 2021-06-06 13:06
A belated note to confirm that, as per https://github.com/emacs-helm/helm/issues/2312#issuecomment-852953368, switching to non-pgtk Emacs fixes this issue.

**Comment by gmoutso** [comment] 2021-06-23 14:17
Also on pgtk, I notice it happening with `helm-M-x`, not with other helm menus such as switch buffer.

**Comment by gmoutso** [comment] 2021-06-23 14:29
It also seems to repeat only the 2nd and 3d character if there are more than 100 candidates in the first three. For instance, I write fast "complete" and I get "comomplete". I write fast "com" I still get "comom". Same with "mag"->"magag" for magit. But not with "vc-" (that has 64 completions) or "geo" for george (with 0 completions).

**Comment by gmoutso** [comment] 2021-06-23 15:19
Setting `(setq helm-M-x-use-completion-styles nil)` **fixes** this bug for me. However, `helm-M-x` is very slow when typing that sounds like #2312.

**Comment by thierryvolpiatto** [comment] 2021-06-23 15:56
George Moutsopoulos ***@***.***> writes:

> Setting (setq helm-M-x-use-completion-styles nil) fixes this bug for
> me. However, helm-M-x is very slow when typing that sounds like #2312.

Are you using MacOs as well?

Are you using different settings than default?

Can you reproduce on Emacs-27.2?

-- 
Thierry

**Comment by gmoutso** [comment] 2021-06-23 16:25
I am on ubuntu 21.04. This is with [pgtk-native-comp](https://github.com/flatwhatson/emacs.git) 28.0.50 (June 14) and no helm configuration (emacs -q).

I have no problems with emacs 27.1 that ubuntu provides. I haven't tried emacs 27.2.

I also tried a snap 28.05 native-comp without pgtk that did not have this double typing.

**Comment by thierryvolpiatto** [comment] 2021-06-23 16:37
George Moutsopoulos ***@***.***> writes:

> I am on ubuntu 21.04. This is with pgtk-native-comp 28.0.50 (June 14) and no helm configuration (emacs -q).

Yes, it have been reported several time with this branch, I will not try
providing a fix for it as it is a flying target, same for now with
emacs-28 branch.
 
> I have no problems with emacs 27.1 that ubuntu provides. I haven't tried emacs 27.2.

Yeah they are more or less the same, so if it works fine in 27.1, it
will work same in 27.2.

> I also tried a snap 28.05 native-comp without pgtk that did not have this double typing.

Ok.

Thanks to report.

PS:
At one point I guess I will make helm-M-x working as it was on Helm-3.5
i.e. no completion-styles. The variable `helm-M-x-use-completion-styles`
allows this but with a sync-source implementation which is slow, it is
here mostly for debugging purpose.

-- 
Thierry

**Comment by gmoutso** [comment] 2021-06-23 17:22
> I will not try providing a fix for it as it is a flying target
Makes sense. Thanks for your work Thierry!

**Comment by thierryvolpiatto** [comment] 2021-06-23 18:02
Is this patch fixing it for you?

```diff
diff --git a/helm-command.el b/helm-command.el
index a378c40b..72c3c794 100644
--- a/helm-command.el
+++ b/helm-command.el
@@ -204,7 +204,7 @@ algorithm."
   (remove-hook 'helm-move-selection-after-hook
                'helm-M-x--move-selection-after-hook))
 
-(defclass helm-M-x-class (helm-source-sync helm-type-command)
+(defclass helm-M-x-class (helm-source-in-buffer helm-type-command)
   ((requires-pattern :initform 0)
    (must-match :initform t)
    (filtered-candidate-transformer :initform 'helm-M-x-transformer-no-sort)
@@ -230,45 +230,26 @@ default to `extended-command-history'."
   (let* ((helm--mode-line-display-prefarg t)
          (minibuffer-completion-confirm t)
          (pred (or predicate #'commandp))
-         (metadata (unless (assq 'flex completion-styles-alist)
-                     '(metadata (display-sort-function
-                                 .
-                                 (lambda (candidates)
-                                   (sort candidates #'helm-generic-sort-fn))))))
          (helm-fuzzy-sort-fn (lambda (candidates _source)
                                ;; Sort on real candidate otherwise
                                ;; "symbol (<binding>)" is used when sorting.
                                (helm-fuzzy-matching-default-sort-fn-1 candidates t)))
          (sources `(,(helm-make-source "Emacs Commands history" 'helm-M-x-class
-                       :match-dynamic helm-M-x-use-completion-styles
-                       :candidates
-                       (if helm-M-x-use-completion-styles
-                           (helm-dynamic-completion
-                            ;; A list of strings.
-                            (or history extended-command-history)
-                            (lambda (str) (funcall pred (intern-soft str)))
-                            nil 'nosort t)
-                         (lambda () (helm-comp-read-get-candidates
-                                     ;; History should be quoted to
-                                     ;; force `helm-comp-read-get-candidates'
-                                     ;; to use predicate against
-                                     ;; symbol and not string.
-                                     (or history 'extended-command-history)
-                                     ;; Ensure using empty string to
-                                     ;; not defeat helm matching fns [1]
-                                     pred nil nil "")))
-                       :fuzzy-match (null helm-M-x-use-completion-styles))
+                       :data (lambda () (helm-comp-read-get-candidates
+                                         ;; History should be quoted to
+                                         ;; force `helm-comp-read-get-candidates'
+                                         ;; to use predicate against
+                                         ;; symbol and not string.
+                                         (or history 'extended-command-history)
+                                         ;; Ensure using empty string to
+                                         ;; not defeat helm matching fns [1]
+                                         pred nil nil ""))
+                       :fuzzy-match t)
                     ,(helm-make-source "Emacs Commands" 'helm-M-x-class
-                       :match-dynamic helm-M-x-use-completion-styles
-                       :candidates
-                       (if helm-M-x-use-completion-styles
-                           (helm-dynamic-completion
-                            collection pred
-                            nil metadata t)
-                         (lambda () (helm-comp-read-get-candidates
-                                     ;; [1] Same comment as above.
-                                     collection pred nil nil "")))
-                       :fuzzy-match (null helm-M-x-use-completion-styles))))
+                       :data (lambda () (helm-comp-read-get-candidates
+                                         ;; [1] Same comment as above.
+                                         collection pred nil nil ""))
+                       :fuzzy-match t)))
          (prompt (concat (cond
                           ((eq helm-M-x-prefix-argument '-) "- ")
                           ((and (consp helm-M-x-prefix-argument)

```

**Comment by gmoutso** [comment] 2021-06-24 11:25
yes it does, thank you! With a full working config from emacs 27 works the same. Not only it does not repeat the characters, helm-M-x is also not sluggish.

**Comment by gmoutso** [comment] 2021-06-24 11:42
`helm-M-x` is fixed, but I noticed the same issue (repeating chars and sluggish) in the `helm-describe-variable` function. I had thought it was only appearing in M-x...

**Comment by thierryvolpiatto** [comment] 2021-06-24 13:20
George Moutsopoulos ***@***.***> writes:

> helm-M-x is fixed, but I noticed the same issue (repeating chars and
> sluggish) in the helm-describe-variable function. I had thought it was
> only appearing in M-x...

You can fix it with `(setq helm-completion-style 'helm)` which will be
the default in next release.


-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2021-06-24 13:21
George Moutsopoulos ***@***.***> writes:

> yes it does, thank you! With a full working config from emacs 27 works
> the same. Not only it does not repeat the characters, helm-M-x is also
> not sluggish.

Great, this will be merged soon, thanks for testing.

-- 
Thierry

**Closed** 2022-06-16 05:00 UTC
Labels: need_more_info, not_reproducible
