### ISSUE TITLE
helm-M-x very often start completely blank

### ISSUE THREAD

**Issue by zeltak** [emacs-helm/helm#789] opened 2015-01-02 07:21 UTC
Hi all, im a complete neewb to helm (and in general :)) but really loving helm
all works well apart from this weird issue in (helm-M-x):
it very often start completely blank and i have to kill and restart it to get the normal interface 
im using latest helm from emacs package manager (ELPA/Melpa)

any ideas, i would love to help debug this, but dont really know much about emacs.

best

Z

**Comment by thierryvolpiatto** [comment] 2015-01-03 07:03
zeltak <notifications@github.com> writes:

> Hi all, im a complete neewb to helm (and in general :)) but really loving helm
> all works well apart from this weird issue in (helm-M-x):
> it very often start completely blank and i have to kill and restart it to get the normal interface
> im using latest helm from emacs package manager (ELPA/Melpa)
>
> any ideas, i would love to help debug this, but dont really know much about emacs.

Not reproductible.
Are you sure you are using helm-M-x ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by zeltak** [comment] 2015-01-03 07:40
Hi and thx for the answer.
hmm im pretty sure, here is my relevant config

#+BEGIN_SRC emacs-lisp :results none
(global-set-key (kbd "M-x") 'helm-M-x)
#+END_SRC

fuzy search enabled for m-x:
#+BEGIN_SRC emacs-lisp :results none
(setq helm-M-x-fuzzy-match t) ;; optional fuzzy matching for helm-M-x
#+END_SRC


Also here is a link to a screencast showing the issue 

https://paste.xinu.at/cft/

thanks alot , would be very happy to try and debug this

best

Z

**Comment by thierryvolpiatto** [comment] 2015-01-03 08:22
zeltak <notifications@github.com> writes:

> Hi and thx for the answer.
> hmm im pretty sure, here is my relevant config
>
> #+BEGIN_SRC emacs-lisp :results none
> (global-set-key (kbd "M-x") 'helm-M-x)
> #+END_SRC
>
> fuzy search enabled for m-x:
> #+BEGIN_SRC emacs-lisp :results none
> (setq helm-M-x-fuzzy-match t) ;; optional fuzzy matching for helm-M-x
> #+END_SRC

Ok so you are using helm-M-x, can you try from ./emacs-helm.sh with and
without fuzzy enabled ?

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by tuhdo** [comment] 2015-01-03 20:01
I've just tried your `.emacs.d` (without all the `~/.emacs.g` stuffs and hard coded home directory). `helm-M-x` behaves fine on both Windows and Ubuntu. Could you tell us what's your Emacs version <kbd>M-x emacs-version</kbd>?

Could you do the following:

- <kbd>M-x elp-instrument-package</kbd> then enter `helm-M-x`; wait until `helm-M-x` is available and press <kbd>RET</kbd>.
- <kbd>M-x</kbd> (to start `helm-M-x`)
- Type a few things to make `helm-M-x` start matching.
- Then, delete the current pattern and enter `elp-results`.
- Paste the content of the buffer `*ELP Profiling Results*` here.

**Comment by zeltak** [comment] 2015-01-03 20:31
Hi again guys

tuhdo as requested:

helm-M-x-transformer-1                 75          0.4791014839  0.0063880197
helm-M-x-transformer-hist              38          0.289915465   0.0076293543
helm-M-x-transformer                   37          0.18984328    0.0051308994
helm-M-x-current-mode-map-alist        75          0.1427189940  0.0019029199
helm-M-x-get-major-mode-command-alist  75          0.1400556630  0.0018674088
helm-M-x--notify-prefix-arg            324         0.0007041319  2.173...e-06
helm-M-x                               1           0             0.0

happy to help with anything else

best

Z

**Comment by karljs** [comment] 2015-01-05 18:52
This just started happening to me as well using fuzzy matching (haven't had a chance to test with it disabled yet) in a recent version from Melpa on OS X.  It seems to be largely unpredictable but tends to only happen after several uses.

**Comment by balajisivaraman** [comment] 2015-01-11 19:26
Hi All, I suddenly started having this issue today, out of the blue, with no changes to my config or OS.

**Emacs Version**: GNU Emacs 24.4.1 (x86_64-unknown-linux-gnu, GTK+ Version 3.14.3) of 2014-10-21 on bitzer.hoetzel.info (I was using a >25.0 Emacs compiled from Git source when I first noticed the issue. I thought it was because of the version I was using. So I downgraded to the latest stable release, but I'm having the same issue.)

I am also on Arch Linux, same as @zeltak. I use the latest Helm from Melpa. [This](https://github.com/balajisivaraman/dot-emacs/blob/master/init.el) is my init.el file. It uses John Wiegley's Use-Package to load `helm-config`.

It should be noted that my issue differs from @zeltak's. I am having a blank Helm-Execute-Extended-Command all the time. Every time I open Emacs. And I'm having issues with Helm in general. Switching buffers, Opening files (`C-x,C-f` is a blank list in a directory with a lot of files for example) etc.

I'll be happy to provide any additional information as needed. A few screenshots below. (First one is `C-x C-f`. The second one is `M-x`.)

![image](https://cloud.githubusercontent.com/assets/1876249/5696391/44e62954-99f5-11e4-86bc-6465437ef03a.png)
![image](https://cloud.githubusercontent.com/assets/1876249/5696393/5a1c8b74-99f5-11e4-8b20-a3cf92f2c196.png)

**Comment by thierryvolpiatto** [comment] 2015-01-11 19:50
Balaji Sivaraman <notifications@github.com> writes:

> I'll be happy to provide any additional information as needed.

Can you uninstall completely helm, verify you have no more helm files in
your load-path, and reinstall helm preferably from git.
Once done use ./emacs-helm.sh from your helm directory.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by balajisivaraman** [comment] 2015-01-11 20:05
@thierryvolpiatto, I've done the same. I deleted all traces of `helm` from my elpa directory. Then started Emacs to verify that nothing related to `helm` was loaded. (The only two commands that came when I pressed `M-x` and then typed in `helm` was `helm-imenu-anywhere` from `imenu-anywhere` and `helm-projectile` from `projectile`. But I cannot imagine those causing any conflicts.)

Then I followed the instructions in the Readme to install `helm` from the repository. The screenshot is below. The right side of the screen shows the `helm` directory installed from Git. The left side shows the result of launching `./emacs-helm.sh` and then pressing `M-x`.

![screenshot - 01122015 - 01 31 42 am](https://cloud.githubusercontent.com/assets/1876249/5696539/c997e868-99fa-11e4-9a12-88e778bb1df6.png)

As I said in my updated post, I'm not having this issue in my Windows machine.

**Comment by michael-heerdegen** [comment] 2015-01-11 22:29
Do you get any suspicious messages in *Messages* when the problem happens?

**Comment by larkery** [comment] 2015-01-12 10:28
I also experience this problem, when using a minimal test configuration in which I:

 - remove all emacs configuration
 - install helm from melpa
 - run `(require 'helm-config)`

This is on emacs24-lucid, on debian jessie.

The results I have look identical to the pictures by @balajisivaraman above, along with the behaviour; say I invoke `helm-M-x`, I get a blank list of commands, but typing in some text will occasionally show one or two results. It's definitely in error, as making the input longer should always reduce the number of results.

On a very similar configuration (my work computer; also lucid emacs, also debian jessie, also helm from melpa) I don't get the same problem. My home computer is much better than my work one, which makes me think it _could_ be a race condition somwhere?

I don't see anything in `*messages*`.

**Comment by thierryvolpiatto** [comment] 2015-01-12 11:17
Tom Hinton <notifications@github.com> writes:

> I also experience this problem, when using a minimal test configuration in which I:
>
>   * remove all emacs configuration
>   * install helm from melpa
>   * run (require 'helm-config)
>
> This is on emacs24-lucid, on debian jessie.
>
> The results I have look identical to the pictures by @balajisivaraman above, along with the behaviour; say I invoke helm-M-x, I get a blank list of commands, but typing in some text will occasionally show
> one or two results. It's definitely in error, as making the input longer should always reduce the number of results.
>
> On a very similar configuration (my work computer; also lucid emacs, also debian jessie, also helm from melpa) I don't get the same problem. My home computer is much better than my work one, which makes me
> think it could be a race condition somwhere?

Hmm, I don't experiment this problem on 4 different machines (only two
of them are quite fast, the two others are slow).

> I don't see anything in *messages*.

Can you try with previous versions of helm ?

Say 1.6.4 https://github.com/emacs-helm/helm/archive/v1.6.4.zip
or 1.6.5 https://github.com/emacs-helm/helm/archive/v1.6.5.zip

and always try with ./emacs-helm.sh.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-01-12 11:54
Tom Hinton <notifications@github.com> writes:

> I also experience this problem, when using a minimal test configuration in which I:
>
>   * remove all emacs configuration
>   * install helm from melpa

Also please try to reproduce installing from git, after removing the
elpa version.


-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by balajisivaraman** [comment] 2015-01-12 12:10
Hmm. That's very weird indeed. I created an empty directory and cloned `helm` and `emacs-async` into it. Then I built `helm` and created an `init.el` with just the following contents.

```emacs-lisp
(add-to-list 'load-path "~/Coding/emacs-lisp/balaji-testing-setup/helm/")
(add-to-list 'load-path "~/Coding/emacs-lisp/balaji-testing-setup/emacs-async/")
(require 'helm-config)
```

Calling `emacs-helm.sh` from this directory's `helm` folder opens up Emacs where everything works. Opening Emacs itself with the following command: `emacs -q --load init.el` (loading this directory's init file), also opens up Emacs with everything working fine.

So I'm wondering whether it could be an issue with conflicting packages. However, I didn't add any new packages yesterday to the best of my knowledge. I'll investigate further, possibly adding my usual packages one at a time to this new setup to see whether I can pinpoint the issue.

**Comment by thierryvolpiatto** [comment] 2015-01-12 12:57
Balaji Sivaraman <notifications@github.com> writes:

> Hmm. That's very weird indeed. I created an empty directory and cloned
> helm and emacs-async into it.

Note that when installing from git emacs-async is not mandatory, so you
can make an even simpler install with only:

(add-to-list 'load-path "~/Coding/emacs-lisp/balaji-testing-setup/helm/")
(require 'helm-config)

> Calling emacs-helm.sh from this directory's helm folder opens up Emacs
> where everything works. Opening Emacs itself with the following
> command: emacs -q --load init.el (loading this directory's init file),
> also opens up Emacs with everything working fine.

Any chance to have a look at this init.el ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by balajisivaraman** [comment] 2015-01-12 13:15
@thierryvolpiatto, I should've been clearer. When I said, "Opening Emacs itself with the following
 command: emacs -q --load init.el (loading this directory's init file),
 also opens up Emacs with everything working fine.", I meant the init file containing only those 3 lines which load up `helm`, then `emacs-async` and call `(require 'helm-config)`. Loading that init file makes Helm work properly.

Also confirmed that everything works fine even without `emacs-async`.

**Comment by balajisivaraman** [comment] 2015-01-13 17:36
@thierryvolpiatto As I was testing by adding packages one-by-one, I accidentally opened Emacs with my normal setup, and everything is working now. With absolutely no changes made to the configuration between yesterday and today. It seems to be an intermittent issue. I'll keep an eye out to see when it resurfaces.

**Comment by larkery** [comment] 2015-01-21 17:27
I have also found myself unable to reproduce on my own machine, to the extent that deleting everything and reinstalling the same versions made it go away. All I can imagine is that there is a nondeterministic bit somewhere, most likely during whatever happens during byte-compilation or first run of helm or some other early stage.

**Comment by thierryvolpiatto** [comment] 2015-01-21 19:44
Ok, I am now closing this as it seems it is more a problem of bad compilation of files or something, feel free to reopen if it reproduce again.

Thanks.

**Closed by thierryvolpiatto** 2015-01-21 19:44 UTC
Labels: bug, notreproductible
